export const config = {
  API_GATEWAY_BASE_URL: process.env.NEXT_PUBLIC_BACKEND_BASE_URL,
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET,
};