import { LspCompletionItem, MonacoKind } from './types';

export const C_API_COMPLETIONS: LspCompletionItem[] = [
  // ================================================================
  // stdio.h
  // ================================================================
  {
    label: 'printf',
    kind: MonacoKind.Function,
    detail: 'int printf(const char *format, ...)',
    documentation: 'Prints formatted output to stdout.',
    insertText: 'printf("${1:format}", ${2:args});',
    insertTextFormat: 2,
  },
  {
    label: 'scanf',
    kind: MonacoKind.Function,
    detail: 'int scanf(const char *format, ...)',
    documentation: 'Reads formatted input from stdin.',
    insertText: 'scanf("${1:format}", ${2:&var});',
    insertTextFormat: 2,
  },
  {
    label: 'puts',
    kind: MonacoKind.Function,
    detail: 'int puts(const char *s)',
    documentation: 'Prints a string to stdout.',
    insertText: 'puts(${1:s});',
    insertTextFormat: 2,
  },
  {
    label: 'putchar',
    kind: MonacoKind.Function,
    detail: 'int putchar(int c)',
    documentation: 'Writes a character to stdout.',
    insertText: 'putchar(${1:c});',
    insertTextFormat: 2,
  },
  {
    label: 'getchar',
    kind: MonacoKind.Function,
    detail: 'int getchar(void)',
    documentation: 'Reads a character from stdin.',
    insertText: 'getchar()',
  },
  {
    label: 'gets',
    kind: MonacoKind.Function,
    detail: 'char *gets(char *s)',
    documentation: 'Reads a line from stdin (deprecated).',
    insertText: 'gets(${1:s})',
    insertTextFormat: 2,
  },
  {
    label: 'fgets',
    kind: MonacoKind.Function,
    detail: 'char *fgets(char *s, int n, FILE *stream)',
    documentation: 'Reads a line from stream.',
    insertText: 'fgets(${1:buf}, ${2:size}, ${3:stdin});',
    insertTextFormat: 2,
  },
  {
    label: 'fscanf',
    kind: MonacoKind.Function,
    detail: 'int fscanf(FILE *stream, const char *format, ...)',
    documentation: 'Reads formatted input from a file.',
    insertText: 'fscanf(${1:file}, "${2:format}", ${3:args});',
    insertTextFormat: 2,
  },
  {
    label: 'fprintf',
    kind: MonacoKind.Function,
    detail: 'int fprintf(FILE *stream, const char *format, ...)',
    documentation: 'Prints formatted output to a file.',
    insertText: 'fprintf(${1:file}, "${2:format}", ${3:args});',
    insertTextFormat: 2,
  },
  {
    label: 'sprintf',
    kind: MonacoKind.Function,
    detail: 'int sprintf(char *buf, const char *format, ...)',
    documentation: 'Prints to a string.',
    insertText: 'sprintf(${1:buf}, "${2:format}", ${3:args});',
    insertTextFormat: 2,
  },
  {
    label: 'sscanf',
    kind: MonacoKind.Function,
    detail: 'int sscanf(const char *buf, const char *format, ...)',
    documentation: 'Reads from a string.',
    insertText: 'sscanf(${1:buf}, "${2:format}", ${3:args});',
    insertTextFormat: 2,
  },
  {
    label: 'snprintf',
    kind: MonacoKind.Function,
    detail: 'int snprintf(char *buf, size_t n, const char *format, ...)',
    documentation: 'Prints to a string with size limit.',
    insertText: 'snprintf(${1:buf}, ${2:size}, "${3:format}", ${4:args});',
    insertTextFormat: 2,
  },
  {
    label: 'FILE',
    kind: MonacoKind.Class,
    detail: 'stdio.h FILE type',
    documentation: 'Type representing a file stream.',
    insertText: 'FILE',
  },
  {
    label: 'stdin',
    kind: MonacoKind.Variable,
    detail: 'FILE *stdin',
    documentation: 'Standard input stream.',
    insertText: 'stdin',
  },
  {
    label: 'stdout',
    kind: MonacoKind.Variable,
    detail: 'FILE *stdout',
    documentation: 'Standard output stream.',
    insertText: 'stdout',
  },
  {
    label: 'stderr',
    kind: MonacoKind.Variable,
    detail: 'FILE *stderr',
    documentation: 'Standard error stream.',
    insertText: 'stderr',
  },
  {
    label: 'fopen',
    kind: MonacoKind.Function,
    detail: 'FILE *fopen(const char *filename, const char *mode)',
    documentation: 'Opens a file.',
    insertText: 'fopen("${1:filename}", "${2:r}");',
    insertTextFormat: 2,
  },
  {
    label: 'fclose',
    kind: MonacoKind.Function,
    detail: 'int fclose(FILE *stream)',
    documentation: 'Closes a file.',
    insertText: 'fclose(${1:file});',
    insertTextFormat: 2,
  },
  {
    label: 'fread',
    kind: MonacoKind.Function,
    detail: 'size_t fread(void *ptr, size_t size, size_t nmemb, FILE *stream)',
    documentation: 'Reads data from a file.',
    insertText: 'fread(${1:ptr}, ${2:size}, ${3:nmemb}, ${4:file});',
    insertTextFormat: 2,
  },
  {
    label: 'fwrite',
    kind: MonacoKind.Function,
    detail: 'size_t fwrite(const void *ptr, size_t size, size_t nmemb, FILE *stream)',
    documentation: 'Writes data to a file.',
    insertText: 'fwrite(${1:ptr}, ${2:size}, ${3:nmemb}, ${4:file});',
    insertTextFormat: 2,
  },
  {
    label: 'feof',
    kind: MonacoKind.Function,
    detail: 'int feof(FILE *stream)',
    documentation: 'Tests for end-of-file.',
    insertText: 'feof(${1:file})',
    insertTextFormat: 2,
  },
  {
    label: 'ferror',
    kind: MonacoKind.Function,
    detail: 'int ferror(FILE *stream)',
    documentation: 'Tests for file error.',
    insertText: 'ferror(${1:file})',
    insertTextFormat: 2,
  },
  {
    label: 'fseek',
    kind: MonacoKind.Function,
    detail: 'int fseek(FILE *stream, long offset, int whence)',
    documentation: 'Repositions the file offset.',
    insertText: 'fseek(${1:file}, ${2:offset}, ${3:SEEK_SET});',
    insertTextFormat: 2,
  },
  {
    label: 'ftell',
    kind: MonacoKind.Function,
    detail: 'long ftell(FILE *stream)',
    documentation: 'Returns current file position.',
    insertText: 'ftell(${1:file})',
    insertTextFormat: 2,
  },
  {
    label: 'rewind',
    kind: MonacoKind.Function,
    detail: 'void rewind(FILE *stream)',
    documentation: 'Sets file position to the beginning.',
    insertText: 'rewind(${1:file});',
    insertTextFormat: 2,
  },
  {
    label: 'SEEK_SET',
    kind: MonacoKind.Constant,
    detail: 'SEEK_SET',
    documentation: 'Seek from beginning of file.',
    insertText: 'SEEK_SET',
  },
  {
    label: 'SEEK_CUR',
    kind: MonacoKind.Constant,
    detail: 'SEEK_CUR',
    documentation: 'Seek from current position.',
    insertText: 'SEEK_CUR',
  },
  {
    label: 'SEEK_END',
    kind: MonacoKind.Constant,
    detail: 'SEEK_END',
    documentation: 'Seek from end of file.',
    insertText: 'SEEK_END',
  },

  // ================================================================
  // stdlib.h
  // ================================================================
  {
    label: 'malloc',
    kind: MonacoKind.Function,
    detail: 'void *malloc(size_t size)',
    documentation: 'Allocates memory.',
    insertText: 'malloc(${1:size})',
    insertTextFormat: 2,
  },
  {
    label: 'calloc',
    kind: MonacoKind.Function,
    detail: 'void *calloc(size_t nmemb, size_t size)',
    documentation: 'Allocates zero-initialized memory.',
    insertText: 'calloc(${1:nmemb}, ${2:size})',
    insertTextFormat: 2,
  },
  {
    label: 'realloc',
    kind: MonacoKind.Function,
    detail: 'void *realloc(void *ptr, size_t size)',
    documentation: 'Reallocates memory.',
    insertText: 'realloc(${1:ptr}, ${2:size})',
    insertTextFormat: 2,
  },
  {
    label: 'free',
    kind: MonacoKind.Function,
    detail: 'void free(void *ptr)',
    documentation: 'Frees allocated memory.',
    insertText: 'free(${1:ptr});',
    insertTextFormat: 2,
  },
  {
    label: 'atoi',
    kind: MonacoKind.Function,
    detail: 'int atoi(const char *nptr)',
    documentation: 'Converts string to int.',
    insertText: 'atoi(${1:str})',
    insertTextFormat: 2,
  },
  {
    label: 'atol',
    kind: MonacoKind.Function,
    detail: 'long atol(const char *nptr)',
    documentation: 'Converts string to long.',
    insertText: 'atol(${1:str})',
    insertTextFormat: 2,
  },
  {
    label: 'atof',
    kind: MonacoKind.Function,
    detail: 'double atof(const char *nptr)',
    documentation: 'Converts string to double.',
    insertText: 'atof(${1:str})',
    insertTextFormat: 2,
  },
  {
    label: 'strtol',
    kind: MonacoKind.Function,
    detail: 'long strtol(const char *nptr, char **endptr, int base)',
    documentation: 'Converts string to long.',
    insertText: 'strtol(${1:str}, ${2:&endptr}, ${3:10})',
    insertTextFormat: 2,
  },
  {
    label: 'strtoul',
    kind: MonacoKind.Function,
    detail: 'unsigned long strtoul(const char *nptr, char **endptr, int base)',
    documentation: 'Converts string to unsigned long.',
    insertText: 'strtoul(${1:str}, ${2:&endptr}, ${3:10})',
    insertTextFormat: 2,
  },
  {
    label: 'strtod',
    kind: MonacoKind.Function,
    detail: 'double strtod(const char *nptr, char **endptr)',
    documentation: 'Converts string to double.',
    insertText: 'strtod(${1:str}, ${2:&endptr})',
    insertTextFormat: 2,
  },
  {
    label: 'srand',
    kind: MonacoKind.Function,
    detail: 'void srand(unsigned int seed)',
    documentation: 'Seeds random number generator.',
    insertText: 'srand(${1:time(NULL)});',
    insertTextFormat: 2,
  },
  {
    label: 'rand',
    kind: MonacoKind.Function,
    detail: 'int rand(void)',
    documentation: 'Returns a pseudo-random integer.',
    insertText: 'rand()',
  },
  {
    label: 'RAND_MAX',
    kind: MonacoKind.Constant,
    detail: 'RAND_MAX',
    documentation: 'Maximum value returned by rand().',
    insertText: 'RAND_MAX',
  },
  {
    label: 'exit',
    kind: MonacoKind.Function,
    detail: 'void exit(int status)',
    documentation: 'Terminates the program.',
    insertText: 'exit(${1:0});',
    insertTextFormat: 2,
  },
  {
    label: 'abort',
    kind: MonacoKind.Function,
    detail: 'void abort(void)',
    documentation: 'Abnormal program termination.',
    insertText: 'abort();',
  },
  {
    label: 'atexit',
    kind: MonacoKind.Function,
    detail: 'int atexit(void (*function)(void))',
    documentation: 'Registers a function to call at exit.',
    insertText: 'atexit(${1:func});',
    insertTextFormat: 2,
  },
  {
    label: 'system',
    kind: MonacoKind.Function,
    detail: 'int system(const char *command)',
    documentation: 'Executes a system command.',
    insertText: 'system(${1:"command"});',
    insertTextFormat: 2,
  },
  {
    label: 'getenv',
    kind: MonacoKind.Function,
    detail: 'char *getenv(const char *name)',
    documentation: 'Gets an environment variable.',
    insertText: 'getenv(${1:"PATH"})',
    insertTextFormat: 2,
  },
  {
    label: 'abs',
    kind: MonacoKind.Function,
    detail: 'int abs(int j)',
    documentation: 'Absolute value of int.',
    insertText: 'abs(${1:j})',
    insertTextFormat: 2,
  },
  {
    label: 'labs',
    kind: MonacoKind.Function,
    detail: 'long labs(long j)',
    documentation: 'Absolute value of long.',
    insertText: 'labs(${1:j})',
    insertTextFormat: 2,
  },
  {
    label: 'qsort',
    kind: MonacoKind.Function,
    detail: 'void qsort(void *base, size_t nmemb, size_t size, int (*compar)(const void *, const void *))',
    documentation: 'Sorts an array.',
    insertText: 'qsort(${1:array}, ${2:n}, sizeof(${3:type}), ${4:compare});',
    insertTextFormat: 2,
  },
  {
    label: 'bsearch',
    kind: MonacoKind.Function,
    detail: 'void *bsearch(const void *key, const void *base, size_t nmemb, size_t size, int (*compar)(const void *, const void *))',
    documentation: 'Binary search in array.',
    insertText: 'bsearch(${1:&key}, ${2:base}, ${3:n}, sizeof(${4:type}), ${5:compare})',
    insertTextFormat: 2,
  },
  {
    label: 'NULL',
    kind: MonacoKind.Constant,
    detail: 'NULL',
    documentation: 'Null pointer constant.',
    insertText: 'NULL',
  },

  // ================================================================
  // string.h
  // ================================================================
  {
    label: 'strlen',
    kind: MonacoKind.Function,
    detail: 'size_t strlen(const char *s)',
    documentation: 'Returns string length.',
    insertText: 'strlen(${1:str})',
    insertTextFormat: 2,
  },
  {
    label: 'strcpy',
    kind: MonacoKind.Function,
    detail: 'char *strcpy(char *dest, const char *src)',
    documentation: 'Copies a string.',
    insertText: 'strcpy(${1:dest}, ${2:src});',
    insertTextFormat: 2,
  },
  {
    label: 'strncpy',
    kind: MonacoKind.Function,
    detail: 'char *strncpy(char *dest, const char *src, size_t n)',
    documentation: 'Copies n characters of a string.',
    insertText: 'strncpy(${1:dest}, ${2:src}, ${3:n});',
    insertTextFormat: 2,
  },
  {
    label: 'strcat',
    kind: MonacoKind.Function,
    detail: 'char *strcat(char *dest, const char *src)',
    documentation: 'Concatenates strings.',
    insertText: 'strcat(${1:dest}, ${2:src});',
    insertTextFormat: 2,
  },
  {
    label: 'strncat',
    kind: MonacoKind.Function,
    detail: 'char *strncat(char *dest, const char *src, size_t n)',
    documentation: 'Concatenates n characters.',
    insertText: 'strncat(${1:dest}, ${2:src}, ${3:n});',
    insertTextFormat: 2,
  },
  {
    label: 'strcmp',
    kind: MonacoKind.Function,
    detail: 'int strcmp(const char *s1, const char *s2)',
    documentation: 'Compares two strings.',
    insertText: 'strcmp(${1:s1}, ${2:s2})',
    insertTextFormat: 2,
  },
  {
    label: 'strncmp',
    kind: MonacoKind.Function,
    detail: 'int strncmp(const char *s1, const char *s2, size_t n)',
    documentation: 'Compares n characters.',
    insertText: 'strncmp(${1:s1}, ${2:s2}, ${3:n})',
    insertTextFormat: 2,
  },
  {
    label: 'strchr',
    kind: MonacoKind.Function,
    detail: 'char *strchr(const char *s, int c)',
    documentation: 'Finds first occurrence of a character.',
    insertText: "strchr(${1:s}, ${2:'c'})",
    insertTextFormat: 2,
  },
  {
    label: 'strrchr',
    kind: MonacoKind.Function,
    detail: 'char *strrchr(const char *s, int c)',
    documentation: 'Finds last occurrence of a character.',
    insertText: "strrchr(${1:s}, ${2:'c'})",
    insertTextFormat: 2,
  },
  {
    label: 'strstr',
    kind: MonacoKind.Function,
    detail: 'char *strstr(const char *haystack, const char *needle)',
    documentation: 'Finds first occurrence of a substring.',
    insertText: 'strstr(${1:haystack}, ${2:needle})',
    insertTextFormat: 2,
  },
  {
    label: 'strdup',
    kind: MonacoKind.Function,
    detail: 'char *strdup(const char *s)',
    documentation: 'Duplicates a string.',
    insertText: 'strdup(${1:s})',
    insertTextFormat: 2,
  },
  {
    label: 'strtok',
    kind: MonacoKind.Function,
    detail: 'char *strtok(char *s, const char *delim)',
    documentation: 'Splits a string into tokens.',
    insertText: 'strtok(${1:s}, ${2:delim})',
    insertTextFormat: 2,
  },
  {
    label: 'memcpy',
    kind: MonacoKind.Function,
    detail: 'void *memcpy(void *dest, const void *src, size_t n)',
    documentation: 'Copies memory.',
    insertText: 'memcpy(${1:dest}, ${2:src}, ${3:n});',
    insertTextFormat: 2,
  },
  {
    label: 'memmove',
    kind: MonacoKind.Function,
    detail: 'void *memmove(void *dest, const void *src, size_t n)',
    documentation: 'Copies memory (handles overlap).',
    insertText: 'memmove(${1:dest}, ${2:src}, ${3:n});',
    insertTextFormat: 2,
  },
  {
    label: 'memcmp',
    kind: MonacoKind.Function,
    detail: 'int memcmp(const void *s1, const void *s2, size_t n)',
    documentation: 'Compares memory.',
    insertText: 'memcmp(${1:s1}, ${2:s2}, ${3:n})',
    insertTextFormat: 2,
  },
  {
    label: 'memset',
    kind: MonacoKind.Function,
    detail: 'void *memset(void *s, int c, size_t n)',
    documentation: 'Fills memory with a value.',
    insertText: 'memset(${1:s}, ${2:0}, ${3:n});',
    insertTextFormat: 2,
  },

  // ================================================================
  // math.h
  // ================================================================
  {
    label: 'pow',
    kind: MonacoKind.Function,
    detail: 'double pow(double x, double y)',
    documentation: 'Computes x raised to power y.',
    insertText: 'pow(${1:x}, ${2:y})',
    insertTextFormat: 2,
  },
  {
    label: 'sqrt',
    kind: MonacoKind.Function,
    detail: 'double sqrt(double x)',
    documentation: 'Computes square root.',
    insertText: 'sqrt(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'cbrt',
    kind: MonacoKind.Function,
    detail: 'double cbrt(double x)',
    documentation: 'Computes cube root.',
    insertText: 'cbrt(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'sin',
    kind: MonacoKind.Function,
    detail: 'double sin(double x)',
    documentation: 'Sine function.',
    insertText: 'sin(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'cos',
    kind: MonacoKind.Function,
    detail: 'double cos(double x)',
    documentation: 'Cosine function.',
    insertText: 'cos(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'tan',
    kind: MonacoKind.Function,
    detail: 'double tan(double x)',
    documentation: 'Tangent function.',
    insertText: 'tan(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'asin',
    kind: MonacoKind.Function,
    detail: 'double asin(double x)',
    documentation: 'Arc sine.',
    insertText: 'asin(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'acos',
    kind: MonacoKind.Function,
    detail: 'double acos(double x)',
    documentation: 'Arc cosine.',
    insertText: 'acos(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'atan',
    kind: MonacoKind.Function,
    detail: 'double atan(double x)',
    documentation: 'Arc tangent.',
    insertText: 'atan(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'atan2',
    kind: MonacoKind.Function,
    detail: 'double atan2(double y, double x)',
    documentation: 'Two-argument arc tangent.',
    insertText: 'atan2(${1:y}, ${2:x})',
    insertTextFormat: 2,
  },
  {
    label: 'sinh',
    kind: MonacoKind.Function,
    detail: 'double sinh(double x)',
    documentation: 'Hyperbolic sine.',
    insertText: 'sinh(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'cosh',
    kind: MonacoKind.Function,
    detail: 'double cosh(double x)',
    documentation: 'Hyperbolic cosine.',
    insertText: 'cosh(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'tanh',
    kind: MonacoKind.Function,
    detail: 'double tanh(double x)',
    documentation: 'Hyperbolic tangent.',
    insertText: 'tanh(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'exp',
    kind: MonacoKind.Function,
    detail: 'double exp(double x)',
    documentation: 'Exponential e^x.',
    insertText: 'exp(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'log',
    kind: MonacoKind.Function,
    detail: 'double log(double x)',
    documentation: 'Natural logarithm.',
    insertText: 'log(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'log10',
    kind: MonacoKind.Function,
    detail: 'double log10(double x)',
    documentation: 'Base-10 logarithm.',
    insertText: 'log10(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'log2',
    kind: MonacoKind.Function,
    detail: 'double log2(double x)',
    documentation: 'Base-2 logarithm.',
    insertText: 'log2(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'ceil',
    kind: MonacoKind.Function,
    detail: 'double ceil(double x)',
    documentation: 'Ceiling function.',
    insertText: 'ceil(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'floor',
    kind: MonacoKind.Function,
    detail: 'double floor(double x)',
    documentation: 'Floor function.',
    insertText: 'floor(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'fabs',
    kind: MonacoKind.Function,
    detail: 'double fabs(double x)',
    documentation: 'Absolute value of double.',
    insertText: 'fabs(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'fmod',
    kind: MonacoKind.Function,
    detail: 'double fmod(double x, double y)',
    documentation: 'Remainder of x/y.',
    insertText: 'fmod(${1:x}, ${2:y})',
    insertTextFormat: 2,
  },
  {
    label: 'round',
    kind: MonacoKind.Function,
    detail: 'double round(double x)',
    documentation: 'Rounds to nearest integer.',
    insertText: 'round(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'trunc',
    kind: MonacoKind.Function,
    detail: 'double trunc(double x)',
    documentation: 'Truncates fractional part.',
    insertText: 'trunc(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'M_PI',
    kind: MonacoKind.Constant,
    detail: 'M_PI',
    documentation: 'Value of pi.',
    insertText: 'M_PI',
  },
  {
    label: 'M_E',
    kind: MonacoKind.Constant,
    detail: 'M_E',
    documentation: 'Value of e.',
    insertText: 'M_E',
  },
  {
    label: 'M_SQRT2',
    kind: MonacoKind.Constant,
    detail: 'M_SQRT2',
    documentation: 'Square root of 2.',
    insertText: 'M_SQRT2',
  },
  {
    label: 'INFINITY',
    kind: MonacoKind.Constant,
    detail: 'INFINITY',
    documentation: 'Positive infinity.',
    insertText: 'INFINITY',
  },
  {
    label: 'NAN',
    kind: MonacoKind.Constant,
    detail: 'NAN',
    documentation: 'Not-a-number.',
    insertText: 'NAN',
  },

  // ================================================================
  // ctype.h
  // ================================================================
  {
    label: 'isdigit',
    kind: MonacoKind.Function,
    detail: 'int isdigit(int c)',
    documentation: 'Tests for decimal digit.',
    insertText: 'isdigit(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'isalpha',
    kind: MonacoKind.Function,
    detail: 'int isalpha(int c)',
    documentation: 'Tests for alphabetic character.',
    insertText: 'isalpha(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'isalnum',
    kind: MonacoKind.Function,
    detail: 'int isalnum(int c)',
    documentation: 'Tests for alphanumeric.',
    insertText: 'isalnum(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'islower',
    kind: MonacoKind.Function,
    detail: 'int islower(int c)',
    documentation: 'Tests for lowercase.',
    insertText: 'islower(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'isupper',
    kind: MonacoKind.Function,
    detail: 'int isupper(int c)',
    documentation: 'Tests for uppercase.',
    insertText: 'isupper(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'isspace',
    kind: MonacoKind.Function,
    detail: 'int isspace(int c)',
    documentation: 'Tests for whitespace.',
    insertText: 'isspace(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'iscntrl',
    kind: MonacoKind.Function,
    detail: 'int iscntrl(int c)',
    documentation: 'Tests for control character.',
    insertText: 'iscntrl(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'isgraph',
    kind: MonacoKind.Function,
    detail: 'int isgraph(int c)',
    documentation: 'Tests for graphic character.',
    insertText: 'isgraph(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'isprint',
    kind: MonacoKind.Function,
    detail: 'int isprint(int c)',
    documentation: 'Tests for printable character.',
    insertText: 'isprint(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'ispunct',
    kind: MonacoKind.Function,
    detail: 'int ispunct(int c)',
    documentation: 'Tests for punctuation.',
    insertText: 'ispunct(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'isxdigit',
    kind: MonacoKind.Function,
    detail: 'int isxdigit(int c)',
    documentation: 'Tests for hexadecimal digit.',
    insertText: 'isxdigit(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'tolower',
    kind: MonacoKind.Function,
    detail: 'int tolower(int c)',
    documentation: 'Converts to lowercase.',
    insertText: 'tolower(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'toupper',
    kind: MonacoKind.Function,
    detail: 'int toupper(int c)',
    documentation: 'Converts to uppercase.',
    insertText: 'toupper(${1:c})',
    insertTextFormat: 2,
  },

  // ================================================================
  // time.h
  // ================================================================
  {
    label: 'time',
    kind: MonacoKind.Function,
    detail: 'time_t time(time_t *timer)',
    documentation: 'Gets current calendar time.',
    insertText: 'time(NULL)',
  },
  {
    label: 'difftime',
    kind: MonacoKind.Function,
    detail: 'double difftime(time_t end, time_t beginning)',
    documentation: 'Computes time difference.',
    insertText: 'difftime(${1:end}, ${2:begin})',
    insertTextFormat: 2,
  },
  {
    label: 'ctime',
    kind: MonacoKind.Function,
    detail: 'char *ctime(const time_t *timep)',
    documentation: 'Converts time to string.',
    insertText: 'ctime(&${1:time})',
    insertTextFormat: 2,
  },
  {
    label: 'ctime_r',
    kind: MonacoKind.Function,
    detail: 'char *ctime_r(const time_t *timep, char *buf)',
    documentation: 'Thread-safe ctime.',
    insertText: 'ctime_r(&${1:time}, ${2:buf})',
    insertTextFormat: 2,
  },
  {
    label: 'localtime',
    kind: MonacoKind.Function,
    detail: 'struct tm *localtime(const time_t *timep)',
    documentation: 'Converts to local time.',
    insertText: 'localtime(&${1:time})',
    insertTextFormat: 2,
  },
  {
    label: 'localtime_r',
    kind: MonacoKind.Function,
    detail: 'struct tm *localtime_r(const time_t *timep, struct tm *result)',
    documentation: 'Thread-safe localtime.',
    insertText: 'localtime_r(&${1:time}, ${2:&result})',
    insertTextFormat: 2,
  },
  {
    label: 'gmtime',
    kind: MonacoKind.Function,
    detail: 'struct tm *gmtime(const time_t *timep)',
    documentation: 'Converts to UTC.',
    insertText: 'gmtime(&${1:time})',
    insertTextFormat: 2,
  },
  {
    label: 'mktime',
    kind: MonacoKind.Function,
    detail: 'time_t mktime(struct tm *timeptr)',
    documentation: 'Converts struct tm to time_t.',
    insertText: 'mktime(${1:&tm})',
    insertTextFormat: 2,
  },
  {
    label: 'strftime',
    kind: MonacoKind.Function,
    detail: 'size_t strftime(char *s, size_t max, const char *format, const struct tm *tm)',
    documentation: 'Formats time as string.',
    insertText: 'strftime(${1:buf}, ${2:size}, "${3:%Y-%m-%d %H:%M:%S}", ${4:&tm});',
    insertTextFormat: 2,
  },
  {
    label: 'clock',
    kind: MonacoKind.Function,
    detail: 'clock_t clock(void)',
    documentation: 'Returns processor time used.',
    insertText: 'clock()',
  },

  // ================================================================
  // stdbool.h
  // ================================================================
  {
    label: 'bool',
    kind: MonacoKind.Keyword,
    detail: '_Bool (stdbool.h)',
    documentation: 'Boolean type.',
    insertText: '_Bool',
  },
  {
    label: 'true',
    kind: MonacoKind.Constant,
    detail: 'true',
    documentation: 'Boolean true value.',
    insertText: 'true',
  },
  {
    label: 'false',
    kind: MonacoKind.Constant,
    detail: 'false',
    documentation: 'Boolean false value.',
    insertText: 'false',
  },

  // ================================================================
  // limits.h
  // ================================================================
  {
    label: 'INT_MAX',
    kind: MonacoKind.Constant,
    detail: 'INT_MAX',
    documentation: 'Maximum value of int.',
    insertText: 'INT_MAX',
  },
  {
    label: 'INT_MIN',
    kind: MonacoKind.Constant,
    detail: 'INT_MIN',
    documentation: 'Minimum value of int.',
    insertText: 'INT_MIN',
  },
  {
    label: 'LONG_MAX',
    kind: MonacoKind.Constant,
    detail: 'LONG_MAX',
    documentation: 'Maximum value of long.',
    insertText: 'LONG_MAX',
  },
  {
    label: 'LONG_MIN',
    kind: MonacoKind.Constant,
    detail: 'LONG_MIN',
    documentation: 'Minimum value of long.',
    insertText: 'LONG_MIN',
  },
  {
    label: 'CHAR_MAX',
    kind: MonacoKind.Constant,
    detail: 'CHAR_MAX',
    documentation: 'Maximum value of char.',
    insertText: 'CHAR_MAX',
  },
  {
    label: 'CHAR_MIN',
    kind: MonacoKind.Constant,
    detail: 'CHAR_MIN',
    documentation: 'Minimum value of char.',
    insertText: 'CHAR_MIN',
  },
  {
    label: 'SCHAR_MAX',
    kind: MonacoKind.Constant,
    detail: 'SCHAR_MAX',
    documentation: 'Maximum signed char.',
    insertText: 'SCHAR_MAX',
  },
  {
    label: 'SCHAR_MIN',
    kind: MonacoKind.Constant,
    detail: 'SCHAR_MIN',
    documentation: 'Minimum signed char.',
    insertText: 'SCHAR_MIN',
  },
  {
    label: 'UCHAR_MAX',
    kind: MonacoKind.Constant,
    detail: 'UCHAR_MAX',
    documentation: 'Maximum unsigned char.',
    insertText: 'UCHAR_MAX',
  },
  {
    label: 'UINT_MAX',
    kind: MonacoKind.Constant,
    detail: 'UINT_MAX',
    documentation: 'Maximum unsigned int.',
    insertText: 'UINT_MAX',
  },
  {
    label: 'ULONG_MAX',
    kind: MonacoKind.Constant,
    detail: 'ULONG_MAX',
    documentation: 'Maximum unsigned long.',
    insertText: 'ULONG_MAX',
  },
  {
    label: 'CHAR_BIT',
    kind: MonacoKind.Constant,
    detail: 'CHAR_BIT',
    documentation: 'Number of bits in a char.',
    insertText: 'CHAR_BIT',
  },
  {
    label: 'sizeof',
    kind: MonacoKind.Keyword,
    detail: 'sizeof operator',
    documentation: 'Size of a type or variable.',
    insertText: 'sizeof(${1:type})',
    insertTextFormat: 2,
  },

  // ================================================================
  // Control flow snippets
  // ================================================================
  {
    label: 'if',
    kind: MonacoKind.Snippet,
    detail: 'if statement',
    documentation: 'If statement snippet.',
    insertText: 'if (${1:condition}) {\n\t${2:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'if-else',
    kind: MonacoKind.Snippet,
    detail: 'if-else statement',
    documentation: 'If-else statement snippet.',
    insertText: 'if (${1:condition}) {\n\t${2:// code}\n} else {\n\t${3:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'for',
    kind: MonacoKind.Snippet,
    detail: 'for loop',
    documentation: 'For loop snippet.',
    insertText: 'for (${1:int} ${2:i} = 0; ${2:i} < ${3:n}; ${2:i}++) {\n\t${4:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'while',
    kind: MonacoKind.Snippet,
    detail: 'while loop',
    documentation: 'While loop snippet.',
    insertText: 'while (${1:condition}) {\n\t${2:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'do-while',
    kind: MonacoKind.Snippet,
    detail: 'do-while loop',
    documentation: 'Do-while loop snippet.',
    insertText: 'do {\n\t${1:// code}\n} while (${2:condition});',
    insertTextFormat: 2,
  },
  {
    label: 'switch',
    kind: MonacoKind.Snippet,
    detail: 'switch statement',
    documentation: 'Switch statement snippet.',
    insertText: 'switch (${1:expr}) {\n\tcase ${2:val1}:\n\t\t${3:// code}\n\t\tbreak;\n\tcase ${4:val2}:\n\t\t${5:// code}\n\t\tbreak;\n\tdefault:\n\t\t${6:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'main',
    kind: MonacoKind.Snippet,
    detail: 'int main(int argc, char *argv[])',
    documentation: 'Main function snippet.',
    insertText: 'int main(int argc, char *argv[]) {\n\t${1:// code}\n\treturn 0;\n}',
    insertTextFormat: 2,
  },
];