'use client';

import { LspCompletionItem, MonacoKind } from './types';

// ─────────────────────────────────────────────────────────────────
// C++ Standard Library Completions
// ─────────────────────────────────────────────────────────────────

export const CPP_API_COMPLETIONS: LspCompletionItem[] = [
  // ─── iostream ────────────────────────────────────────────────
  {
    label: 'cout',
    kind: MonacoKind.Variable,
    detail: 'std::ostream &cout',
    documentation: 'Standard output stream.',
    insertText: 'std::cout',
  },
  {
    label: 'cin',
    kind: MonacoKind.Variable,
    detail: 'std::istream &cin',
    documentation: 'Standard input stream.',
    insertText: 'std::cin',
  },
  {
    label: 'cerr',
    kind: MonacoKind.Variable,
    detail: 'std::ostream &cerr',
    documentation: 'Standard error stream.',
    insertText: 'std::cerr',
  },
  {
    label: 'clog',
    kind: MonacoKind.Variable,
    detail: 'std::ostream &clog',
    documentation: 'Standard log stream.',
    insertText: 'std::clog',
  },
  {
    label: 'endl',
    kind: MonacoKind.Variable,
    detail: 'std::endl',
    documentation: 'Line feed manipulator.',
    insertText: 'std::endl',
  },
  {
    label: 'std::cout',
    kind: MonacoKind.Variable,
    detail: 'std::ostream &std::cout',
    documentation: 'Standard output stream.',
    insertText: 'std::cout',
  },
  {
    label: 'std::cin',
    kind: MonacoKind.Variable,
    detail: 'std::istream &std::cin',
    documentation: 'Standard input stream.',
    insertText: 'std::cin',
  },
  {
    label: 'std::endl',
    kind: MonacoKind.Variable,
    detail: 'std::ostream &std::endl',
    documentation: 'Line feed manipulator.',
    insertText: 'std::endl',
  },

  // ─── fstream ─────────────────────────────────────────────────
  {
    label: 'std::fstream',
    kind: MonacoKind.Class,
    detail: 'std::fstream',
    documentation: 'File stream class.',
    insertText: 'std::fstream ${1:fs}("${2:file.txt}", std::ios::in);',
    insertTextFormat: 2,
  },
  {
    label: 'std::ifstream',
    kind: MonacoKind.Class,
    detail: 'std::ifstream',
    documentation: 'Input file stream.',
    insertText: 'std::ifstream ${1:ifile}("${2:file.txt}");',
    insertTextFormat: 2,
  },
  {
    label: 'std::ofstream',
    kind: MonacoKind.Class,
    detail: 'std::ofstream',
    documentation: 'Output file stream.',
    insertText: 'std::ofstream ${1:ofile}("${2:file.txt}");',
    insertTextFormat: 2,
  },
  {
    label: 'std::ios::in',
    kind: MonacoKind.Constant,
    detail: 'std::ios::in',
    documentation: 'Open file for reading.',
    insertText: 'std::ios::in',
  },
  {
    label: 'std::ios::out',
    kind: MonacoKind.Constant,
    detail: 'std::ios::out',
    documentation: 'Open file for writing.',
    insertText: 'std::ios::out',
  },
  {
    label: 'std::ios::app',
    kind: MonacoKind.Constant,
    detail: 'std::ios::app',
    documentation: 'Append to end of file.',
    insertText: 'std::ios::app',
  },
  {
    label: 'std::ios::ate',
    kind: MonacoKind.Constant,
    detail: 'std::ios::ate',
    documentation: 'Open and seek to end.',
    insertText: 'std::ios::ate',
  },
  {
    label: 'std::ios::trunc',
    kind: MonacoKind.Constant,
    detail: 'std::ios::trunc',
    documentation: 'Truncate file.',
    insertText: 'std::ios::trunc',
  },
  {
    label: 'std::ios::binary',
    kind: MonacoKind.Constant,
    detail: 'std::ios::binary',
    documentation: 'Binary mode.',
    insertText: 'std::ios::binary',
  },

  // ─── vector ─────────────────────────────────────────────────
  {
    label: 'std::vector',
    kind: MonacoKind.Class,
    detail: 'std::vector<T>',
    documentation: 'Dynamic array container.',
    insertText: 'std::vector<${1:int}> ${2:v};',
    insertTextFormat: 2,
  },
  {
    label: 'v.push_back',
    kind: MonacoKind.Method,
    detail: 'void push_back(const T& value)',
    documentation: 'Adds element to end.',
    insertText: 'v.push_back(${1:value});',
    insertTextFormat: 2,
  },
  {
    label: 'v.at',
    kind: MonacoKind.Method,
    detail: 'T& at(size_t pos)',
    documentation: 'Access element with bounds check.',
    insertText: 'v.at(${1:index})',
    insertTextFormat: 2,
  },
  {
    label: 'v.size',
    kind: MonacoKind.Method,
    detail: 'size_t size()',
    documentation: 'Returns number of elements.',
    insertText: 'v.size()',
  },
  {
    label: 'v.empty',
    kind: MonacoKind.Method,
    detail: 'bool empty()',
    documentation: 'Checks if vector is empty.',
    insertText: 'v.empty()',
  },
  {
    label: 'v.clear',
    kind: MonacoKind.Method,
    detail: 'void clear()',
    documentation: 'Removes all elements.',
    insertText: 'v.clear();',
    insertTextFormat: 2,
  },
  {
    label: 'v.resize',
    kind: MonacoKind.Method,
    detail: 'void resize(size_t count)',
    documentation: 'Changes vector size.',
    insertText: 'v.resize(${1:size});',
    insertTextFormat: 2,
  },
  {
    label: 'v.front',
    kind: MonacoKind.Method,
    detail: 'T& front()',
    documentation: 'Returns first element.',
    insertText: 'v.front()',
  },
  {
    label: 'v.back',
    kind: MonacoKind.Method,
    detail: 'T& back()',
    documentation: 'Returns last element.',
    insertText: 'v.back()',
  },
  {
    label: 'v.begin',
    kind: MonacoKind.Method,
    detail: 'iterator begin()',
    documentation: 'Returns iterator to beginning.',
    insertText: 'v.begin()',
  },
  {
    label: 'v.end',
    kind: MonacoKind.Method,
    detail: 'iterator end()',
    documentation: 'Returns iterator to end.',
    insertText: 'v.end()',
  },
  {
    label: 'v.rbegin',
    kind: MonacoKind.Method,
    detail: 'reverse_iterator rbegin()',
    documentation: 'Returns reverse iterator.',
    insertText: 'v.rbegin()',
  },
  {
    label: 'v.rend',
    kind: MonacoKind.Method,
    detail: 'reverse_iterator rend()',
    documentation: 'Returns reverse end.',
    insertText: 'v.rend()',
  },
  {
    label: 'v.insert',
    kind: MonacoKind.Method,
    detail: 'iterator insert(const_iterator pos, const T& value)',
    documentation: 'Inserts element.',
    insertText: 'v.insert(${1:pos}, ${2:value});',
    insertTextFormat: 2,
  },
  {
    label: 'v.erase',
    kind: MonacoKind.Method,
    detail: 'iterator erase(const_iterator pos)',
    documentation: 'Removes element.',
    insertText: 'v.erase(${1:pos});',
    insertTextFormat: 2,
  },
  {
    label: 'v.pop_back',
    kind: MonacoKind.Method,
    detail: 'void pop_back()',
    documentation: 'Removes last element.',
    insertText: 'v.pop_back();',
    insertTextFormat: 2,
  },

  // ─── string ───────────────────────────────────────────────────
  {
    label: 'std::string',
    kind: MonacoKind.Class,
    detail: 'std::string',
    documentation: 'String class.',
    insertText: 'std::string ${1:s};',
    insertTextFormat: 2,
  },
  {
    label: 's.length',
    kind: MonacoKind.Method,
    detail: 'size_t length()',
    documentation: 'Returns string length.',
    insertText: 's.length()',
  },
  {
    label: 's.size',
    kind: MonacoKind.Method,
    detail: 'size_t size()',
    documentation: 'Returns string length.',
    insertText: 's.size()',
  },
  {
    label: 's.substr',
    kind: MonacoKind.Method,
    detail: 'std::string substr(size_t pos, size_t len)',
    documentation: 'Returns substring.',
    insertText: 's.substr(${1:pos}, ${2:len})',
    insertTextFormat: 2,
  },
  {
    label: 's.find',
    kind: MonacoKind.Method,
    detail: 'size_t find(const std::string& str)',
    documentation: 'Finds first occurrence.',
    insertText: 's.find(${1:str})',
    insertTextFormat: 2,
  },
  {
    label: 's.rfind',
    kind: MonacoKind.Method,
    detail: 'size_t rfind(const std::string& str)',
    documentation: 'Finds last occurrence.',
    insertText: 's.rfind(${1:str})',
    insertTextFormat: 2,
  },
  {
    label: 's.replace',
    kind: MonacoKind.Method,
    detail: "std::string& replace(size_t pos, size_t len, const std::string& str)",
    documentation: 'Replaces substring.',
    insertText: 's.replace(${1:pos}, ${2:len}, ${3:str});',
    insertTextFormat: 2,
  },
  {
    label: 's.compare',
    kind: MonacoKind.Method,
    detail: 'int compare(const std::string& str)',
    documentation: 'Compares strings.',
    insertText: 's.compare(${1:str})',
    insertTextFormat: 2,
  },
  {
    label: 's.append',
    kind: MonacoKind.Method,
    detail: 'std::string& append(const std::string& str)',
    documentation: 'Appends to string.',
    insertText: 's.append(${1:str});',
    insertTextFormat: 2,
  },
  {
    label: 's.push_back',
    kind: MonacoKind.Method,
    detail: 'void push_back(char c)',
    documentation: 'Appends a character.',
    insertText: "s.push_back(${1:'c'});",
    insertTextFormat: 2,
  },
  {
    label: 's.pop_back',
    kind: MonacoKind.Method,
    detail: 'void pop_back()',
    documentation: 'Removes last character.',
    insertText: 's.pop_back();',
    insertTextFormat: 2,
  },
  {
    label: 's.empty',
    kind: MonacoKind.Method,
    detail: 'bool empty()',
    documentation: 'Checks if string is empty.',
    insertText: 's.empty()',
  },
  {
    label: 's.clear',
    kind: MonacoKind.Method,
    detail: 'void clear()',
    documentation: 'Clears the string.',
    insertText: 's.clear();',
    insertTextFormat: 2,
  },
  {
    label: 's.c_str',
    kind: MonacoKind.Method,
    detail: 'const char* c_str()',
    documentation: 'Returns C-string.',
    insertText: 's.c_str()',
  },
  {
    label: 's.data',
    kind: MonacoKind.Method,
    detail: 'const char* data()',
    documentation: 'Returns character data.',
    insertText: 's.data()',
  },
  {
    label: 's.begin',
    kind: MonacoKind.Method,
    detail: 'iterator begin()',
    documentation: 'Returns iterator to beginning.',
    insertText: 's.begin()',
  },
  {
    label: 's.end',
    kind: MonacoKind.Method,
    detail: 'iterator end()',
    documentation: 'Returns iterator to end.',
    insertText: 's.end()',
  },
  {
    label: 'std::to_string',
    kind: MonacoKind.Function,
    detail: 'std::string to_string(int value)',
    documentation: 'Converts value to string.',
    insertText: 'std::to_string(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'std::stoi',
    kind: MonacoKind.Function,
    detail: 'int stoi(const std::string& str)',
    documentation: 'Converts string to int.',
    insertText: 'std::stoi(${1:s})',
    insertTextFormat: 2,
  },
  {
    label: 'std::stol',
    kind: MonacoKind.Function,
    detail: 'long stol(const std::string& str)',
    documentation: 'Converts string to long.',
    insertText: 'std::stol(${1:s})',
    insertTextFormat: 2,
  },
  {
    label: 'std::stod',
    kind: MonacoKind.Function,
    detail: 'double stod(const std::string& str)',
    documentation: 'Converts string to double.',
    insertText: 'std::stod(${1:s})',
    insertTextFormat: 2,
  },

  // ─── map / unordered_map ──────────────────────────────────────
  {
    label: 'std::map',
    kind: MonacoKind.Class,
    detail: 'std::map<K, V>',
    documentation: 'Sorted key-value container.',
    insertText: 'std::map<${1:string}, ${2:int}> ${3:m};',
    insertTextFormat: 2,
  },
  {
    label: 'std::unordered_map',
    kind: MonacoKind.Class,
    detail: 'std::unordered_map<K, V>',
    documentation: 'Hash table key-value container.',
    insertText: 'std::unordered_map<${1:string}, ${2:int}> ${3:um};',
    insertTextFormat: 2,
  },
  {
    label: 'm[key]',
    kind: MonacoKind.Method,
    detail: 'T& operator[](const K& key)',
    documentation: 'Access or insert element.',
    insertText: 'm[${1:key}]',
    insertTextFormat: 2,
  },
  {
    label: 'm.at',
    kind: MonacoKind.Method,
    detail: 'T& at(const K& key)',
    documentation: 'Access element with bounds check.',
    insertText: 'm.at(${1:key})',
    insertTextFormat: 2,
  },
  {
    label: 'm.insert',
    kind: MonacoKind.Method,
    detail: 'pair<iterator, bool> insert(const pair& p)',
    documentation: 'Inserts element.',
    insertText: 'm.insert(std::make_pair(${1:key}, ${2:value}));',
    insertTextFormat: 2,
  },
  {
    label: 'm.erase',
    kind: MonacoKind.Method,
    detail: 'size_t erase(const K& key)',
    documentation: 'Removes element.',
    insertText: 'm.erase(${1:key});',
    insertTextFormat: 2,
  },
  {
    label: 'm.find',
    kind: MonacoKind.Method,
    detail: 'iterator find(const K& key)',
    documentation: 'Finds element.',
    insertText: 'm.find(${1:key})',
    insertTextFormat: 2,
  },
  {
    label: 'm.count',
    kind: MonacoKind.Method,
    detail: 'size_t count(const K& key)',
    documentation: 'Counts elements with key.',
    insertText: 'm.count(${1:key})',
    insertTextFormat: 2,
  },
  {
    label: 'm.size',
    kind: MonacoKind.Method,
    detail: 'size_t size()',
    documentation: 'Returns number of elements.',
    insertText: 'm.size()',
  },
  {
    label: 'm.empty',
    kind: MonacoKind.Method,
    detail: 'bool empty()',
    documentation: 'Checks if map is empty.',
    insertText: 'm.empty()',
  },
  {
    label: 'm.clear',
    kind: MonacoKind.Method,
    detail: 'void clear()',
    documentation: 'Removes all elements.',
    insertText: 'm.clear();',
    insertTextFormat: 2,
  },
  {
    label: 'm.begin',
    kind: MonacoKind.Method,
    detail: 'iterator begin()',
    documentation: 'Returns iterator to beginning.',
    insertText: 'm.begin()',
  },
  {
    label: 'm.end',
    kind: MonacoKind.Method,
    detail: 'iterator end()',
    documentation: 'Returns iterator to end.',
    insertText: 'm.end()',
  },

  // ─── set / unordered_set ──────────────────────────────────────
  {
    label: 'std::set',
    kind: MonacoKind.Class,
    detail: 'std::set<T>',
    documentation: 'Sorted set container.',
    insertText: 'std::set<${1:int}> ${2:s};',
    insertTextFormat: 2,
  },
  {
    label: 'std::unordered_set',
    kind: MonacoKind.Class,
    detail: 'std::unordered_set<T>',
    documentation: 'Hash table set.',
    insertText: 'std::unordered_set<${1:int}> ${2:us};',
    insertTextFormat: 2,
  },
  {
    label: 's.insert',
    kind: MonacoKind.Method,
    detail: 'pair<iterator, bool> insert(const T& value)',
    documentation: 'Inserts element.',
    insertText: 's.insert(${1:value});',
    insertTextFormat: 2,
  },
  {
    label: 's.erase',
    kind: MonacoKind.Method,
    detail: 'size_t erase(const T& value)',
    documentation: 'Removes element.',
    insertText: 's.erase(${1:value});',
    insertTextFormat: 2,
  },
  {
    label: 's.find',
    kind: MonacoKind.Method,
    detail: 'iterator find(const T& value)',
    documentation: 'Finds element.',
    insertText: 's.find(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 's.count',
    kind: MonacoKind.Method,
    detail: 'size_t count(const T& value)',
    documentation: 'Counts elements.',
    insertText: 's.count(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 's.size',
    kind: MonacoKind.Method,
    detail: 'size_t size()',
    documentation: 'Returns number of elements.',
    insertText: 's.size()',
  },
  {
    label: 's.empty',
    kind: MonacoKind.Method,
    detail: 'bool empty()',
    documentation: 'Checks if set is empty.',
    insertText: 's.empty()',
  },
  {
    label: 's.begin',
    kind: MonacoKind.Method,
    detail: 'iterator begin()',
    documentation: 'Returns iterator to beginning.',
    insertText: 's.begin()',
  },
  {
    label: 's.end',
    kind: MonacoKind.Method,
    detail: 'iterator end()',
    documentation: 'Returns iterator to end.',
    insertText: 's.end()',
  },

  // ─── algorithm ───────────────────────────────────────────────
  {
    label: 'std::sort',
    kind: MonacoKind.Function,
    detail: 'void sort(RandomIt first, RandomIt last)',
    documentation: 'Sorts range.',
    insertText: 'std::sort(${1:v}.begin(), ${2:v}.end());',
    insertTextFormat: 2,
  },
  {
    label: 'std::stable_sort',
    kind: MonacoKind.Function,
    detail: 'void stable_sort(RandomIt first, RandomIt last)',
    documentation: 'Stable sort.',
    insertText: 'std::stable_sort(${1:v}.begin(), ${2:v}.end());',
    insertTextFormat: 2,
  },
  {
    label: 'std::reverse',
    kind: MonacoKind.Function,
    detail: 'void reverse(BidirIt first, BidirIt last)',
    documentation: 'Reverses range.',
    insertText: 'std::reverse(${1:v}.begin(), ${2:v}.end());',
    insertTextFormat: 2,
  },
  {
    label: 'std::find',
    kind: MonacoKind.Function,
    detail: 'InputIt find(InputIt first, InputIt last, const T& value)',
    documentation: 'Finds element.',
    insertText: 'std::find(${1:v}.begin(), ${2:v}.end(), ${3:value})',
    insertTextFormat: 2,
  },
  {
    label: 'std::find_if',
    kind: MonacoKind.Function,
    detail: 'InputIt find_if(InputIt first, InputIt last, UnaryPredicate p)',
    documentation: 'Finds element satisfying predicate.',
    insertText: 'std::find_if(${1:v}.begin(), ${2:v}.end(), ${3:pred});',
    insertTextFormat: 2,
  },
  {
    label: 'std::count',
    kind: MonacoKind.Function,
    detail: 'size_t count(InputIt first, InputIt last, const T& value)',
    documentation: 'Counts occurrences.',
    insertText: 'std::count(${1:v}.begin(), ${2:v}.end(), ${3:value})',
    insertTextFormat: 2,
  },
  {
    label: 'std::count_if',
    kind: MonacoKind.Function,
    detail: 'size_t count_if(InputIt first, InputIt last, UnaryPredicate p)',
    documentation: 'Counts elements satisfying predicate.',
    insertText: 'std::count_if(${1:v}.begin(), ${2:v}.end(), ${3:pred});',
    insertTextFormat: 2,
  },
  {
    label: 'std::accumulate',
    kind: MonacoKind.Function,
    detail: 'T accumulate(InputIt first, InputIt last, T init)',
    documentation: 'Sums elements.',
    insertText: 'std::accumulate(${1:v}.begin(), ${2:v}.end(), ${3:0})',
    insertTextFormat: 2,
  },
  {
    label: 'std::max_element',
    kind: MonacoKind.Function,
    detail: 'ForwardIt max_element(ForwardIt first, ForwardIt last)',
    documentation: 'Finds maximum element.',
    insertText: 'std::max_element(${1:v}.begin(), ${2:v}.end())',
    insertTextFormat: 2,
  },
  {
    label: 'std::min_element',
    kind: MonacoKind.Function,
    detail: 'ForwardIt min_element(ForwardIt first, ForwardIt last)',
    documentation: 'Finds minimum element.',
    insertText: 'std::min_element(${1:v}.begin(), ${2:v}.end())',
    insertTextFormat: 2,
  },
  {
    label: 'std::minmax_element',
    kind: MonacoKind.Function,
    detail: 'pair<ForwardIt, ForwardIt> minmax_element(ForwardIt first, ForwardIt last)',
    documentation: 'Finds both min and max.',
    insertText: 'std::minmax_element(${1:v}.begin(), ${2:v}.end())',
    insertTextFormat: 2,
  },
  {
    label: 'std::binary_search',
    kind: MonacoKind.Function,
    detail: 'bool binary_search(ForwardIt first, ForwardIt last, const T& value)',
    documentation: 'Checks if value exists.',
    insertText: 'std::binary_search(${1:v}.begin(), ${2:v}.end(), ${3:value})',
    insertTextFormat: 2,
  },
  {
    label: 'std::lower_bound',
    kind: MonacoKind.Function,
    detail: 'ForwardIt lower_bound(ForwardIt first, ForwardIt last, const T& value)',
    documentation: 'Finds first not less than.',
    insertText: 'std::lower_bound(${1:v}.begin(), ${2:v}.end(), ${3:value})',
    insertTextFormat: 2,
  },
  {
    label: 'std::upper_bound',
    kind: MonacoKind.Function,
    detail: 'ForwardIt upper_bound(ForwardIt first, ForwardIt last, const T& value)',
    documentation: 'Finds first greater than.',
    insertText: 'std::upper_bound(${1:v}.begin(), ${2:v}.end(), ${3:value})',
    insertTextFormat: 2,
  },
  {
    label: 'std::equal_range',
    kind: MonacoKind.Function,
    detail: 'pair<ForwardIt, ForwardIt> equal_range(ForwardIt first, ForwardIt last, const T& value)',
    documentation: 'Finds range of equal elements.',
    insertText: 'std::equal_range(${1:v}.begin(), ${2:v}.end(), ${3:value})',
    insertTextFormat: 2,
  },
  {
    label: 'std::fill',
    kind: MonacoKind.Function,
    detail: 'void fill(ForwardIt first, ForwardIt last, const T& value)',
    documentation: 'Fills range with value.',
    insertText: 'std::fill(${1:v}.begin(), ${2:v}.end(), ${3:value});',
    insertTextFormat: 2,
  },
  {
    label: 'std::copy',
    kind: MonacoKind.Function,
    detail: 'OutputIt copy(InputIt first, InputIt last, OutputIt d_first)',
    documentation: 'Copies range.',
    insertText: 'std::copy(${1:v}.begin(), ${2:v}.end(), ${3:destination}.begin());',
    insertTextFormat: 2,
  },
  {
    label: 'std::move',
    kind: MonacoKind.Function,
    detail: 'OutputIt move(InputIt first, InputIt last, OutputIt d_first)',
    documentation: 'Moves range.',
    insertText: 'std::move(${1:v}.begin(), ${2:v}.end(), ${3:destination}.begin());',
    insertTextFormat: 2,
  },
  {
    label: 'std::unique',
    kind: MonacoKind.Function,
    detail: 'ForwardIt unique(ForwardIt first, ForwardIt last)',
    documentation: 'Removes consecutive duplicates.',
    insertText: 'std::unique(${1:v}.begin(), ${2:v}.end());',
    insertTextFormat: 2,
  },
  {
    label: 'std::remove',
    kind: MonacoKind.Function,
    detail: 'ForwardIt remove(ForwardIt first, ForwardIt last, const T& value)',
    documentation: 'Removes all equal elements.',
    insertText: 'std::remove(${1:v}.begin(), ${2:v}.end(), ${3:value});',
    insertTextFormat: 2,
  },
  {
    label: 'std::transform',
    kind: MonacoKind.Function,
    detail: 'OutputIt transform(InputIt first, InputIt last, OutputIt d_first, UnaryOperation op)',
    documentation: 'Applies function to range.',
    insertText: 'std::transform(${1:v}.begin(), ${2:v}.end(), ${3:result}.begin(), ${4:func});',
    insertTextFormat: 2,
  },
  {
    label: 'std::any_of',
    kind: MonacoKind.Function,
    detail: 'bool any_of(InputIt first, InputIt last, UnaryPredicate p)',
    documentation: 'Checks if any satisfies predicate.',
    insertText: 'std::any_of(${1:v}.begin(), ${2:v}.end(), ${3:pred})',
    insertTextFormat: 2,
  },
  {
    label: 'std::all_of',
    kind: MonacoKind.Function,
    detail: 'bool all_of(InputIt first, InputIt last, UnaryPredicate p)',
    documentation: 'Checks if all satisfy predicate.',
    insertText: 'std::all_of(${1:v}.begin(), ${2:v}.end(), ${3:pred})',
    insertTextFormat: 2,
  },
  {
    label: 'std::none_of',
    kind: MonacoKind.Function,
    detail: 'bool none_of(InputIt first, InputIt last, UnaryPredicate p)',
    documentation: 'Checks if none satisfy predicate.',
    insertText: 'std::none_of(${1:v}.begin(), ${2:v}.end(), ${3:pred})',
    insertTextFormat: 2,
  },
  {
    label: 'std::next_permutation',
    kind: MonacoKind.Function,
    detail: 'bool next_permutation(BidirIt first, BidirIt last)',
    documentation: 'Generates next permutation.',
    insertText: 'std::next_permutation(${1:v}.begin(), ${2:v}.end());',
    insertTextFormat: 2,
  },
  {
    label: 'std::prev_permutation',
    kind: MonacoKind.Function,
    detail: 'bool prev_permutation(BidirIt first, BidirIt last)',
    documentation: 'Generates previous permutation.',
    insertText: 'std::prev_permutation(${1:v}.begin(), ${2:v}.end());',
    insertTextFormat: 2,
  },

  // ─── functional ───────────────────────────────────────────────
  {
    label: 'std::function',
    kind: MonacoKind.Class,
    detail: 'std::function<R(Args...)>',
    documentation: 'Wrapper for callable.',
    insertText: 'std::function<${1:void()}> ${2:fn};',
    insertTextFormat: 2,
  },
  {
    label: 'std::bind',
    kind: MonacoKind.Function,
    detail: 'void bind(F&& f, Args&&... args)',
    documentation: 'Binds arguments.',
    insertText: 'std::bind(${1:f}, ${2:args})',
    insertTextFormat: 2,
  },
  {
    label: 'std::ref',
    kind: MonacoKind.Function,
    detail: 'reference_wrapper<T> ref(T& t)',
    documentation: 'Creates reference wrapper.',
    insertText: 'std::ref(${1:t})',
    insertTextFormat: 2,
  },
  {
    label: 'std::cref',
    kind: MonacoKind.Function,
    detail: 'reference_wrapper<const T> cref(const T& t)',
    documentation: 'Creates const reference wrapper.',
    insertText: 'std::cref(${1:t})',
    insertTextFormat: 2,
  },
  {
    label: 'std::placeholders::_1',
    kind: MonacoKind.Constant,
    detail: 'placeholder',
    documentation: 'Placeholder for first argument.',
    insertText: 'std::placeholders::_1',
  },
  {
    label: 'std::placeholders::_2',
    kind: MonacoKind.Constant,
    detail: 'placeholder',
    documentation: 'Placeholder for second argument.',
    insertText: 'std::placeholders::_2',
  },

  // ─── memory / smart pointers ─────────────────────────────────
  {
    label: 'std::unique_ptr',
    kind: MonacoKind.Class,
    detail: 'std::unique_ptr<T>',
    documentation: 'Exclusive ownership smart pointer.',
    insertText: 'std::unique_ptr<${1:T}> ${2:ptr} = std::make_unique<${1:T}>();',
    insertTextFormat: 2,
  },
  {
    label: 'std::shared_ptr',
    kind: MonacoKind.Class,
    detail: 'std::shared_ptr<T>',
    documentation: 'Shared ownership smart pointer.',
    insertText: 'std::shared_ptr<${1:T}> ${2:ptr} = std::make_shared<${1:T}>();',
    insertTextFormat: 2,
  },
  {
    label: 'std::make_unique',
    kind: MonacoKind.Function,
    detail: 'unique_ptr<T> make_unique(Args&&... args)',
    documentation: 'Creates unique_ptr.',
    insertText: 'std::make_unique<${1:T}>(${2:args})',
    insertTextFormat: 2,
  },
  {
    label: 'std::make_shared',
    kind: MonacoKind.Function,
    detail: 'shared_ptr<T> make_shared(Args&&... args)',
    documentation: 'Creates shared_ptr.',
    insertText: 'std::make_shared<${1:T}>(${2:args})',
    insertTextFormat: 2,
  },
  {
    label: 'std::weak_ptr',
    kind: MonacoKind.Class,
    detail: 'std::weak_ptr<T>',
    documentation: 'Non-owning smart pointer.',
    insertText: 'std::weak_ptr<${1:T}> ${2:wp};',
    insertTextFormat: 2,
  },
  {
    label: 'ptr.get',
    kind: MonacoKind.Method,
    detail: 'T* get()',
    documentation: 'Returns raw pointer.',
    insertText: 'ptr.get()',
  },
  {
    label: 'ptr.reset',
    kind: MonacoKind.Method,
    detail: 'void reset()',
    documentation: 'Releases ownership.',
    insertText: 'ptr.reset();',
    insertTextFormat: 2,
  },
  {
    label: 'ptr.release',
    kind: MonacoKind.Method,
    detail: 'T* release()',
    documentation: 'Releases ownership and returns pointer.',
    insertText: 'ptr.release();',
    insertTextFormat: 2,
  },
  {
    label: 'shared.use_count',
    kind: MonacoKind.Method,
    detail: 'long use_count()',
    documentation: 'Returns shared_ptr reference count.',
    insertText: 'shared.use_count()',
  },
  {
    label: 'weak.lock',
    kind: MonacoKind.Method,
    detail: 'shared_ptr<T> lock()',
    documentation: 'Lock weak_ptr to shared_ptr.',
    insertText: 'wp.lock()',
  },
  {
    label: 'std::auto_ptr',
    kind: MonacoKind.Class,
    detail: 'std::auto_ptr<T> (deprecated)',
    documentation: 'Auto pointer (deprecated).',
    insertText: 'std::auto_ptr<${1:T}>',
  },
  {
    label: 'std::allocator',
    kind: MonacoKind.Class,
    detail: 'std::allocator<T>',
    documentation: 'Default allocator.',
    insertText: 'std::allocator<${1:T}>',
  },

  // ─── thread ───────────────────────────────────────────────────
  {
    label: 'std::thread',
    kind: MonacoKind.Class,
    detail: 'std::thread',
    documentation: 'Thread class.',
    insertText: 'std::thread ${1:t}(${2:func});',
    insertTextFormat: 2,
  },
  {
    label: 't.join',
    kind: MonacoKind.Method,
    detail: 'void join()',
    documentation: 'Waits for thread to finish.',
    insertText: 't.join();',
    insertTextFormat: 2,
  },
  {
    label: 't.detach',
    kind: MonacoKind.Method,
    detail: 'void detach()',
    documentation: 'Detaches thread.',
    insertText: 't.detach();',
    insertTextFormat: 2,
  },
  {
    label: 't.joinable',
    kind: MonacoKind.Method,
    detail: 'bool joinable()',
    documentation: 'Checks if thread is joinable.',
    insertText: 't.joinable()',
  },
  {
    label: 'std::this_thread::get_id',
    kind: MonacoKind.Function,
    detail: 'thread::id get_id()',
    documentation: 'Gets current thread ID.',
    insertText: 'std::this_thread::get_id()',
  },
  {
    label: 'std::this_thread::sleep_for',
    kind: MonacoKind.Function,
    detail: 'void sleep_for(const duration& rel_time)',
    documentation: 'Sleep for duration.',
    insertText: 'std::this_thread::sleep_for(std::chrono::seconds(${1:1}));',
    insertTextFormat: 2,
  },
  {
    label: 'std::this_thread::sleep_until',
    kind: MonacoKind.Function,
    detail: 'void sleep_until(const time_point& abs_time)',
    documentation: 'Sleep until time point.',
    insertText: 'std::this_thread::sleep_until(${1:tp});',
    insertTextFormat: 2,
  },
  {
    label: 'std::this_thread::yield',
    kind: MonacoKind.Function,
    detail: 'void yield()',
    documentation: 'Yields execution.',
    insertText: 'std::this_thread::yield();',
    insertTextFormat: 2,
  },
  {
    label: 'std::mutex',
    kind: MonacoKind.Class,
    detail: 'std::mutex',
    documentation: 'Mutual exclusion.',
    insertText: 'std::mutex ${1:m};',
    insertTextFormat: 2,
  },
  {
    label: 'm.lock',
    kind: MonacoKind.Method,
    detail: 'void lock()',
    documentation: 'Locks the mutex.',
    insertText: 'm.lock();',
    insertTextFormat: 2,
  },
  {
    label: 'm.unlock',
    kind: MonacoKind.Method,
    detail: 'void unlock()',
    documentation: 'Unlocks the mutex.',
    insertText: 'm.unlock();',
    insertTextFormat: 2,
  },
  {
    label: 'm.try_lock',
    kind: MonacoKind.Method,
    detail: 'bool try_lock()',
    documentation: 'Tries to lock mutex.',
    insertText: 'm.try_lock()',
  },
  {
    label: 'std::lock_guard',
    kind: MonacoKind.Class,
    detail: 'std::lock_guard<T>',
    documentation: 'RAII mutex lock.',
    insertText: 'std::lock_guard<std::mutex> ${1:lock}(${2:m});',
    insertTextFormat: 2,
  },
  {
    label: 'std::unique_lock',
    kind: MonacoKind.Class,
    detail: 'std::unique_lock<T>',
    documentation: 'More flexible RAII lock.',
    insertText: 'std::unique_lock<std::mutex> ${1:lock}(${2:m});',
    insertTextFormat: 2,
  },

  // ─── optional / variant ───────────────────────────────────────
  {
    label: 'std::optional',
    kind: MonacoKind.Class,
    detail: 'std::optional<T>',
    documentation: 'Optional value container.',
    insertText: 'std::optional<${1:T}> ${2:opt};',
    insertTextFormat: 2,
  },
  {
    label: 'opt.has_value',
    kind: MonacoKind.Method,
    detail: 'bool has_value()',
    documentation: 'Checks if optional has value.',
    insertText: 'opt.has_value()',
  },
  {
    label: 'opt.value',
    kind: MonacoKind.Method,
    detail: 'T& value()',
    documentation: 'Returns value or throws.',
    insertText: 'opt.value()',
  },
  {
    label: 'opt.value_or',
    kind: MonacoKind.Method,
    detail: 'T value_or(T&& default_val)',
    documentation: 'Returns value or default.',
    insertText: 'opt.value_or(${1:default_val})',
    insertTextFormat: 2,
  },
  {
    label: 'opt.reset',
    kind: MonacoKind.Method,
    detail: 'void reset()',
    documentation: 'Empties the optional.',
    insertText: 'opt.reset();',
    insertTextFormat: 2,
  },
  {
    label: 'opt.emplace',
    kind: MonacoKind.Method,
    detail: 'template<typename U> T& emplace(U&& args)',
    documentation: 'Constructs value in place.',
    insertText: 'opt.emplace(${1:args});',
    insertTextFormat: 2,
  },
  {
    label: 'std::nullopt',
    kind: MonacoKind.Constant,
    detail: 'std::nullopt',
    documentation: 'Optional with no value.',
    insertText: 'std::nullopt',
  },
  {
    label: 'std::variant',
    kind: MonacoKind.Class,
    detail: 'std::variant<Ts...>',
    documentation: 'Type-safe union.',
    insertText: 'std::variant<${1:int}, ${2:string}, ${3:double}> ${4:v};',
    insertTextFormat: 2,
  },
  {
    label: 'std::get_if',
    kind: MonacoKind.Function,
    detail: 'T* get_if<T>(const variant* v)',
    documentation: 'Gets variant value if type matches.',
    insertText: 'std::get_if<${1:T}>(&${2:v})',
    insertTextFormat: 2,
  },
  {
    label: 'std::get',
    kind: MonacoKind.Function,
    detail: 'T& get<T>(variant& v)',
    documentation: 'Gets variant value.',
    insertText: 'std::get<${1:T}>(${2:v})',
    insertTextFormat: 2,
  },
  {
    label: 'v.index',
    kind: MonacoKind.Method,
    detail: 'size_t index()',
    documentation: 'Returns index of current type.',
    insertText: 'v.index()',
  },
  {
    label: 'v.valueless_by_exception',
    kind: MonacoKind.Method,
    detail: 'bool valueless_by_exception()',
    documentation: 'Checks if variant has no value.',
    insertText: 'v.valueless_by_exception()',
  },

  // ─── chrono (time) ────────────────────────────────────────────
  {
    label: 'std::chrono',
    kind: MonacoKind.Module,
    detail: 'std::chrono',
    documentation: 'Time utilities namespace.',
    insertText: 'std::chrono',
  },
  {
    label: 'std::chrono::seconds',
    kind: MonacoKind.Class,
    detail: 'std::chrono::seconds',
    documentation: 'Seconds duration.',
    insertText: 'std::chrono::seconds(${1:1})',
    insertTextFormat: 2,
  },
  {
    label: 'std::chrono::milliseconds',
    kind: MonacoKind.Class,
    detail: 'std::chrono::milliseconds',
    documentation: 'Milliseconds duration.',
    insertText: 'std::chrono::milliseconds(${1:1})',
    insertTextFormat: 2,
  },
  {
    label: 'std::chrono::microseconds',
    kind: MonacoKind.Class,
    detail: 'std::chrono::microseconds',
    documentation: 'Microseconds duration.',
    insertText: 'std::chrono::microseconds(${1:1})',
    insertTextFormat: 2,
  },
  {
    label: 'std::chrono::nanoseconds',
    kind: MonacoKind.Class,
    detail: 'std::chrono::nanoseconds',
    documentation: 'Nanoseconds duration.',
    insertText: 'std::chrono::nanoseconds(${1:1})',
    insertTextFormat: 2,
  },
  {
    label: 'std::chrono::minutes',
    kind: MonacoKind.Class,
    detail: 'std::chrono::minutes',
    documentation: 'Minutes duration.',
    insertText: 'std::chrono::minutes(${1:1})',
    insertTextFormat: 2,
  },
  {
    label: 'std::chrono::hours',
    kind: MonacoKind.Class,
    detail: 'std::chrono::hours',
    documentation: 'Hours duration.',
    insertText: 'std::chrono::hours(${1:1})',
    insertTextFormat: 2,
  },
  {
    label: 'std::chrono::steady_clock',
    kind: MonacoKind.Class,
    detail: 'std::chrono::steady_clock',
    documentation: 'Steady clock.',
    insertText: 'std::chrono::steady_clock',
  },
  {
    label: 'std::chrono::system_clock',
    kind: MonacoKind.Class,
    detail: 'std::chrono::system_clock',
    documentation: 'System wall clock.',
    insertText: 'std::chrono::system_clock',
  },
  {
    label: 'std::chrono::high_resolution_clock',
    kind: MonacoKind.Class,
    detail: 'std::chrono::high_resolution_clock',
    documentation: 'High resolution clock.',
    insertText: 'std::chrono::high_resolution_clock',
  },
  {
    label: 'std::chrono::now',
    kind: MonacoKind.Function,
    detail: 'time_point now()',
    documentation: 'Gets current time point.',
    insertText: 'std::chrono::steady_clock::now()',
  },

  // ─── tuple ────────────────────────────────────────────────────
  {
    label: 'std::tuple',
    kind: MonacoKind.Class,
    detail: 'std::tuple<Ts...>',
    documentation: 'Fixed-size collection of values.',
    insertText: 'std::tuple<${1:int}, ${2:string}> ${3:t};',
    insertTextFormat: 2,
  },
  {
    label: 'std::make_tuple',
    kind: MonacoKind.Function,
    detail: 'tuple make_tuple(Args&&... args)',
    documentation: 'Creates a tuple.',
    insertText: 'std::make_tuple(${1:a}, ${2:b})',
    insertTextFormat: 2,
  },
  {
    label: 'std::get<idx>',
    kind: MonacoKind.Function,
    detail: 'T& get<N>(tuple& t)',
    documentation: 'Gets element by index.',
    insertText: 'std::get<${1:0}>(${2:t})',
    insertTextFormat: 2,
  },
  {
    label: 't.size',
    kind: MonacoKind.Method,
    detail: 'size_t size()',
    documentation: 'Returns number of elements.',
    insertText: 'std::tuple_size<std::tuple<${1:int, double}>>::value',
  },

  // ─── utility / pair ──────────────────────────────────────────
  {
    label: 'std::pair',
    kind: MonacoKind.Class,
    detail: 'std::pair<T1, T2>',
    documentation: 'Two-element tuple.',
    insertText: 'std::pair<${1:int}, ${2:string}> ${3:p};',
    insertTextFormat: 2,
  },
  {
    label: 'std::make_pair',
    kind: MonacoKind.Function,
    detail: 'pair make_pair(T1&& x, T2&& y)',
    documentation: 'Creates a pair.',
    insertText: 'std::make_pair(${1:a}, ${2:b})',
    insertTextFormat: 2,
  },
  {
    label: 'p.first',
    kind: MonacoKind.Property,
    detail: 'T1 first',
    documentation: 'First element.',
    insertText: 'p.first',
  },
  {
    label: 'p.second',
    kind: MonacoKind.Property,
    detail: 'T2 second',
    documentation: 'Second element.',
    insertText: 'p.second',
  },

  // ─── cmath ────────────────────────────────────────────────────
  {
    label: 'std::abs',
    kind: MonacoKind.Function,
    detail: 'template<T> T abs(T value)',
    documentation: 'Absolute value.',
    insertText: 'std::abs(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::pow',
    kind: MonacoKind.Function,
    detail: 'double pow(double x, double y)',
    documentation: 'Power function.',
    insertText: 'std::pow(${1:x}, ${2:y})',
    insertTextFormat: 2,
  },
  {
    label: 'std::sqrt',
    kind: MonacoKind.Function,
    detail: 'double sqrt(double x)',
    documentation: 'Square root.',
    insertText: 'std::sqrt(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::sin',
    kind: MonacoKind.Function,
    detail: 'double sin(double x)',
    documentation: 'Sine function.',
    insertText: 'std::sin(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::cos',
    kind: MonacoKind.Function,
    detail: 'double cos(double x)',
    documentation: 'Cosine function.',
    insertText: 'std::cos(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::tan',
    kind: MonacoKind.Function,
    detail: 'double tan(double x)',
    documentation: 'Tangent function.',
    insertText: 'std::tan(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::asin',
    kind: MonacoKind.Function,
    detail: 'double asin(double x)',
    documentation: 'Arc sine function.',
    insertText: 'std::asin(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::acos',
    kind: MonacoKind.Function,
    detail: 'double acos(double x)',
    documentation: 'Arc cosine function.',
    insertText: 'std::acos(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::atan',
    kind: MonacoKind.Function,
    detail: 'double atan(double x)',
    documentation: 'Arc tangent function.',
    insertText: 'std::atan(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::atan2',
    kind: MonacoKind.Function,
    detail: 'double atan2(double y, double x)',
    documentation: 'Two-argument arc tangent.',
    insertText: 'std::atan2(${1:y}, ${2:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::sinh',
    kind: MonacoKind.Function,
    detail: 'double sinh(double x)',
    documentation: 'Hyperbolic sine.',
    insertText: 'std::sinh(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::cosh',
    kind: MonacoKind.Function,
    detail: 'double cosh(double x)',
    documentation: 'Hyperbolic cosine.',
    insertText: 'std::cosh(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::tanh',
    kind: MonacoKind.Function,
    detail: 'double tanh(double x)',
    documentation: 'Hyperbolic tangent.',
    insertText: 'std::tanh(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::exp',
    kind: MonacoKind.Function,
    detail: 'double exp(double x)',
    documentation: 'Exponential function e^x.',
    insertText: 'std::exp(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::log',
    kind: MonacoKind.Function,
    detail: 'double log(double x)',
    documentation: 'Natural logarithm.',
    insertText: 'std::log(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::log10',
    kind: MonacoKind.Function,
    detail: 'double log10(double x)',
    documentation: 'Base-10 logarithm.',
    insertText: 'std::log10(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::ceil',
    kind: MonacoKind.Function,
    detail: 'double ceil(double x)',
    documentation: 'Ceiling function.',
    insertText: 'std::ceil(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::floor',
    kind: MonacoKind.Function,
    detail: 'double floor(double x)',
    documentation: 'Floor function.',
    insertText: 'std::floor(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::fabs',
    kind: MonacoKind.Function,
    detail: 'double fabs(double x)',
    documentation: 'Floating-point absolute value.',
    insertText: 'std::fabs(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::fmod',
    kind: MonacoKind.Function,
    detail: 'double fmod(double x, double y)',
    documentation: 'Floating-point remainder.',
    insertText: 'std::fmod(${1:x}, ${2:y})',
    insertTextFormat: 2,
  },
  {
    label: 'std::round',
    kind: MonacoKind.Function,
    detail: 'double round(double x)',
    documentation: 'Round to nearest integer.',
    insertText: 'std::round(${1:x})',
    insertTextFormat: 2,
  },
  {
    label: 'std::trunc',
    kind: MonacoKind.Function,
    detail: 'double trunc(double x)',
    documentation: 'Truncate decimal part.',
    insertText: 'std::trunc(${1:x})',
    insertTextFormat: 2,
  },

  // ─── exception ────────────────────────────────────────────────
  {
    label: 'std::exception',
    kind: MonacoKind.Class,
    detail: 'std::exception',
    documentation: 'Base exception class.',
    insertText: 'std::exception',
  },
  {
    label: 'std::runtime_error',
    kind: MonacoKind.Class,
    detail: 'std::runtime_error',
    documentation: 'Runtime error exception.',
    insertText: 'throw std::runtime_error("${1:message}");',
    insertTextFormat: 2,
  },
  {
    label: 'std::logic_error',
    kind: MonacoKind.Class,
    detail: 'std::logic_error',
    documentation: 'Logic error exception.',
    insertText: 'throw std::logic_error("${1:message}");',
    insertTextFormat: 2,
  },
  {
    label: 'std::invalid_argument',
    kind: MonacoKind.Class,
    detail: 'std::invalid_argument',
    documentation: 'Invalid argument exception.',
    insertText: 'throw std::invalid_argument("${1:message}");',
    insertTextFormat: 2,
  },
  {
    label: 'std::out_of_range',
    kind: MonacoKind.Class,
    detail: 'std::out_of_range',
    documentation: 'Out of range exception.',
    insertText: 'throw std::out_of_range("${1:message}");',
    insertTextFormat: 2,
  },
  {
    label: 'std::length_error',
    kind: MonacoKind.Class,
    detail: 'std::length_error',
    documentation: 'Length error exception.',
    insertText: 'throw std::length_error("${1:message}");',
    insertTextFormat: 2,
  },
  {
    label: 'e.what',
    kind: MonacoKind.Method,
    detail: 'const char* what()',
    documentation: 'Returns exception message.',
    insertText: 'e.what()',
  },

  // ─── IO formatting ────────────────────────────────────────────
  {
    label: 'std::fixed',
    kind: MonacoKind.Constant,
    detail: 'std::fixed',
    documentation: 'Fixed-point notation.',
    insertText: 'std::fixed',
  },
  {
    label: 'std::setprecision',
    kind: MonacoKind.Constant,
    detail: 'std::setprecision(n)',
    documentation: 'Decimal precision.',
    insertText: 'std::setprecision(${1:2})',
    insertTextFormat: 2,
  },
  {
    label: 'std::setw',
    kind: MonacoKind.Constant,
    detail: 'std::setw(n)',
    documentation: 'Field width.',
    insertText: 'std::setw(${1:10})',
    insertTextFormat: 2,
  },
  {
    label: 'std::left',
    kind: MonacoKind.Constant,
    detail: 'std::left',
    documentation: 'Left alignment.',
    insertText: 'std::left',
  },
  {
    label: 'std::right',
    kind: MonacoKind.Constant,
    detail: 'std::right',
    documentation: 'Right alignment.',
    insertText: 'std::right',
  },
  {
    label: 'std::setfill',
    kind: MonacoKind.Constant,
    detail: 'std::setfill(c)',
    documentation: 'Fill character.',
    insertText: "std::setfill('${1:0}')",
    insertTextFormat: 2,
  },

  // ─── STL container traits ─────────────────────────────────────
  {
    label: 'std::begin',
    kind: MonacoKind.Function,
    detail: 'Iterator begin',
    documentation: 'Returns iterator to container.',
    insertText: 'std::begin(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'std::end',
    kind: MonacoKind.Function,
    detail: 'Iterator end',
    documentation: 'Returns iterator to end.',
    insertText: 'std::end(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'std::size',
    kind: MonacoKind.Function,
    detail: 'size_t size()',
    documentation: 'Returns container size.',
    insertText: 'std::size(${1:c})',
    insertTextFormat: 2,
  },
  {
    label: 'std::empty',
    kind: MonacoKind.Function,
    detail: 'bool empty()',
    documentation: 'Checks if container is empty.',
    insertText: 'std::empty(${1:c})',
    insertTextFormat: 2,
  },

  // ─── Control flow / snippets ───────────────────────────────────
  {
    label: 'if',
    kind: MonacoKind.Snippet,
    detail: 'if statement',
    documentation: 'If statement.',
    insertText: 'if (${1:condition}) {\n\t${2:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'if-else',
    kind: MonacoKind.Snippet,
    detail: 'if-else statement',
    documentation: 'If-else statement.',
    insertText: 'if (${1:condition}) {\n\t${2:// code}\n} else {\n\t${3:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'for',
    kind: MonacoKind.Snippet,
    detail: 'for loop',
    documentation: 'For loop.',
    insertText: 'for (${1:int} ${2:i} = 0; ${2:i} < ${3:n}; ${2:i}++) {\n\t${4:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'for-each',
    kind: MonacoKind.Snippet,
    detail: 'range-based for loop',
    documentation: 'Range-based for loop.',
    insertText: 'for (const auto& ${1:item} : ${2:container}) {\n\t${3:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'while',
    kind: MonacoKind.Snippet,
    detail: 'while loop',
    documentation: 'While loop.',
    insertText: 'while (${1:condition}) {\n\t${2:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'do-while',
    kind: MonacoKind.Snippet,
    detail: 'do-while loop',
    documentation: 'Do-while loop.',
    insertText: 'do {\n\t${1:// code}\n} while (${2:condition});',
    insertTextFormat: 2,
  },
  {
    label: 'switch',
    kind: MonacoKind.Snippet,
    detail: 'switch statement',
    documentation: 'Switch statement.',
    insertText: 'switch (${1:expr}) {\n\tcase ${2:val1}:\n\t\t${3:// code}\n\t\tbreak;\n\tcase ${4:val2}:\n\t\t${5:// code}\n\t\tbreak;\n\tdefault:\n\t\t${6:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'try-catch',
    kind: MonacoKind.Snippet,
    detail: 'try-catch block',
    documentation: 'Try-catch block.',
    insertText: 'try {\n\t${1:// code}\n} catch (${2:const std::exception&} ${3:e}) {\n\t${4:// handle exception}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'try-catch-any',
    kind: MonacoKind.Snippet,
    detail: 'try-catch-all block',
    documentation: 'Try-catch-all block.',
    insertText: 'try {\n\t${1:// code}\n} catch (...) {\n\t${2:// handle any exception}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'lambda',
    kind: MonacoKind.Snippet,
    detail: 'lambda expression',
    documentation: 'Lambda expression.',
    insertText: '[${1:captures}](${2:params}) -> ${3:ret_type} {\n\t${4:// body}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'class',
    kind: MonacoKind.Snippet,
    detail: 'class definition',
    documentation: 'Class definition.',
    insertText: 'class ${1:ClassName} {\npublic:\n\t${1:ClassName}();\n\t~${1:ClassName}();\nprivate:\n\t${2:// members}\n};',
    insertTextFormat: 2,
  },
  {
    label: 'public:',
    kind: MonacoKind.Keyword,
    detail: 'access specifier',
    documentation: 'Public access specifier.',
    insertText: 'public:',
  },
  {
    label: 'private:',
    kind: MonacoKind.Keyword,
    detail: 'access specifier',
    documentation: 'Private access specifier.',
    insertText: 'private:',
  },
  {
    label: 'protected:',
    kind: MonacoKind.Keyword,
    detail: 'access specifier',
    documentation: 'Protected access specifier.',
    insertText: 'protected:',
  },
  {
    label: 'struct',
    kind: MonacoKind.Snippet,
    detail: 'struct definition',
    documentation: 'Struct definition.',
    insertText: 'struct ${1:StructName} {\n\t${2:// members}\n};',
    insertTextFormat: 2,
  },
  {
    label: 'namespace',
    kind: MonacoKind.Snippet,
    detail: 'namespace definition',
    documentation: 'Namespace definition.',
    insertText: 'namespace ${1:name} {\n\t${2:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'using',
    kind: MonacoKind.Snippet,
    detail: 'using directive',
    documentation: 'Using directive.',
    insertText: 'using namespace ${1:std};',
    insertTextFormat: 2,
  },
  {
    label: 'nullptr',
    kind: MonacoKind.Constant,
    detail: 'nullptr',
    documentation: 'Null pointer literal.',
    insertText: 'nullptr',
  },
  {
    label: 'auto',
    kind: MonacoKind.Keyword,
    detail: 'auto',
    documentation: 'Automatic type deduction.',
    insertText: 'auto ${1:var} = ${2:value};',
    insertTextFormat: 2,
  },
  {
    label: 'decltype',
    kind: MonacoKind.Keyword,
    detail: 'decltype',
    documentation: 'Type deduction from expression.',
    insertText: 'decltype(${1:expr})',
    insertTextFormat: 2,
  },
  {
    label: 'constexpr',
    kind: MonacoKind.Keyword,
    detail: 'constexpr',
    documentation: 'Compile-time constant.',
    insertText: 'constexpr ${1:int} ${2:var} = ${3:value};',
    insertTextFormat: 2,
  },
  {
    label: 'static_cast',
    kind: MonacoKind.Function,
    detail: 'static_cast<T>(expr)',
    documentation: 'Compile-time cast.',
    insertText: 'static_cast<${1:T}>(${2:expr})',
    insertTextFormat: 2,
  },
  {
    label: 'dynamic_cast',
    kind: MonacoKind.Function,
    detail: 'dynamic_cast<T*>(ptr)',
    documentation: 'Runtime cast.',
    insertText: 'dynamic_cast<${1:T*}>(${2:ptr})',
    insertTextFormat: 2,
  },
  {
    label: 'reinterpret_cast',
    kind: MonacoKind.Function,
    detail: 'reinterpret_cast<T>(expr)',
    documentation: 'Bitwise cast.',
    insertText: 'reinterpret_cast<${1:T}>(${2:expr})',
    insertTextFormat: 2,
  },
  {
    label: 'const_cast',
    kind: MonacoKind.Function,
    detail: 'const_cast<T>(expr)',
    documentation: 'Remove const cast.',
    insertText: 'const_cast<${1:T}>(${2:expr})',
    insertTextFormat: 2,
  },
  {
    label: 'sizeof',
    kind: MonacoKind.Function,
    detail: 'sizeof',
    documentation: 'Size of type/variable.',
    insertText: 'sizeof(${1:type})',
    insertTextFormat: 2,
  },
  {
    label: 'typeid',
    kind: MonacoKind.Function,
    detail: 'typeid',
    documentation: 'Type information.',
    insertText: 'typeid(${1:T}).name()',
    insertTextFormat: 2,
  },
  {
    label: 'noexcept',
    kind: MonacoKind.Keyword,
    detail: 'noexcept',
    documentation: 'No exception specification.',
    insertText: 'noexcept(${1:expr})',
    insertTextFormat: 2,
  },
  {
    label: 'override',
    kind: MonacoKind.Keyword,
    detail: 'override',
    documentation: 'Override virtual method.',
    insertText: 'override',
  },
  {
    label: 'final',
    kind: MonacoKind.Keyword,
    detail: 'final',
    documentation: 'Cannot override or inherit.',
    insertText: 'final',
  },
  {
    label: 'virtual',
    kind: MonacoKind.Snippet,
    detail: 'virtual',
    documentation: 'Virtual method.',
    insertText: 'virtual ${1:void} ${2:method}() {\n\t${3:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'abstract class',
    kind: MonacoKind.Snippet,
    detail: 'abstract class',
    documentation: 'Abstract class.',
    insertText: 'class ${1:ClassName} {\npublic:\n\tvirtual ~${1:ClassName}() = default;\n\tvirtual ${2:void} ${3:method}() = 0;\n};',
    insertTextFormat: 2,
  },
  {
    label: 'template',
    kind: MonacoKind.Snippet,
    detail: 'template function/class',
    documentation: 'Template function/class.',
    insertText: 'template<typename ${1:T}>\n${2:void} ${3:function}(${4:T} ${5:param}) {\n\t${6:// code}\n}',
    insertTextFormat: 2,
  },
];
