'use client';

import { LspCompletionItem, MonacoKind } from './types';

/**
 * C# Standard Library Completions
 * System namespace: Console, String, Math, Array, List, Dictionary, HashSet, Queue, Stack,
 * DateTime, TimeSpan, Random, File, Stream, Encoding, Convert
 */

export const CSHARP_API_COMPLETIONS: LspCompletionItem[] = [
  // ─────────────────────────────────────────────────────────────────
  // Console
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'Console.WriteLine',
    kind: MonacoKind.Method,
    detail: 'void WriteLine()',
    documentation: 'Writes a line to console.',
    insertText: 'Console.WriteLine("${1:value}");',
    insertTextFormat: 2,
  },
  {
    label: 'Console.Write',
    kind: MonacoKind.Method,
    detail: 'void Write()',
    documentation: 'Writes to console.',
    insertText: 'Console.Write("${1:value}");',
    insertTextFormat: 2,
  },
  {
    label: 'Console.ReadLine',
    kind: MonacoKind.Method,
    detail: 'string? ReadLine()',
    documentation: 'Reads a line from console.',
    insertText: 'Console.ReadLine()',
  },
  {
    label: 'Console.Read',
    kind: MonacoKind.Method,
    detail: 'int Read()',
    documentation: 'Reads next character.',
    insertText: 'Console.Read()',
  },
  {
    label: 'Console.ReadKey',
    kind: MonacoKind.Method,
    detail: 'ConsoleKeyInfo ReadKey()',
    documentation: 'Reads a key press.',
    insertText: 'Console.ReadKey()',
  },
  {
    label: 'Console.Clear',
    kind: MonacoKind.Method,
    detail: 'void Clear()',
    documentation: 'Clears the console.',
    insertText: 'Console.Clear();',
    insertTextFormat: 2,
  },
  {
    label: 'Console.BackgroundColor',
    kind: MonacoKind.Property,
    detail: 'ConsoleColor',
    documentation: 'Console background color.',
    insertText: 'Console.BackgroundColor',
  },
  {
    label: 'Console.ForegroundColor',
    kind: MonacoKind.Property,
    detail: 'ConsoleColor',
    documentation: 'Console foreground color.',
    insertText: 'Console.ForegroundColor',
  },
  {
    label: 'Console.ResetColor',
    kind: MonacoKind.Method,
    detail: 'void ResetColor()',
    documentation: 'Resets console colors.',
    insertText: 'Console.ResetColor();',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // String
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'string',
    kind: MonacoKind.Class,
    detail: 'System.String',
    documentation: 'String class.',
    insertText: 'string ${1:s};',
    insertTextFormat: 2,
  },
  {
    label: 's.Length',
    kind: MonacoKind.Property,
    detail: 'int Length',
    documentation: 'Returns string length.',
    insertText: 's.Length',
  },
  {
    label: 's.Substring',
    kind: MonacoKind.Method,
    detail: 'string Substring(int startIndex, int length)',
    documentation: 'Returns substring.',
    insertText: 's.Substring(${1:start}, ${2:length})',
    insertTextFormat: 2,
  },
  {
    label: 's.IndexOf',
    kind: MonacoKind.Method,
    detail: 'int IndexOf(string value)',
    documentation: 'Finds first occurrence.',
    insertText: 's.IndexOf("${1:str}")',
    insertTextFormat: 2,
  },
  {
    label: 's.LastIndexOf',
    kind: MonacoKind.Method,
    detail: 'int LastIndexOf(string value)',
    documentation: 'Finds last occurrence.',
    insertText: 's.LastIndexOf("${1:str}")',
    insertTextFormat: 2,
  },
  {
    label: 's.Contains',
    kind: MonacoKind.Method,
    detail: 'bool Contains(string value)',
    documentation: 'Checks if string contains value.',
    insertText: 's.Contains("${1:str}")',
    insertTextFormat: 2,
  },
  {
    label: 's.Replace',
    kind: MonacoKind.Method,
    detail: 'string Replace(string oldValue, string newValue)',
    documentation: 'Replaces all occurrences.',
    insertText: 's.Replace("${1:old}", "${2:new}")',
    insertTextFormat: 2,
  },
  {
    label: 's.Split',
    kind: MonacoKind.Method,
    detail: 'string[] Split(params char[] separator)',
    documentation: 'Splits string.',
    insertText: "s.Split(${1:' '})",
    insertTextFormat: 2,
  },
  {
    label: 's.Trim',
    kind: MonacoKind.Method,
    detail: 'string Trim()',
    documentation: 'Removes whitespace.',
    insertText: 's.Trim()',
  },
  {
    label: 's.TrimStart',
    kind: MonacoKind.Method,
    detail: 'string TrimStart()',
    documentation: 'Removes leading whitespace.',
    insertText: 's.TrimStart()',
  },
  {
    label: 's.TrimEnd',
    kind: MonacoKind.Method,
    detail: 'string TrimEnd()',
    documentation: 'Removes trailing whitespace.',
    insertText: 's.TrimEnd()',
  },
  {
    label: 's.ToLower',
    kind: MonacoKind.Method,
    detail: 'string ToLower()',
    documentation: 'Converts to lowercase.',
    insertText: 's.ToLower()',
  },
  {
    label: 's.ToUpper',
    kind: MonacoKind.Method,
    detail: 'string ToUpper()',
    documentation: 'Converts to uppercase.',
    insertText: 's.ToUpper()',
  },
  {
    label: 's.StartsWith',
    kind: MonacoKind.Method,
    detail: 'bool StartsWith(string value)',
    documentation: 'Checks if string starts with value.',
    insertText: 's.StartsWith("${1:str}")',
    insertTextFormat: 2,
  },
  {
    label: 's.EndsWith',
    kind: MonacoKind.Method,
    detail: 'bool EndsWith(string value)',
    documentation: 'Checks if string ends with value.',
    insertText: 's.EndsWith("${1:str}")',
    insertTextFormat: 2,
  },
  {
    label: 's.PadLeft',
    kind: MonacoKind.Method,
    detail: 'string PadLeft(int totalWidth)',
    documentation: 'Pads left.',
    insertText: 's.PadLeft(${1:totalWidth})',
    insertTextFormat: 2,
  },
  {
    label: 's.PadRight',
    kind: MonacoKind.Method,
    detail: 'string PadRight(int totalWidth)',
    documentation: 'Pads right.',
    insertText: 's.PadRight(${1:totalWidth})',
    insertTextFormat: 2,
  },
  {
    label: 'string.IsNullOrEmpty',
    kind: MonacoKind.Method,
    detail: 'static bool IsNullOrEmpty(string? value)',
    documentation: 'Checks if null or empty.',
    insertText: 'string.IsNullOrEmpty(${1:s})',
    insertTextFormat: 2,
  },
  {
    label: 'string.IsNullOrWhiteSpace',
    kind: MonacoKind.Method,
    detail: 'static bool IsNullOrWhiteSpace(string? value)',
    documentation: 'Checks if null, empty, or whitespace.',
    insertText: 'string.IsNullOrWhiteSpace(${1:s})',
    insertTextFormat: 2,
  },
  {
    label: 'string.Concat',
    kind: MonacoKind.Method,
    detail: 'static string Concat(params string[] values)',
    documentation: 'Concatenates strings.',
    insertText: 'string.Concat(${1:str1}, ${2:str2})',
    insertTextFormat: 2,
  },
  {
    label: 'string.Join',
    kind: MonacoKind.Method,
    detail: 'static string Join(string separator, params string[] values)',
    documentation: 'Joins strings with separator.',
    insertText: 'string.Join("${1:separator}", ${2:strs})',
    insertTextFormat: 2,
  },
  {
    label: 'string.Format',
    kind: MonacoKind.Method,
    detail: 'static string Format(string format, params object[] args)',
    documentation: 'Formats string.',
    insertText: 'string.Format("${1:format}", ${2:args})',
    insertTextFormat: 2,
  },
  {
    label: 'string.Intern',
    kind: MonacoKind.Method,
    detail: 'static string Intern(string str)',
    documentation: 'Interns a string.',
    insertText: 'string.Intern(${1:str})',
    insertTextFormat: 2,
  },
  {
    label: 'string.Interpolate',
    kind: MonacoKind.Snippet,
    detail: 'string interpolation',
    documentation: 'String interpolation.',
    insertText: '$"${1:{variable}}"',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // Math
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'Math.Abs',
    kind: MonacoKind.Method,
    detail: 'static T Abs(T value)',
    documentation: 'Absolute value.',
    insertText: 'Math.Abs(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Max',
    kind: MonacoKind.Method,
    detail: 'static T Max(T val1, T val2)',
    documentation: 'Maximum of two values.',
    insertText: 'Math.Max(${1:val1}, ${2:val2})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Min',
    kind: MonacoKind.Method,
    detail: 'static T Min(T val1, T val2)',
    documentation: 'Minimum of two values.',
    insertText: 'Math.Min(${1:val1}, ${2:val2})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Pow',
    kind: MonacoKind.Method,
    detail: 'static double Pow(double x, double y)',
    documentation: 'Power.',
    insertText: 'Math.Pow(${1:x}, ${2:y})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Sqrt',
    kind: MonacoKind.Method,
    detail: 'static double Sqrt(double d)',
    documentation: 'Square root.',
    insertText: 'Math.Sqrt(${1:d})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Floor',
    kind: MonacoKind.Method,
    detail: 'static double Floor(double d)',
    documentation: 'Rounds down.',
    insertText: 'Math.Floor(${1:d})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Ceiling',
    kind: MonacoKind.Method,
    detail: 'static double Ceiling(double d)',
    documentation: 'Rounds up.',
    insertText: 'Math.Ceiling(${1:d})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Round',
    kind: MonacoKind.Method,
    detail: 'static double Round(double d)',
    documentation: 'Rounds to nearest.',
    insertText: 'Math.Round(${1:d})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Truncate',
    kind: MonacoKind.Method,
    detail: 'static double Truncate(double d)',
    documentation: 'Truncates decimal part.',
    insertText: 'Math.Truncate(${1:d})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.PI',
    kind: MonacoKind.Constant,
    detail: 'static readonly double PI',
    documentation: 'Value of pi.',
    insertText: 'Math.PI',
  },
  {
    label: 'Math.E',
    kind: MonacoKind.Constant,
    detail: 'static readonly double E',
    documentation: 'Value of e.',
    insertText: 'Math.E',
  },
  {
    label: 'Math.Sin',
    kind: MonacoKind.Method,
    detail: 'static double Sin(double a)',
    documentation: 'Sine.',
    insertText: 'Math.Sin(${1:a})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Cos',
    kind: MonacoKind.Method,
    detail: 'static double Cos(double a)',
    documentation: 'Cosine.',
    insertText: 'Math.Cos(${1:a})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Tan',
    kind: MonacoKind.Method,
    detail: 'static double Tan(double a)',
    documentation: 'Tangent.',
    insertText: 'Math.Tan(${1:a})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Asin',
    kind: MonacoKind.Method,
    detail: 'static double Asin(double d)',
    documentation: 'Arc sine.',
    insertText: 'Math.Asin(${1:d})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Acos',
    kind: MonacoKind.Method,
    detail: 'static double Acos(double d)',
    documentation: 'Arc cosine.',
    insertText: 'Math.Acos(${1:d})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Atan',
    kind: MonacoKind.Method,
    detail: 'static double Atan(double d)',
    documentation: 'Arc tangent.',
    insertText: 'Math.Atan(${1:d})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Atan2',
    kind: MonacoKind.Method,
    detail: 'static double Atan2(double y, double x)',
    documentation: 'Arc tangent of y/x.',
    insertText: 'Math.Atan2(${1:y}, ${2:x})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Log',
    kind: MonacoKind.Method,
    detail: 'static double Log(double d)',
    documentation: 'Natural logarithm.',
    insertText: 'Math.Log(${1:d})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Log10',
    kind: MonacoKind.Method,
    detail: 'static double Log10(double d)',
    documentation: 'Base 10 logarithm.',
    insertText: 'Math.Log10(${1:d})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Exp',
    kind: MonacoKind.Method,
    detail: 'static double Exp(double d)',
    documentation: 'e raised to power.',
    insertText: 'Math.Exp(${1:d})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Sinh',
    kind: MonacoKind.Method,
    detail: 'static double Sinh(double value)',
    documentation: 'Hyperbolic sine.',
    insertText: 'Math.Sinh(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Cosh',
    kind: MonacoKind.Method,
    detail: 'static double Cosh(double value)',
    documentation: 'Hyperbolic cosine.',
    insertText: 'Math.Cosh(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'Math.Tanh',
    kind: MonacoKind.Method,
    detail: 'static double Tanh(double value)',
    documentation: 'Hyperbolic tangent.',
    insertText: 'Math.Tanh(${1:value})',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // List<T>
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'List<T>',
    kind: MonacoKind.Class,
    detail: 'List<T>',
    documentation: 'Generic list.',
    insertText: 'var ${1:list} = new List<${2:int}>();',
    insertTextFormat: 2,
  },
  {
    label: 'list.Add',
    kind: MonacoKind.Method,
    detail: 'void Add(T item)',
    documentation: 'Adds item to list.',
    insertText: 'list.Add(${1:item});',
    insertTextFormat: 2,
  },
  {
    label: 'list.AddRange',
    kind: MonacoKind.Method,
    detail: 'void AddRange(IEnumerable<T> collection)',
    documentation: 'Adds range to list.',
    insertText: 'list.AddRange(${1:collection});',
    insertTextFormat: 2,
  },
  {
    label: 'list.Insert',
    kind: MonacoKind.Method,
    detail: 'void Insert(int index, T item)',
    documentation: 'Inserts item at index.',
    insertText: 'list.Insert(${1:index}, ${2:item});',
    insertTextFormat: 2,
  },
  {
    label: 'list.InsertRange',
    kind: MonacoKind.Method,
    detail: 'void InsertRange(int index, IEnumerable<T> collection)',
    documentation: 'Inserts range at index.',
    insertText: 'list.InsertRange(${1:index}, ${2:collection});',
    insertTextFormat: 2,
  },
  {
    label: 'list.Remove',
    kind: MonacoKind.Method,
    detail: 'bool Remove(T item)',
    documentation: 'Removes first occurrence.',
    insertText: 'list.Remove(${1:item});',
    insertTextFormat: 2,
  },
  {
    label: 'list.RemoveAt',
    kind: MonacoKind.Method,
    detail: 'void RemoveAt(int index)',
    documentation: 'Removes at index.',
    insertText: 'list.RemoveAt(${1:index});',
    insertTextFormat: 2,
  },
  {
    label: 'list.RemoveRange',
    kind: MonacoKind.Method,
    detail: 'void RemoveRange(int index, int count)',
    documentation: 'Removes range.',
    insertText: 'list.RemoveRange(${1:index}, ${2:count});',
    insertTextFormat: 2,
  },
  {
    label: 'list.RemoveAll',
    kind: MonacoKind.Method,
    detail: 'int RemoveAll(Predicate<T> match)',
    documentation: 'Removes all matching.',
    insertText: 'list.RemoveAll(${1:x => condition});',
    insertTextFormat: 2,
  },
  {
    label: 'list.Clear',
    kind: MonacoKind.Method,
    detail: 'void Clear()',
    documentation: 'Clears the list.',
    insertText: 'list.Clear();',
    insertTextFormat: 2,
  },
  {
    label: 'list.Count',
    kind: MonacoKind.Property,
    detail: 'int Count',
    documentation: 'Number of elements.',
    insertText: 'list.Count',
  },
  {
    label: 'list.Capacity',
    kind: MonacoKind.Property,
    detail: 'int Capacity',
    documentation: 'Internal buffer size.',
    insertText: 'list.Capacity',
  },
  {
    label: 'list.Contains',
    kind: MonacoKind.Method,
    detail: 'bool Contains(T item)',
    documentation: 'Checks if contains item.',
    insertText: 'list.Contains(${1:item})',
    insertTextFormat: 2,
  },
  {
    label: 'list.IndexOf',
    kind: MonacoKind.Method,
    detail: 'int IndexOf(T item)',
    documentation: 'Returns first index.',
    insertText: 'list.IndexOf(${1:item})',
    insertTextFormat: 2,
  },
  {
    label: 'list.LastIndexOf',
    kind: MonacoKind.Method,
    detail: 'int LastIndexOf(T item)',
    documentation: 'Returns last index.',
    insertText: 'list.LastIndexOf(${1:item})',
    insertTextFormat: 2,
  },
  {
    label: 'list.Sort',
    kind: MonacoKind.Method,
    detail: 'void Sort()',
    documentation: 'Sorts the list.',
    insertText: 'list.Sort();',
    insertTextFormat: 2,
  },
  {
    label: 'list.Reverse',
    kind: MonacoKind.Method,
    detail: 'void Reverse()',
    documentation: 'Reverses the list.',
    insertText: 'list.Reverse();',
    insertTextFormat: 2,
  },
  {
    label: 'list.ForEach',
    kind: MonacoKind.Method,
    detail: 'void ForEach(Action<T> action)',
    documentation: 'Iterates over elements.',
    insertText: 'list.ForEach(${1:item => Console.WriteLine(item)});',
    insertTextFormat: 2,
  },
  {
    label: 'list.Find',
    kind: MonacoKind.Method,
    detail: 'T? Find(Predicate<T> match)',
    documentation: 'Finds first match.',
    insertText: 'list.Find(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: 'list.FindAll',
    kind: MonacoKind.Method,
    detail: 'List<T> FindAll(Predicate<T> match)',
    documentation: 'Finds all matches.',
    insertText: 'list.FindAll(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: 'list.FindIndex',
    kind: MonacoKind.Method,
    detail: 'int FindIndex(Predicate<T> match)',
    documentation: 'Finds index of first match.',
    insertText: 'list.FindIndex(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: 'list.FindLast',
    kind: MonacoKind.Method,
    detail: 'T? FindLast(Predicate<T> match)',
    documentation: 'Finds last match.',
    insertText: 'list.FindLast(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: 'list.FindLastIndex',
    kind: MonacoKind.Method,
    detail: 'int FindLastIndex(Predicate<T> match)',
    documentation: 'Finds index of last match.',
    insertText: 'list.FindLastIndex(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: 'list.Exists',
    kind: MonacoKind.Method,
    detail: 'bool Exists(Predicate<T> match)',
    documentation: 'Checks if match exists.',
    insertText: 'list.Exists(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: 'list.TrueForAll',
    kind: MonacoKind.Method,
    detail: 'bool TrueForAll(Predicate<T> match)',
    documentation: 'Checks if all match.',
    insertText: 'list.TrueForAll(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: 'list.ToArray',
    kind: MonacoKind.Method,
    detail: 'T[] ToArray()',
    documentation: 'Converts to array.',
    insertText: 'list.ToArray()',
  },
  {
    label: 'list.AsReadOnly',
    kind: MonacoKind.Method,
    detail: 'ReadOnlyCollection<T> AsReadOnly()',
    documentation: 'Returns read-only wrapper.',
    insertText: 'list.AsReadOnly()',
  },

  // ─────────────────────────────────────────────────────────────────
  // Array
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'T[] array',
    kind: MonacoKind.Snippet,
    detail: 'T[] array',
    documentation: 'Array declaration.',
    insertText: 'var ${1:arr} = new ${2:int}[${3:size}];',
    insertTextFormat: 2,
  },
  {
    label: 'arr.Length',
    kind: MonacoKind.Property,
    detail: 'int Length',
    documentation: 'Number of elements.',
    insertText: 'arr.Length',
  },
  {
    label: 'arr.LongLength',
    kind: MonacoKind.Property,
    detail: 'long LongLength',
    documentation: '64-bit length.',
    insertText: 'arr.LongLength',
  },
  {
    label: 'arr.Rank',
    kind: MonacoKind.Property,
    detail: 'int Rank',
    documentation: 'Number of dimensions.',
    insertText: 'arr.Rank',
  },
  {
    label: 'arr.GetLength',
    kind: MonacoKind.Method,
    detail: 'int GetLength(int dimension)',
    documentation: 'Gets length of dimension.',
    insertText: 'arr.GetLength(${1:0})',
    insertTextFormat: 2,
  },
  {
    label: 'arr.GetLongLength',
    kind: MonacoKind.Method,
    detail: 'long GetLongLength(int dimension)',
    documentation: 'Gets long length of dimension.',
    insertText: 'arr.GetLongLength(${1:0})',
    insertTextFormat: 2,
  },
  {
    label: 'Array.Resize',
    kind: MonacoKind.Method,
    detail: 'static void Resize<T>(ref T[] array, int newSize)',
    documentation: 'Resizes array.',
    insertText: 'Array.Resize(ref ${1:arr}, ${2:newSize});',
    insertTextFormat: 2,
  },
  {
    label: 'Array.Sort',
    kind: MonacoKind.Method,
    detail: 'static void Sort(Array array)',
    documentation: 'Sorts array.',
    insertText: 'Array.Sort(${1:arr});',
    insertTextFormat: 2,
  },
  {
    label: 'Array.Reverse',
    kind: MonacoKind.Method,
    detail: 'static void Reverse(Array array)',
    documentation: 'Reverses array.',
    insertText: 'Array.Reverse(${1:arr});',
    insertTextFormat: 2,
  },
  {
    label: 'Array.Clear',
    kind: MonacoKind.Method,
    detail: 'static void Clear(Array array, int index, int length)',
    documentation: 'Clears array elements.',
    insertText: 'Array.Clear(${1:arr}, ${2:0}, ${3:arr.Length});',
    insertTextFormat: 2,
  },
  {
    label: 'Array.Copy',
    kind: MonacoKind.Method,
    detail: 'static void Copy(Array sourceArray, Array destinationArray, int length)',
    documentation: 'Copies array.',
    insertText: 'Array.Copy(${1:source}, ${2:destination}, ${3:length});',
    insertTextFormat: 2,
  },
  {
    label: 'Array.BinarySearch',
    kind: MonacoKind.Method,
    detail: 'static int BinarySearch(Array array, object value)',
    documentation: 'Binary searches sorted array.',
    insertText: 'Array.BinarySearch(${1:arr}, ${2:value})',
    insertTextFormat: 2,
  },
  {
    label: 'Array.FindIndex',
    kind: MonacoKind.Method,
    detail: 'static int FindIndex<T>(T[] array, Predicate<T> match)',
    documentation: 'Finds index of first match.',
    insertText: 'Array.FindIndex(${1:arr}, ${2:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: 'Array.FindAll',
    kind: MonacoKind.Method,
    detail: 'static T[] FindAll<T>(T[] array, Predicate<T> match)',
    documentation: 'Finds all matches.',
    insertText: 'Array.FindAll(${1:arr}, ${2:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: 'Array.Exists',
    kind: MonacoKind.Method,
    detail: 'static bool Exists<T>(T[] array, Predicate<T> match)',
    documentation: 'Checks if match exists.',
    insertText: 'Array.Exists(${1:arr}, ${2:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: 'Array.TrueForAll',
    kind: MonacoKind.Method,
    detail: 'static bool TrueForAll<T>(T[] array, Predicate<T> match)',
    documentation: 'Checks if all match.',
    insertText: 'Array.TrueForAll(${1:arr}, ${2:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: 'Array.ForEach',
    kind: MonacoKind.Method,
    detail: 'static void ForEach<T>(T[] array, Action<T> action)',
    documentation: 'Iterates over array.',
    insertText: 'Array.ForEach(${1:arr}, ${2:item => Console.WriteLine(item)});',
    insertTextFormat: 2,
  },
  {
    label: 'Enumerable.Range',
    kind: MonacoKind.Method,
    detail: 'static IEnumerable<int> Range(int start, int count)',
    documentation: 'Generates range.',
    insertText: 'Enumerable.Range(${1:0}, ${2:10})',
    insertTextFormat: 2,
  },
  {
    label: 'Enumerable.Repeat',
    kind: MonacoKind.Method,
    detail: 'static IEnumerable<T> Repeat<T>(T element, int count)',
    documentation: 'Repeats element.',
    insertText: 'Enumerable.Repeat(${1:element}, ${2:count})',
    insertTextFormat: 2,
  },
  {
    label: 'Enumerable.Empty',
    kind: MonacoKind.Method,
    detail: 'static IEnumerable<T> Empty<T>()',
    documentation: 'Returns empty enumerable.',
    insertText: 'Enumerable.Empty<${1:T}>()',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // Dictionary<K, V>
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'Dictionary<K, V>',
    kind: MonacoKind.Class,
    detail: 'Dictionary<K, V>',
    documentation: 'Key-value dictionary.',
    insertText: 'var ${1:dict} = new Dictionary<${2:string}, ${3:int}>();',
    insertTextFormat: 2,
  },
  {
    label: 'dict[key]',
    kind: MonacoKind.Property,
    detail: 'V this[K key]',
    documentation: 'Access by key.',
    insertText: 'dict[${1:key}]',
    insertTextFormat: 2,
  },
  {
    label: 'dict.Add',
    kind: MonacoKind.Method,
    detail: 'void Add(K key, V value)',
    documentation: 'Adds key-value pair.',
    insertText: 'dict.Add(${1:key}, ${2:value});',
    insertTextFormat: 2,
  },
  {
    label: 'dict.Remove',
    kind: MonacoKind.Method,
    detail: 'bool Remove(K key)',
    documentation: 'Removes by key.',
    insertText: 'dict.Remove(${1:key});',
    insertTextFormat: 2,
  },
  {
    label: 'dict.ContainsKey',
    kind: MonacoKind.Method,
    detail: 'bool ContainsKey(K key)',
    documentation: 'Checks if key exists.',
    insertText: 'dict.ContainsKey(${1:key})',
    insertTextFormat: 2,
  },
  {
    label: 'dict.ContainsValue',
    kind: MonacoKind.Method,
    detail: 'bool ContainsValue(V value)',
    documentation: 'Checks if value exists.',
    insertText: 'dict.ContainsValue(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'dict.TryGetValue',
    kind: MonacoKind.Method,
    detail: 'bool TryGetValue(K key, out V value)',
    documentation: 'Tries to get value.',
    insertText: 'dict.TryGetValue(${1:key}, out ${2:var} ${3:value})',
    insertTextFormat: 2,
  },
  {
    label: 'dict.Keys',
    kind: MonacoKind.Property,
    detail: 'Dictionary<K, V>.KeyCollection Keys',
    documentation: 'Collection of keys.',
    insertText: 'dict.Keys',
  },
  {
    label: 'dict.Values',
    kind: MonacoKind.Property,
    detail: 'Dictionary<K, V>.ValueCollection Values',
    documentation: 'Collection of values.',
    insertText: 'dict.Values',
  },
  {
    label: 'dict.Count',
    kind: MonacoKind.Property,
    detail: 'int Count',
    documentation: 'Number of pairs.',
    insertText: 'dict.Count',
  },
  {
    label: 'dict.Clear',
    kind: MonacoKind.Method,
    detail: 'void Clear()',
    documentation: 'Clears dictionary.',
    insertText: 'dict.Clear();',
    insertTextFormat: 2,
  },
  {
    label: 'dict.ToList',
    kind: MonacoKind.Method,
    detail: 'List<KeyValuePair<K, V>> ToList()',
    documentation: 'Converts to list.',
    insertText: 'dict.ToList()',
  },
  {
    label: 'dict.OrderBy',
    kind: MonacoKind.Method,
    detail: 'IOrderedEnumerable<KeyValuePair<K, V>> OrderBy(Func<KeyValuePair<K, V>, TKey> keySelector)',
    documentation: 'Orders by key.',
    insertText: 'dict.OrderBy(${1:kvp => kvp.Key})',
    insertTextFormat: 2,
  },
  {
    label: 'dict.OrderByDescending',
    kind: MonacoKind.Method,
    detail: 'IOrderedEnumerable<KeyValuePair<K, V>> OrderByDescending(Func<KeyValuePair<K, V>, TKey> keySelector)',
    documentation: 'Orders by key descending.',
    insertText: 'dict.OrderByDescending(${1:kvp => kvp.Key})',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // HashSet<T>
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'HashSet<T>',
    kind: MonacoKind.Class,
    detail: 'HashSet<T>',
    documentation: 'Hash set.',
    insertText: 'var ${1:set} = new HashSet<${2:int}>();',
    insertTextFormat: 2,
  },
  {
    label: 'set.Add',
    kind: MonacoKind.Method,
    detail: 'bool Add(T item)',
    documentation: 'Adds item.',
    insertText: 'set.Add(${1:item});',
    insertTextFormat: 2,
  },
  {
    label: 'set.Remove',
    kind: MonacoKind.Method,
    detail: 'bool Remove(T item)',
    documentation: 'Removes item.',
    insertText: 'set.Remove(${1:item});',
    insertTextFormat: 2,
  },
  {
    label: 'set.Contains',
    kind: MonacoKind.Method,
    detail: 'bool Contains(T item)',
    documentation: 'Checks if contains item.',
    insertText: 'set.Contains(${1:item})',
    insertTextFormat: 2,
  },
  {
    label: 'set.Count',
    kind: MonacoKind.Property,
    detail: 'int Count',
    documentation: 'Number of elements.',
    insertText: 'set.Count',
  },
  {
    label: 'set.Clear',
    kind: MonacoKind.Method,
    detail: 'void Clear()',
    documentation: 'Clears the set.',
    insertText: 'set.Clear();',
    insertTextFormat: 2,
  },
  {
    label: 'set.IsSubsetOf',
    kind: MonacoKind.Method,
    detail: 'bool IsSubsetOf(IEnumerable<T> other)',
    documentation: 'Checks if subset.',
    insertText: 'set.IsSubsetOf(${1:other})',
    insertTextFormat: 2,
  },
  {
    label: 'set.IsSupersetOf',
    kind: MonacoKind.Method,
    detail: 'bool IsSupersetOf(IEnumerable<T> other)',
    documentation: 'Checks if superset.',
    insertText: 'set.IsSupersetOf(${1:other})',
    insertTextFormat: 2,
  },
  {
    label: 'set.IsProperSubsetOf',
    kind: MonacoKind.Method,
    detail: 'bool IsProperSubsetOf(IEnumerable<T> other)',
    documentation: 'Checks if proper subset.',
    insertText: 'set.IsProperSubsetOf(${1:other})',
    insertTextFormat: 2,
  },
  {
    label: 'set.IsProperSupersetOf',
    kind: MonacoKind.Method,
    detail: 'bool IsProperSupersetOf(IEnumerable<T> other)',
    documentation: 'Checks if proper superset.',
    insertText: 'set.IsProperSupersetOf(${1:other})',
    insertTextFormat: 2,
  },
  {
    label: 'set.UnionWith',
    kind: MonacoKind.Method,
    detail: 'void UnionWith(IEnumerable<T> other)',
    documentation: 'Union with other set.',
    insertText: 'set.UnionWith(${1:other});',
    insertTextFormat: 2,
  },
  {
    label: 'set.IntersectWith',
    kind: MonacoKind.Method,
    detail: 'void IntersectWith(IEnumerable<T> other)',
    documentation: 'Intersect with other set.',
    insertText: 'set.IntersectWith(${1:other});',
    insertTextFormat: 2,
  },
  {
    label: 'set.ExceptWith',
    kind: MonacoKind.Method,
    detail: 'void ExceptWith(IEnumerable<T> other)',
    documentation: 'Removes other set elements.',
    insertText: 'set.ExceptWith(${1:other});',
    insertTextFormat: 2,
  },
  {
    label: 'set.SymmetricExceptWith',
    kind: MonacoKind.Method,
    detail: 'void SymmetricExceptWith(IEnumerable<T> other)',
    documentation: 'Symmetric difference.',
    insertText: 'set.SymmetricExceptWith(${1:other});',
    insertTextFormat: 2,
  },
  {
    label: 'set.TryGetValue',
    kind: MonacoKind.Method,
    detail: 'bool TryGetValue(T equalValue, out T actualValue)',
    documentation: 'Tries to get value.',
    insertText: 'set.TryGetValue(${1:value}, out ${2:var} ${3:actual})',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // Queue<T>
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'Queue<T>',
    kind: MonacoKind.Class,
    detail: 'Queue<T>',
    documentation: 'FIFO queue.',
    insertText: 'var ${1:q} = new Queue<${2:int}>();',
    insertTextFormat: 2,
  },
  {
    label: 'q.Enqueue',
    kind: MonacoKind.Method,
    detail: 'void Enqueue(T item)',
    documentation: 'Adds to queue.',
    insertText: 'q.Enqueue(${1:item});',
    insertTextFormat: 2,
  },
  {
    label: 'q.Dequeue',
    kind: MonacoKind.Method,
    detail: 'T Dequeue()',
    documentation: 'Removes from queue.',
    insertText: 'q.Dequeue()',
  },
  {
    label: 'q.Peek',
    kind: MonacoKind.Method,
    detail: 'T Peek()',
    documentation: 'Views front.',
    insertText: 'q.Peek()',
  },
  {
    label: 'q.Contains',
    kind: MonacoKind.Method,
    detail: 'bool Contains(T item)',
    documentation: 'Checks if contains.',
    insertText: 'q.Contains(${1:item})',
    insertTextFormat: 2,
  },
  {
    label: 'q.Count',
    kind: MonacoKind.Property,
    detail: 'int Count',
    documentation: 'Number of elements.',
    insertText: 'q.Count',
  },
  {
    label: 'q.Clear',
    kind: MonacoKind.Method,
    detail: 'void Clear()',
    documentation: 'Clears queue.',
    insertText: 'q.Clear();',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // Stack<T>
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'Stack<T>',
    kind: MonacoKind.Class,
    detail: 'Stack<T>',
    documentation: 'LIFO stack.',
    insertText: 'var ${1:s} = new Stack<${2:int}>();',
    insertTextFormat: 2,
  },
  {
    label: 's.Push',
    kind: MonacoKind.Method,
    detail: 'void Push(T item)',
    documentation: 'Pushes to stack.',
    insertText: 's.Push(${1:item});',
    insertTextFormat: 2,
  },
  {
    label: 's.Pop',
    kind: MonacoKind.Method,
    detail: 'T Pop()',
    documentation: 'Pops from stack.',
    insertText: 's.Pop()',
  },
  {
    label: 's.Peek',
    kind: MonacoKind.Method,
    detail: 'T Peek()',
    documentation: 'Views top.',
    insertText: 's.Peek()',
  },
  {
    label: 's.Contains',
    kind: MonacoKind.Method,
    detail: 'bool Contains(T item)',
    documentation: 'Checks if contains.',
    insertText: 's.Contains(${1:item})',
    insertTextFormat: 2,
  },
  {
    label: 's.Count',
    kind: MonacoKind.Property,
    detail: 'int Count',
    documentation: 'Number of elements.',
    insertText: 's.Count',
  },
  {
    label: 's.Clear',
    kind: MonacoKind.Method,
    detail: 'void Clear()',
    documentation: 'Clears stack.',
    insertText: 's.Clear();',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // DateTime
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'DateTime.Now',
    kind: MonacoKind.Property,
    detail: 'static DateTime Now',
    documentation: 'Current local time.',
    insertText: 'DateTime.Now',
  },
  {
    label: 'DateTime.UtcNow',
    kind: MonacoKind.Property,
    detail: 'static DateTime UtcNow',
    documentation: 'Current UTC time.',
    insertText: 'DateTime.UtcNow',
  },
  {
    label: 'DateTime.Today',
    kind: MonacoKind.Property,
    detail: 'static DateTime Today',
    documentation: 'Current date at midnight.',
    insertText: 'DateTime.Today',
  },
  {
    label: 'DateTime.Parse',
    kind: MonacoKind.Method,
    detail: 'static DateTime Parse(string s)',
    documentation: 'Parses string to DateTime.',
    insertText: 'DateTime.Parse("${1:date}")',
    insertTextFormat: 2,
  },
  {
    label: 'DateTime.TryParse',
    kind: MonacoKind.Method,
    detail: 'static bool TryParse(string s, out DateTime result)',
    documentation: 'Tries to parse string.',
    insertText: 'DateTime.TryParse("${1:date}", out ${2:result})',
    insertTextFormat: 2,
  },
  {
    label: 'DateTime.ParseExact',
    kind: MonacoKind.Method,
    detail: 'static DateTime ParseExact(string s, string format, IFormatProvider? provider)',
    documentation: 'Parses with format.',
    insertText: 'DateTime.ParseExact("${1:date}", "${2:format}", null)',
    insertTextFormat: 2,
  },
  {
    label: 'DateTime.TryParseExact',
    kind: MonacoKind.Method,
    detail: 'static bool TryParseExact(string s, string format, IFormatProvider? provider, DateTimeStyles styles, out DateTime result)',
    documentation: 'Tries to parse with format.',
    insertText: 'DateTime.TryParseExact("${1:date}", "${2:format}", null, DateTimeStyles.None, out ${3:result})',
    insertTextFormat: 2,
  },
  {
    label: 'dt.AddDays',
    kind: MonacoKind.Method,
    detail: 'DateTime AddDays(double days)',
    documentation: 'Adds days.',
    insertText: 'dt.AddDays(${1:days})',
    insertTextFormat: 2,
  },
  {
    label: 'dt.AddHours',
    kind: MonacoKind.Method,
    detail: 'DateTime AddHours(double hours)',
    documentation: 'Adds hours.',
    insertText: 'dt.AddHours(${1:hours})',
    insertTextFormat: 2,
  },
  {
    label: 'dt.AddMinutes',
    kind: MonacoKind.Method,
    detail: 'DateTime AddMinutes(double minutes)',
    documentation: 'Adds minutes.',
    insertText: 'dt.AddMinutes(${1:minutes})',
    insertTextFormat: 2,
  },
  {
    label: 'dt.AddSeconds',
    kind: MonacoKind.Method,
    detail: 'DateTime AddSeconds(double seconds)',
    documentation: 'Adds seconds.',
    insertText: 'dt.AddSeconds(${1:seconds})',
    insertTextFormat: 2,
  },
  {
    label: 'dt.AddMilliseconds',
    kind: MonacoKind.Method,
    detail: 'DateTime AddMilliseconds(double value)',
    documentation: 'Adds milliseconds.',
    insertText: 'dt.AddMilliseconds(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'dt.AddMonths',
    kind: MonacoKind.Method,
    detail: 'DateTime AddMonths(int months)',
    documentation: 'Adds months.',
    insertText: 'dt.AddMonths(${1:months})',
    insertTextFormat: 2,
  },
  {
    label: 'dt.AddYears',
    kind: MonacoKind.Method,
    detail: 'DateTime AddYears(int years)',
    documentation: 'Adds years.',
    insertText: 'dt.AddYears(${1:years})',
    insertTextFormat: 2,
  },
  {
    label: 'dt.Subtract',
    kind: MonacoKind.Method,
    detail: 'TimeSpan Subtract(DateTime value)',
    documentation: 'Subtracts date.',
    insertText: 'dt.Subtract(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'dt.ToString',
    kind: MonacoKind.Method,
    detail: 'string ToString()',
    documentation: 'Converts to string.',
    insertText: 'dt.ToString()',
  },
  {
    label: 'dt.ToShortDateString',
    kind: MonacoKind.Method,
    detail: 'string ToShortDateString()',
    documentation: 'Short date format.',
    insertText: 'dt.ToShortDateString()',
  },
  {
    label: 'dt.ToLongDateString',
    kind: MonacoKind.Method,
    detail: 'string ToLongDateString()',
    documentation: 'Long date format.',
    insertText: 'dt.ToLongDateString()',
  },
  {
    label: 'dt.ToShortTimeString',
    kind: MonacoKind.Method,
    detail: 'string ToShortTimeString()',
    documentation: 'Short time format.',
    insertText: 'dt.ToShortTimeString()',
  },
  {
    label: 'dt.ToLongTimeString',
    kind: MonacoKind.Method,
    detail: 'string ToLongTimeString()',
    documentation: 'Long time format.',
    insertText: 'dt.ToLongTimeString()',
  },
  {
    label: 'DateTime.Compare',
    kind: MonacoKind.Method,
    detail: 'static int Compare(DateTime t1, DateTime t2)',
    documentation: 'Compares two dates.',
    insertText: 'DateTime.Compare(${1:t1}, ${2:t2})',
    insertTextFormat: 2,
  },
  {
    label: 'dt.CompareTo',
    kind: MonacoKind.Method,
    detail: 'int CompareTo(DateTime value)',
    documentation: 'Compares to date.',
    insertText: 'dt.CompareTo(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'dt.Day',
    kind: MonacoKind.Property,
    detail: 'int Day',
    documentation: 'Day of month.',
    insertText: 'dt.Day',
  },
  {
    label: 'dt.Month',
    kind: MonacoKind.Property,
    detail: 'int Month',
    documentation: 'Month of year.',
    insertText: 'dt.Month',
  },
  {
    label: 'dt.Year',
    kind: MonacoKind.Property,
    detail: 'int Year',
    documentation: 'Year.',
    insertText: 'dt.Year',
  },
  {
    label: 'dt.Hour',
    kind: MonacoKind.Property,
    detail: 'int Hour',
    documentation: 'Hour.',
    insertText: 'dt.Hour',
  },
  {
    label: 'dt.Minute',
    kind: MonacoKind.Property,
    detail: 'int Minute',
    documentation: 'Minute.',
    insertText: 'dt.Minute',
  },
  {
    label: 'dt.Second',
    kind: MonacoKind.Property,
    detail: 'int Second',
    documentation: 'Second.',
    insertText: 'dt.Second',
  },
  {
    label: 'dt.Millisecond',
    kind: MonacoKind.Property,
    detail: 'int Millisecond',
    documentation: 'Millisecond.',
    insertText: 'dt.Millisecond',
  },
  {
    label: 'dt.DayOfWeek',
    kind: MonacoKind.Property,
    detail: 'DayOfWeek DayOfWeek',
    documentation: 'Day of week.',
    insertText: 'dt.DayOfWeek',
  },
  {
    label: 'dt.DayOfYear',
    kind: MonacoKind.Property,
    detail: 'int DayOfYear',
    documentation: 'Day of year.',
    insertText: 'dt.DayOfYear',
  },

  // ─────────────────────────────────────────────────────────────────
  // TimeSpan
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'TimeSpan.Zero',
    kind: MonacoKind.Constant,
    detail: 'static readonly TimeSpan Zero',
    documentation: 'Zero time span.',
    insertText: 'TimeSpan.Zero',
  },
  {
    label: 'TimeSpan.FromDays',
    kind: MonacoKind.Method,
    detail: 'static TimeSpan FromDays(double value)',
    documentation: 'Creates from days.',
    insertText: 'TimeSpan.FromDays(${1:days})',
    insertTextFormat: 2,
  },
  {
    label: 'TimeSpan.FromHours',
    kind: MonacoKind.Method,
    detail: 'static TimeSpan FromHours(double value)',
    documentation: 'Creates from hours.',
    insertText: 'TimeSpan.FromHours(${1:hours})',
    insertTextFormat: 2,
  },
  {
    label: 'TimeSpan.FromMinutes',
    kind: MonacoKind.Method,
    detail: 'static TimeSpan FromMinutes(double value)',
    documentation: 'Creates from minutes.',
    insertText: 'TimeSpan.FromMinutes(${1:minutes})',
    insertTextFormat: 2,
  },
  {
    label: 'TimeSpan.FromSeconds',
    kind: MonacoKind.Method,
    detail: 'static TimeSpan FromSeconds(double value)',
    documentation: 'Creates from seconds.',
    insertText: 'TimeSpan.FromSeconds(${1:seconds})',
    insertTextFormat: 2,
  },
  {
    label: 'TimeSpan.FromMilliseconds',
    kind: MonacoKind.Method,
    detail: 'static TimeSpan FromMilliseconds(double value)',
    documentation: 'Creates from milliseconds.',
    insertText: 'TimeSpan.FromMilliseconds(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'ts.TotalDays',
    kind: MonacoKind.Property,
    detail: 'double TotalDays',
    documentation: 'Total days.',
    insertText: 'ts.TotalDays',
  },
  {
    label: 'ts.TotalHours',
    kind: MonacoKind.Property,
    detail: 'double TotalHours',
    documentation: 'Total hours.',
    insertText: 'ts.TotalHours',
  },
  {
    label: 'ts.TotalMinutes',
    kind: MonacoKind.Property,
    detail: 'double TotalMinutes',
    documentation: 'Total minutes.',
    insertText: 'ts.TotalMinutes',
  },
  {
    label: 'ts.TotalSeconds',
    kind: MonacoKind.Property,
    detail: 'double TotalSeconds',
    documentation: 'Total seconds.',
    insertText: 'ts.TotalSeconds',
  },
  {
    label: 'ts.TotalMilliseconds',
    kind: MonacoKind.Property,
    detail: 'double TotalMilliseconds',
    documentation: 'Total milliseconds.',
    insertText: 'ts.TotalMilliseconds',
  },

  // ─────────────────────────────────────────────────────────────────
  // Random
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'Random',
    kind: MonacoKind.Class,
    detail: 'Random',
    documentation: 'Random number generator.',
    insertText: 'var ${1:rand} = new Random();',
    insertTextFormat: 2,
  },
  {
    label: 'rand.Next',
    kind: MonacoKind.Method,
    detail: 'int Next()',
    documentation: 'Next random int.',
    insertText: 'rand.Next()',
  },
  {
    label: 'rand.Next(maxValue)',
    kind: MonacoKind.Method,
    detail: 'int Next(int maxValue)',
    documentation: 'Next random int (0 to max).',
    insertText: 'rand.Next(${1:maxValue})',
    insertTextFormat: 2,
  },
  {
    label: 'rand.Next(minValue, maxValue)',
    kind: MonacoKind.Method,
    detail: 'int Next(int minValue, int maxValue)',
    documentation: 'Next random int in range.',
    insertText: 'rand.Next(${1:minValue}, ${2:maxValue})',
    insertTextFormat: 2,
  },
  {
    label: 'rand.NextDouble',
    kind: MonacoKind.Method,
    detail: 'double NextDouble()',
    documentation: 'Next random double (0 to 1).',
    insertText: 'rand.NextDouble()',
  },
  {
    label: 'rand.NextBytes',
    kind: MonacoKind.Method,
    detail: 'void NextBytes(byte[] buffer)',
    documentation: 'Fills byte array.',
    insertText: 'rand.NextBytes(${1:buffer});',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // File
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'File.ReadAllText',
    kind: MonacoKind.Method,
    detail: 'static string ReadAllText(string path)',
    documentation: 'Reads all text from file.',
    insertText: 'File.ReadAllText("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'File.WriteAllText',
    kind: MonacoKind.Method,
    detail: 'static void WriteAllText(string path, string contents)',
    documentation: 'Writes all text to file.',
    insertText: 'File.WriteAllText("${1:path}", ${2:contents});',
    insertTextFormat: 2,
  },
  {
    label: 'File.ReadAllLines',
    kind: MonacoKind.Method,
    detail: 'static string[] ReadAllLines(string path)',
    documentation: 'Reads all lines from file.',
    insertText: 'File.ReadAllLines("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'File.WriteAllLines',
    kind: MonacoKind.Method,
    detail: 'static void WriteAllLines(string path, string[] contents)',
    documentation: 'Writes all lines to file.',
    insertText: 'File.WriteAllLines("${1:path}", ${2:lines});',
    insertTextFormat: 2,
  },
  {
    label: 'File.ReadAllBytes',
    kind: MonacoKind.Method,
    detail: 'static byte[] ReadAllBytes(string path)',
    documentation: 'Reads all bytes from file.',
    insertText: 'File.ReadAllBytes("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'File.WriteAllBytes',
    kind: MonacoKind.Method,
    detail: 'static void WriteAllBytes(string path, byte[] bytes)',
    documentation: 'Writes all bytes to file.',
    insertText: 'File.WriteAllBytes("${1:path}", ${2:bytes});',
    insertTextFormat: 2,
  },
  {
    label: 'File.AppendAllText',
    kind: MonacoKind.Method,
    detail: 'static void AppendAllText(string path, string contents)',
    documentation: 'Appends text to file.',
    insertText: 'File.AppendAllText("${1:path}", ${2:contents});',
    insertTextFormat: 2,
  },
  {
    label: 'File.AppendText',
    kind: MonacoKind.Method,
    detail: 'static StreamWriter AppendText(string path)',
    documentation: 'Returns StreamWriter for appending.',
    insertText: 'File.AppendText("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'File.Exists',
    kind: MonacoKind.Method,
    detail: 'static bool Exists(string? path)',
    documentation: 'Checks if file exists.',
    insertText: 'File.Exists("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'File.Copy',
    kind: MonacoKind.Method,
    detail: 'static void Copy(string sourceFileName, string destFileName)',
    documentation: 'Copies file.',
    insertText: 'File.Copy("${1:source}", "${2:dest}");',
    insertTextFormat: 2,
  },
  {
    label: 'File.Move',
    kind: MonacoKind.Method,
    detail: 'static void Move(string sourceFileName, string destFileName)',
    documentation: 'Moves file.',
    insertText: 'File.Move("${1:source}", "${2:dest}");',
    insertTextFormat: 2,
  },
  {
    label: 'File.Delete',
    kind: MonacoKind.Method,
    detail: 'static void Delete(string? path)',
    documentation: 'Deletes file.',
    insertText: 'File.Delete("${1:path}");',
    insertTextFormat: 2,
  },
  {
    label: 'File.GetCreationTime',
    kind: MonacoKind.Method,
    detail: 'static DateTime GetCreationTime(string path)',
    documentation: 'Gets creation time.',
    insertText: 'File.GetCreationTime("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'File.GetLastWriteTime',
    kind: MonacoKind.Method,
    detail: 'static DateTime GetLastWriteTime(string path)',
    documentation: 'Gets last write time.',
    insertText: 'File.GetLastWriteTime("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'File.GetLastAccessTime',
    kind: MonacoKind.Method,
    detail: 'static DateTime GetLastAccessTime(string path)',
    documentation: 'Gets last access time.',
    insertText: 'File.GetLastAccessTime("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'File.Open',
    kind: MonacoKind.Method,
    detail: 'static FileStream Open(string path, FileMode mode)',
    documentation: 'Opens file stream.',
    insertText: 'File.Open("${1:path}", FileMode.${2:Open});',
    insertTextFormat: 2,
  },
  {
    label: 'File.Create',
    kind: MonacoKind.Method,
    detail: 'static FileStream Create(string path)',
    documentation: 'Creates file.',
    insertText: 'File.Create("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'File.OpenRead',
    kind: MonacoKind.Method,
    detail: 'static FileStream OpenRead(string path)',
    documentation: 'Opens file for reading.',
    insertText: 'File.OpenRead("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'File.OpenText',
    kind: MonacoKind.Method,
    detail: 'static StreamReader OpenText(string path)',
    documentation: 'Opens text file for reading.',
    insertText: 'File.OpenText("${1:path}")',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // Directory
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'Directory.CreateDirectory',
    kind: MonacoKind.Method,
    detail: 'static DirectoryInfo CreateDirectory(string path)',
    documentation: 'Creates directory.',
    insertText: 'Directory.CreateDirectory("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'Directory.Delete',
    kind: MonacoKind.Method,
    detail: 'static void Delete(string path, bool recursive)',
    documentation: 'Deletes directory.',
    insertText: 'Directory.Delete("${1:path}", ${2:false});',
    insertTextFormat: 2,
  },
  {
    label: 'Directory.Exists',
    kind: MonacoKind.Method,
    detail: 'static bool Exists(string? path)',
    documentation: 'Checks if directory exists.',
    insertText: 'Directory.Exists("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'Directory.Move',
    kind: MonacoKind.Method,
    detail: 'static void Move(string sourceDirName, string destDirName)',
    documentation: 'Moves directory.',
    insertText: 'Directory.Move("${1:source}", "${2:dest}");',
    insertTextFormat: 2,
  },
  {
    label: 'Directory.GetFiles',
    kind: MonacoKind.Method,
    detail: 'static string[] GetFiles(string path)',
    documentation: 'Gets files in directory.',
    insertText: 'Directory.GetFiles("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'Directory.GetDirectories',
    kind: MonacoKind.Method,
    detail: 'static string[] GetDirectories(string path)',
    documentation: 'Gets subdirectories.',
    insertText: 'Directory.GetDirectories("${1:path}")',
    insertTextFormat: 2,
  },
  {
    label: 'Directory.GetLogicalDrives',
    kind: MonacoKind.Method,
    detail: 'static string[] GetLogicalDrives()',
    documentation: 'Gets logical drives.',
    insertText: 'Directory.GetLogicalDrives()',
  },

  // ─────────────────────────────────────────────────────────────────
  // Stream
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'FileStream',
    kind: MonacoKind.Snippet,
    detail: 'FileStream',
    documentation: 'File stream.',
    insertText: 'using var ${1:stream} = new FileStream("${2:path}", FileMode.${3:Open});',
    insertTextFormat: 2,
  },
  {
    label: 'MemoryStream',
    kind: MonacoKind.Class,
    detail: 'MemoryStream',
    documentation: 'Memory stream.',
    insertText: 'var ${1:ms} = new MemoryStream();',
    insertTextFormat: 2,
  },
  {
    label: 'BufferedStream',
    kind: MonacoKind.Class,
    detail: 'BufferedStream',
    documentation: 'Buffered stream.',
    insertText: 'var ${1:bs} = new BufferedStream(${2:stream});',
    insertTextFormat: 2,
  },
  {
    label: 'stream.Read',
    kind: MonacoKind.Method,
    detail: 'int Read(byte[] buffer, int offset, int count)',
    documentation: 'Reads from stream.',
    insertText: 'stream.Read(${1:buffer}, ${2:0}, ${3:count})',
    insertTextFormat: 2,
  },
  {
    label: 'stream.Write',
    kind: MonacoKind.Method,
    detail: 'void Write(byte[] buffer, int offset, int count)',
    documentation: 'Writes to stream.',
    insertText: 'stream.Write(${1:buffer}, ${2:0}, ${3:count});',
    insertTextFormat: 2,
  },
  {
    label: 'stream.Flush',
    kind: MonacoKind.Method,
    detail: 'void Flush()',
    documentation: 'Flushes stream.',
    insertText: 'stream.Flush();',
    insertTextFormat: 2,
  },
  {
    label: 'stream.BeginRead',
    kind: MonacoKind.Method,
    detail: 'IAsyncResult BeginRead(byte[] buffer, int offset, int count, AsyncCallback? callback, object? state)',
    documentation: 'Begins async read.',
    insertText: 'stream.BeginRead(${1:buffer}, ${2:0}, ${3:count}, ${4:callback}, ${5:state})',
    insertTextFormat: 2,
  },
  {
    label: 'stream.BeginWrite',
    kind: MonacoKind.Method,
    detail: 'IAsyncResult BeginWrite(byte[] buffer, int offset, int count, AsyncCallback? callback, object? state)',
    documentation: 'Begins async write.',
    insertText: 'stream.BeginWrite(${1:buffer}, ${2:0}, ${3:count}, ${4:callback}, ${5:state})',
    insertTextFormat: 2,
  },
  {
    label: 'stream.EndRead',
    kind: MonacoKind.Method,
    detail: 'int EndRead(IAsyncResult asyncResult)',
    documentation: 'Ends async read.',
    insertText: 'stream.EndRead(${1:asyncResult})',
    insertTextFormat: 2,
  },
  {
    label: 'stream.EndWrite',
    kind: MonacoKind.Method,
    detail: 'void EndWrite(IAsyncResult asyncResult)',
    documentation: 'Ends async write.',
    insertText: 'stream.EndWrite(${1:asyncResult});',
    insertTextFormat: 2,
  },
  {
    label: 'stream.Position',
    kind: MonacoKind.Property,
    detail: 'long Position',
    documentation: 'Current position.',
    insertText: 'stream.Position',
  },
  {
    label: 'stream.Seek',
    kind: MonacoKind.Method,
    detail: 'long Seek(long offset, SeekOrigin origin)',
    documentation: 'Seeks position.',
    insertText: 'stream.Seek(${1:offset}, ${2:SeekOrigin.Begin});',
    insertTextFormat: 2,
  },
  {
    label: 'stream.SetLength',
    kind: MonacoKind.Method,
    detail: 'void SetLength(long value)',
    documentation: 'Sets stream length.',
    insertText: 'stream.SetLength(${1:value});',
    insertTextFormat: 2,
  },
  {
    label: 'stream.CanRead',
    kind: MonacoKind.Property,
    detail: 'bool CanRead',
    documentation: 'Can read from stream.',
    insertText: 'stream.CanRead',
  },
  {
    label: 'stream.CanWrite',
    kind: MonacoKind.Property,
    detail: 'bool CanWrite',
    documentation: 'Can write to stream.',
    insertText: 'stream.CanWrite',
  },
  {
    label: 'stream.CanSeek',
    kind: MonacoKind.Property,
    detail: 'bool CanSeek',
    documentation: 'Can seek in stream.',
    insertText: 'stream.CanSeek',
  },

  // ─────────────────────────────────────────────────────────────────
  // StreamReader / StreamWriter
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'StreamReader',
    kind: MonacoKind.Snippet,
    detail: 'StreamReader',
    documentation: 'Text reader stream.',
    insertText: 'using var ${1:reader} = new StreamReader("${2:path}");',
    insertTextFormat: 2,
  },
  {
    label: 'StreamWriter',
    kind: MonacoKind.Snippet,
    detail: 'StreamWriter',
    documentation: 'Text writer stream.',
    insertText: 'using var ${1:writer} = new StreamWriter("${2:path}");',
    insertTextFormat: 2,
  },
  {
    label: 'reader.Read',
    kind: MonacoKind.Method,
    detail: 'int Read()',
    documentation: 'Reads next character.',
    insertText: 'reader.Read()',
  },
  {
    label: 'reader.ReadLine',
    kind: MonacoKind.Method,
    detail: 'string? ReadLine()',
    documentation: 'Reads a line.',
    insertText: 'reader.ReadLine()',
  },
  {
    label: 'reader.ReadToEnd',
    kind: MonacoKind.Method,
    detail: 'string ReadToEnd()',
    documentation: 'Reads to end.',
    insertText: 'reader.ReadToEnd()',
  },
  {
    label: 'reader.Peek',
    kind: MonacoKind.Method,
    detail: 'int Peek()',
    documentation: 'Peeks next character.',
    insertText: 'reader.Peek()',
  },
  {
    label: 'writer.Write',
    kind: MonacoKind.Method,
    detail: 'void Write(string? value)',
    documentation: 'Writes to stream.',
    insertText: 'writer.Write(${1:value});',
    insertTextFormat: 2,
  },
  {
    label: 'writer.WriteLine',
    kind: MonacoKind.Method,
    detail: 'void WriteLine(string? value)',
    documentation: 'Writes line to stream.',
    insertText: 'writer.WriteLine(${1:value});',
    insertTextFormat: 2,
  },
  {
    label: 'writer.Flush',
    kind: MonacoKind.Method,
    detail: 'void Flush()',
    documentation: 'Flushes writer.',
    insertText: 'writer.Flush();',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // Encoding
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'Encoding.UTF8',
    kind: MonacoKind.Constant,
    detail: 'static Encoding UTF8',
    documentation: 'UTF-8 encoding.',
    insertText: 'Encoding.UTF8',
  },
  {
    label: 'Encoding.ASCII',
    kind: MonacoKind.Constant,
    detail: 'static Encoding ASCII',
    documentation: 'ASCII encoding.',
    insertText: 'Encoding.ASCII',
  },
  {
    label: 'Encoding.Unicode',
    kind: MonacoKind.Constant,
    detail: 'static Encoding Unicode',
    documentation: 'Unicode encoding (UTF-16).',
    insertText: 'Encoding.Unicode',
  },
  {
    label: 'Encoding.GetEncoding',
    kind: MonacoKind.Method,
    detail: 'static Encoding GetEncoding(string name)',
    documentation: 'Gets encoding by name.',
    insertText: 'Encoding.GetEncoding("${1:name}")',
    insertTextFormat: 2,
  },
  {
    label: 'Encoding.GetBytes',
    kind: MonacoKind.Method,
    detail: 'byte[] GetBytes(string s)',
    documentation: 'Converts string to bytes.',
    insertText: 'Encoding.UTF8.GetBytes(${1:s})',
    insertTextFormat: 2,
  },
  {
    label: 'Encoding.GetString',
    kind: MonacoKind.Method,
    detail: 'string GetString(byte[] bytes)',
    documentation: 'Converts bytes to string.',
    insertText: 'Encoding.UTF8.GetString(${1:bytes})',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // Convert
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'Convert.ToString',
    kind: MonacoKind.Method,
    detail: 'static string ToString(object? value)',
    documentation: 'Converts to string.',
    insertText: 'Convert.ToString(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'Convert.ToInt32',
    kind: MonacoKind.Method,
    detail: 'static int ToInt32(object? value)',
    documentation: 'Converts to 32-bit int.',
    insertText: 'Convert.ToInt32(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'Convert.ToInt64',
    kind: MonacoKind.Method,
    detail: 'static long ToInt64(object? value)',
    documentation: 'Converts to 64-bit int.',
    insertText: 'Convert.ToInt64(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'Convert.ToDouble',
    kind: MonacoKind.Method,
    detail: 'static double ToDouble(object? value)',
    documentation: 'Converts to double.',
    insertText: 'Convert.ToDouble(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'Convert.ToBoolean',
    kind: MonacoKind.Method,
    detail: 'static bool ToBoolean(object? value)',
    documentation: 'Converts to bool.',
    insertText: 'Convert.ToBoolean(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'Convert.ChangeType',
    kind: MonacoKind.Method,
    detail: 'static object? ChangeType(object? value, Type conversionType)',
    documentation: 'Changes type.',
    insertText: 'Convert.ChangeType(${1:value}, typeof(${2:T}))',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // Nullable / Option
  // ─────────────────────────────────────────────────────────────────
  {
    label: '? nullable',
    kind: MonacoKind.Snippet,
    detail: 'Nullable type modifier',
    documentation: 'Makes type nullable.',
    insertText: 'int? ${1:n} = null;',
    insertTextFormat: 2,
  },
  {
    label: '?. null-conditional',
    kind: MonacoKind.Snippet,
    detail: 'Null-conditional operator',
    documentation: 'Null-conditional member access.',
    insertText: '${1:obj}?.${2:Member}',
    insertTextFormat: 2,
  },
  {
    label: '?? null-coalescing',
    kind: MonacoKind.Snippet,
    detail: 'Null-coalescing operator',
    documentation: 'Returns left if not null, else right.',
    insertText: '${1:left} ?? ${2:right}',
    insertTextFormat: 2,
  },
  {
    label: '??= null-coalescing assignment',
    kind: MonacoKind.Snippet,
    detail: 'Null-coalescing assignment',
    documentation: 'Assigns if null.',
    insertText: '${1:x} ??= ${2:value};',
    insertTextFormat: 2,
  },
  {
    label: 'nullable.HasValue',
    kind: MonacoKind.Property,
    detail: 'bool HasValue',
    documentation: 'Checks if has value.',
    insertText: 'nullable.HasValue',
  },
  {
    label: 'nullable.Value',
    kind: MonacoKind.Property,
    detail: 'T Value',
    documentation: 'Gets value.',
    insertText: 'nullable.Value',
  },

  // ─────────────────────────────────────────────────────────────────
  // LINQ
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'using System.Linq',
    kind: MonacoKind.Snippet,
    detail: 'using directive',
    documentation: 'Imports LINQ.',
    insertText: 'using System.Linq;',
  },
  {
    label: '.Where()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TSource> Where(Func<TSource, bool> predicate)',
    documentation: 'Filters elements.',
    insertText: '.Where(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: '.Select()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TResult> Select(Func<TSource, TResult> selector)',
    documentation: 'Projects elements.',
    insertText: '.Select(${1:x => result})',
    insertTextFormat: 2,
  },
  {
    label: '.SelectMany()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TResult> SelectMany(Func<TSource, IEnumerable<TResult>> selector)',
    documentation: 'Flattens collections.',
    insertText: '.SelectMany(${1:x => x.Nested})',
    insertTextFormat: 2,
  },
  {
    label: '.OrderBy()',
    kind: MonacoKind.Method,
    detail: 'IOrderedEnumerable<TSource> OrderBy(Func<TSource, TKey> keySelector)',
    documentation: 'Orders ascending.',
    insertText: '.OrderBy(${1:x => x.Key})',
    insertTextFormat: 2,
  },
  {
    label: '.OrderByDescending()',
    kind: MonacoKind.Method,
    detail: 'IOrderedEnumerable<TSource> OrderByDescending(Func<TSource, TKey> keySelector)',
    documentation: 'Orders descending.',
    insertText: '.OrderByDescending(${1:x => x.Key})',
    insertTextFormat: 2,
  },
  {
    label: '.ThenBy()',
    kind: MonacoKind.Method,
    detail: 'IOrderedEnumerable<TSource> ThenBy(Func<TSource, TKey> keySelector)',
    documentation: 'Secondary ordering.',
    insertText: '.ThenBy(${1:x => x.Key})',
    insertTextFormat: 2,
  },
  {
    label: '.ThenByDescending()',
    kind: MonacoKind.Method,
    detail: 'IOrderedEnumerable<TSource> ThenByDescending(Func<TSource, TKey> keySelector)',
    documentation: 'Secondary ordering descending.',
    insertText: '.ThenByDescending(${1:x => x.Key})',
    insertTextFormat: 2,
  },
  {
    label: '.GroupBy()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<IGrouping<TKey, TSource>> GroupBy(Func<TSource, TKey> keySelector)',
    documentation: 'Groups elements.',
    insertText: '.GroupBy(${1:x => x.Key})',
    insertTextFormat: 2,
  },
  {
    label: '.Join()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TResult> Join<TInner, TKey, TResult>(IEnumerable<TInner> inner, Func<TSource, TKey> outerKeySelector, Func<TInner, TKey> innerKeySelector, Func<TSource, TInner, TResult> resultSelector)',
    documentation: 'Joins two sequences.',
    insertText: '.Join(${1:inner}, ${2:o => o.Key}, ${3:i => i.Key}, ${4:(o, i) => result})',
    insertTextFormat: 2,
  },
  {
    label: '.Any()',
    kind: MonacoKind.Method,
    detail: 'bool Any()',
    documentation: 'Checks if any element.',
    insertText: '.Any()',
  },
  {
    label: '.Any(predicate)',
    kind: MonacoKind.Method,
    detail: 'bool Any(Func<TSource, bool> predicate)',
    documentation: 'Checks if predicate matches.',
    insertText: '.Any(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: '.All()',
    kind: MonacoKind.Method,
    detail: 'bool All(Func<TSource, bool> predicate)',
    documentation: 'Checks if all match.',
    insertText: '.All(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: '.Contains()',
    kind: MonacoKind.Method,
    detail: 'bool Contains(TSource item)',
    documentation: 'Checks if contains item.',
    insertText: '.Contains(${1:item})',
    insertTextFormat: 2,
  },
  {
    label: '.First()',
    kind: MonacoKind.Method,
    detail: 'TSource First()',
    documentation: 'Gets first element.',
    insertText: '.First()',
  },
  {
    label: '.First(predicate)',
    kind: MonacoKind.Method,
    detail: 'TSource First(Func<TSource, bool> predicate)',
    documentation: 'Gets first matching.',
    insertText: '.First(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: '.FirstOrDefault()',
    kind: MonacoKind.Method,
    detail: 'TSource? FirstOrDefault()',
    documentation: 'Gets first or default.',
    insertText: '.FirstOrDefault()',
  },
  {
    label: '.FirstOrDefault(predicate)',
    kind: MonacoKind.Method,
    detail: 'TSource? FirstOrDefault(Func<TSource, bool> predicate)',
    documentation: 'Gets first matching or default.',
    insertText: '.FirstOrDefault(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: '.Last()',
    kind: MonacoKind.Method,
    detail: 'TSource Last()',
    documentation: 'Gets last element.',
    insertText: '.Last()',
  },
  {
    label: '.LastOrDefault()',
    kind: MonacoKind.Method,
    detail: 'TSource? LastOrDefault()',
    documentation: 'Gets last or default.',
    insertText: '.LastOrDefault()',
  },
  {
    label: '.Single()',
    kind: MonacoKind.Method,
    detail: 'TSource Single()',
    documentation: 'Gets single element.',
    insertText: '.Single()',
  },
  {
    label: '.SingleOrDefault()',
    kind: MonacoKind.Method,
    detail: 'TSource? SingleOrDefault()',
    documentation: 'Gets single or default.',
    insertText: '.SingleOrDefault()',
  },
  {
    label: '.ElementAt()',
    kind: MonacoKind.Method,
    detail: 'TSource ElementAt(int index)',
    documentation: 'Gets element at index.',
    insertText: '.ElementAt(${1:index})',
    insertTextFormat: 2,
  },
  {
    label: '.ElementAtOrDefault()',
    kind: MonacoKind.Method,
    detail: 'TSource? ElementAtOrDefault(int index)',
    documentation: 'Gets element at index or default.',
    insertText: '.ElementAtOrDefault(${1:index})',
    insertTextFormat: 2,
  },
  {
    label: '.Count()',
    kind: MonacoKind.Method,
    detail: 'int Count()',
    documentation: 'Counts elements.',
    insertText: '.Count()',
  },
  {
    label: '.Count(predicate)',
    kind: MonacoKind.Method,
    detail: 'int Count(Func<TSource, bool> predicate)',
    documentation: 'Counts matching elements.',
    insertText: '.Count(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: '.LongCount()',
    kind: MonacoKind.Method,
    detail: 'long LongCount()',
    documentation: 'Counts as long.',
    insertText: '.LongCount()',
  },
  {
    label: '.Sum()',
    kind: MonacoKind.Method,
    detail: 'int Sum(Func<TSource, int> selector)',
    documentation: 'Sums values.',
    insertText: '.Sum(${1:x => x.Value})',
    insertTextFormat: 2,
  },
  {
    label: '.Average()',
    kind: MonacoKind.Method,
    detail: 'double Average(Func<TSource, int> selector)',
    documentation: 'Averages values.',
    insertText: '.Average(${1:x => x.Value})',
    insertTextFormat: 2,
  },
  {
    label: '.Min()',
    kind: MonacoKind.Method,
    detail: 'TSource Min()',
    documentation: 'Gets minimum.',
    insertText: '.Min()',
  },
  {
    label: '.Max()',
    kind: MonacoKind.Method,
    detail: 'TSource Max()',
    documentation: 'Gets maximum.',
    insertText: '.Max()',
  },
  {
    label: '.Aggregate()',
    kind: MonacoKind.Method,
    detail: 'TResult Aggregate(TSeed seed, Func<TAccumulate, TSource, TAccumulate> func)',
    documentation: 'Aggregates elements.',
    insertText: '.Aggregate(${1:seed}, ${2:(acc, x) => acc + x})',
    insertTextFormat: 2,
  },
  {
    label: '.Distinct()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TSource> Distinct()',
    documentation: 'Removes duplicates.',
    insertText: '.Distinct()',
  },
  {
    label: '.Union()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TSource> Union(IEnumerable<TSource> second)',
    documentation: 'Union of sequences.',
    insertText: '.Union(${1:second})',
    insertTextFormat: 2,
  },
  {
    label: '.Intersect()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TSource> Intersect(IEnumerable<TSource> second)',
    documentation: 'Intersection of sequences.',
    insertText: '.Intersect(${1:second})',
    insertTextFormat: 2,
  },
  {
    label: '.Except()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TSource> Except(IEnumerable<TSource> second)',
    documentation: 'Set difference.',
    insertText: '.Except(${1:second})',
    insertTextFormat: 2,
  },
  {
    label: '.Skip()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TSource> Skip(int count)',
    documentation: 'Skips elements.',
    insertText: '.Skip(${1:count})',
    insertTextFormat: 2,
  },
  {
    label: '.Take()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TSource> Take(int count)',
    documentation: 'Takes elements.',
    insertText: '.Take(${1:count})',
    insertTextFormat: 2,
  },
  {
    label: '.SkipWhile()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TSource> SkipWhile(Func<TSource, bool> predicate)',
    documentation: 'Skips while condition.',
    insertText: '.SkipWhile(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: '.TakeWhile()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TSource> TakeWhile(Func<TSource, bool> predicate)',
    documentation: 'Takes while condition.',
    insertText: '.TakeWhile(${1:x => condition})',
    insertTextFormat: 2,
  },
  {
    label: '.Concat()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TSource> Concat(IEnumerable<TSource> second)',
    documentation: 'Concatenates sequences.',
    insertText: '.Concat(${1:second})',
    insertTextFormat: 2,
  },
  {
    label: '.Reverse()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TSource> Reverse()',
    documentation: 'Reverses sequence.',
    insertText: '.Reverse()',
  },
  {
    label: '.ToList()',
    kind: MonacoKind.Method,
    detail: 'List<TSource> ToList()',
    documentation: 'Converts to list.',
    insertText: '.ToList()',
  },
  {
    label: '.ToArray()',
    kind: MonacoKind.Method,
    detail: 'TSource[] ToArray()',
    documentation: 'Converts to array.',
    insertText: '.ToArray()',
  },
  {
    label: '.ToDictionary()',
    kind: MonacoKind.Method,
    detail: 'Dictionary<TKey, TSource> ToDictionary(Func<TSource, TKey> keySelector)',
    documentation: 'Converts to dictionary.',
    insertText: '.ToDictionary(${1:x => x.Key})',
    insertTextFormat: 2,
  },
  {
    label: '.ToHashSet()',
    kind: MonacoKind.Method,
    detail: 'HashSet<TSource> ToHashSet()',
    documentation: 'Converts to hash set.',
    insertText: '.ToHashSet()',
  },
  {
    label: '.OfType<T>()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<T> OfType<T>()',
    documentation: 'Filters by type.',
    insertText: '.OfType<${1:T}>()',
    insertTextFormat: 2,
  },
  {
    label: '.Cast<T>()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<T> Cast<T>()',
    documentation: 'Casts to type.',
    insertText: '.Cast<${1:T}>()',
    insertTextFormat: 2,
  },
  {
    label: '.DefaultIfEmpty()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TSource> DefaultIfEmpty()',
    documentation: 'Returns default if empty.',
    insertText: '.DefaultIfEmpty()',
  },
  {
    label: '.Zip()',
    kind: MonacoKind.Method,
    detail: 'IEnumerable<TResult> Zip<TSecond, TResult>(IEnumerable<TSecond> second, Func<TSource, TSecond, TResult> resultSelector)',
    documentation: 'Zips two sequences.',
    insertText: '.Zip(${1:second}, ${2:(a, b) => (a, b)})',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // Async / Await
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'async Task',
    kind: MonacoKind.Snippet,
    detail: 'async Task method',
    documentation: 'Async method returning Task.',
    insertText: 'async Task ${1:MethodName}Async() {\n\t${2:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'async Task<T>',
    kind: MonacoKind.Snippet,
    detail: 'async Task<T> method',
    documentation: 'Async method returning T.',
    insertText: 'async Task<${1:T}> ${2:MethodName}Async() {\n\treturn ${3:value};\n}',
    insertTextFormat: 2,
  },
  {
    label: 'async void',
    kind: MonacoKind.Snippet,
    detail: 'async void method',
    documentation: 'Async void event handler.',
    insertText: 'async void ${1:EventHandler}(object? sender, ${2:EventArgs} e) {\n\t${3:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'await Task.Delay',
    kind: MonacoKind.Method,
    detail: 'Task Delay(TimeSpan)',
    documentation: 'Async delay.',
    insertText: 'await Task.Delay(${1:TimeSpan.FromSeconds(1)});',
    insertTextFormat: 2,
  },
  {
    label: 'await Task.Run',
    kind: MonacoKind.Snippet,
    detail: 'Task Run(Action)',
    documentation: 'Runs work on thread pool.',
    insertText: 'await Task.Run(() => {\n\t${1:// code}\n});',
    insertTextFormat: 2,
  },
  {
    label: 'Task.WhenAll',
    kind: MonacoKind.Method,
    detail: 'static Task WhenAll(params Task[] tasks)',
    documentation: 'Waits for all tasks.',
    insertText: 'await Task.WhenAll(${1:tasks});',
    insertTextFormat: 2,
  },
  {
    label: 'Task.WhenAny',
    kind: MonacoKind.Method,
    detail: 'static Task<Task> WhenAny(params Task[] tasks)',
    documentation: 'Waits for any task.',
    insertText: 'await Task.WhenAny(${1:tasks});',
    insertTextFormat: 2,
  },
  {
    label: 'Task.FromResult',
    kind: MonacoKind.Method,
    detail: 'static Task<T> FromResult<T>(T result)',
    documentation: 'Creates completed task.',
    insertText: 'Task.FromResult(${1:value})',
    insertTextFormat: 2,
  },
  {
    label: 'Task.FromCanceled',
    kind: MonacoKind.Method,
    detail: 'static Task FromCanceled(CancellationToken cancellationToken)',
    documentation: 'Creates canceled task.',
    insertText: 'Task.FromCanceled(new CancellationToken(true))',
  },
  {
    label: 'Task.Yield',
    kind: MonacoKind.Method,
    detail: 'static YieldAwaitable Yield()',
    documentation: 'Yields to context.',
    insertText: 'await Task.Yield();',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // Pattern Matching / Records
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'if (x is Type y)',
    kind: MonacoKind.Snippet,
    detail: 'type pattern',
    documentation: 'Pattern matching.',
    insertText: 'if (${1:x} is ${2:TypeName} ${3:y}) {\n\t${4:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'switch with pattern',
    kind: MonacoKind.Snippet,
    detail: 'switch with pattern matching',
    documentation: 'Pattern matching switch.',
    insertText: 'switch (${1:expr}) {\n\tcase ${2:TypeName} ${3:var}:\n\t\t${4:// code}\n\t\tbreak;\n\tdefault:\n\t\t${5:// code}\n\t\tbreak;\n}',
    insertTextFormat: 2,
  },
  {
    label: 'record',
    kind: MonacoKind.Snippet,
    detail: 'record type',
    documentation: 'Immutable record.',
    insertText: 'public record ${1:Name}(${2:int Value});',
    insertTextFormat: 2,
  },

  // ─────────────────────────────────────────────────────────────────
  // Control Flow Snippets
  // ─────────────────────────────────────────────────────────────────
  {
    label: 'if',
    kind: MonacoKind.Snippet,
    detail: 'if statement',
    documentation: 'If statement.',
    insertText: 'if (${1:condition}) {\n\t${2:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'if-else',
    kind: MonacoKind.Snippet,
    detail: 'if-else statement',
    documentation: 'If-else statement.',
    insertText: 'if (${1:condition}) {\n\t${2:// code}\n} else {\n\t${3:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'for',
    kind: MonacoKind.Snippet,
    detail: 'for loop',
    documentation: 'For loop.',
    insertText: 'for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t${3:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'foreach',
    kind: MonacoKind.Snippet,
    detail: 'foreach loop',
    documentation: 'Foreach loop.',
    insertText: 'foreach (var ${1:item} in ${2:collection}) {\n\t${3:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'while',
    kind: MonacoKind.Snippet,
    detail: 'while loop',
    documentation: 'While loop.',
    insertText: 'while (${1:condition}) {\n\t${2:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'do-while',
    kind: MonacoKind.Snippet,
    detail: 'do-while loop',
    documentation: 'Do-while loop.',
    insertText: 'do {\n\t${1:// code}\n} while (${2:condition});',
    insertTextFormat: 2,
  },
  {
    label: 'switch',
    kind: MonacoKind.Snippet,
    detail: 'switch statement',
    documentation: 'Switch statement.',
    insertText: 'switch (${1:expr}) {\n\tcase ${2:val1}:\n\t\t${3:// code}\n\t\tbreak;\n\tcase ${4:val2}:\n\t\t${5:// code}\n\t\tbreak;\n\tdefault:\n\t\t${6:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'switch expression',
    kind: MonacoKind.Snippet,
    detail: 'switch expression',
    documentation: 'Switch expression.',
    insertText: '${1:result} = ${2:expr} switch {\n\t${3:val1} => ${4:result1},\n\t${5:val2} => ${6:result2},\n\t_ => ${7:default}\n};',
    insertTextFormat: 2,
  },
  {
    label: 'try-catch',
    kind: MonacoKind.Snippet,
    detail: 'try-catch block',
    documentation: 'Try-catch block.',
    insertText: 'try {\n\t${1:// code}\n} catch (${2:Exception} ${3:e}) {\n\t${4:// handle exception}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'try-catch-finally',
    kind: MonacoKind.Snippet,
    detail: 'try-catch-finally block',
    documentation: 'Try-catch-finally block.',
    insertText: 'try {\n\t${1:// code}\n} catch (${2:Exception} ${3:e}) {\n\t${4:// handle exception}\n} finally {\n\t${5:// cleanup}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'class',
    kind: MonacoKind.Snippet,
    detail: 'class definition',
    documentation: 'Class definition.',
    insertText: 'public class ${1:ClassName} {\n\t${2:// fields\n\t// constructors\n\t// properties\n\t// methods\n}',
    insertTextFormat: 2,
  },
  {
    label: 'interface',
    kind: MonacoKind.Snippet,
    detail: 'interface definition',
    documentation: 'Interface definition.',
    insertText: 'public interface ${1:IInterfaceName} {\n\t${2:// methods\n}',
    insertTextFormat: 2,
  },
  {
    label: 'struct',
    kind: MonacoKind.Snippet,
    detail: 'struct definition',
    documentation: 'Struct definition.',
    insertText: 'public struct ${1:StructName} {\n\t${2:// fields and properties\n}',
    insertTextFormat: 2,
  },
  {
    label: 'enum',
    kind: MonacoKind.Snippet,
    detail: 'enum definition',
    documentation: 'Enum definition.',
    insertText: 'public enum ${1:EnumName} {\n\t${2:Value1},\n\t${3:Value2}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'namespace',
    kind: MonacoKind.Snippet,
    detail: 'namespace',
    documentation: 'Namespace.',
    insertText: 'namespace ${1:Namespace} {\n\t${2:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'using',
    kind: MonacoKind.Snippet,
    detail: 'using directive',
    documentation: 'Using directive.',
    insertText: 'using ${1:System};',
    insertTextFormat: 2,
  },
  {
    label: 'var',
    kind: MonacoKind.Snippet,
    detail: 'var keyword',
    documentation: 'Var keyword.',
    insertText: 'var ${1:varName} = ${2:value};',
    insertTextFormat: 2,
  },
  {
    label: 'new',
    kind: MonacoKind.Snippet,
    detail: 'new object',
    documentation: 'New object.',
    insertText: 'new ${1:Type}(${2:args});',
    insertTextFormat: 2,
  },
  {
    label: 'this',
    kind: MonacoKind.Snippet,
    detail: 'this keyword',
    documentation: 'This keyword.',
    insertText: 'this.${1:member}',
    insertTextFormat: 2,
  },
  {
    label: 'base',
    kind: MonacoKind.Snippet,
    detail: 'base keyword',
    documentation: 'Base keyword.',
    insertText: 'base.${1:member}',
    insertTextFormat: 2,
  },
  {
    label: 'get; set;',
    kind: MonacoKind.Snippet,
    detail: 'property auto-implemented',
    documentation: 'Auto-implemented property.',
    insertText: 'public ${1:int} ${2:Property} { get; set; }',
    insertTextFormat: 2,
  },
  {
    label: 'get => / set =>',
    kind: MonacoKind.Snippet,
    detail: 'expression-bodied property',
    documentation: 'Expression-bodied property.',
    insertText: 'public ${1:int} ${2:Property} { get => ${3:field}; set => ${3:field} = value; }',
    insertTextFormat: 2,
  },
  {
    label: 'delegate',
    kind: MonacoKind.Snippet,
    detail: 'delegate',
    documentation: 'Delegate type.',
    insertText: 'delegate ${1:void} ${2:DelegateName}(${3:params});',
    insertTextFormat: 2,
  },
  {
    label: 'event',
    kind: MonacoKind.Snippet,
    detail: 'event',
    documentation: 'Event declaration.',
    insertText: 'public event ${1:EventHandler} ${2:EventName};',
    insertTextFormat: 2,
  },
  {
    label: 'yield return',
    kind: MonacoKind.Snippet,
    detail: 'yield return',
    documentation: 'Returns value in iterator.',
    insertText: 'yield return ${1:value};',
    insertTextFormat: 2,
  },
  {
    label: 'lock',
    kind: MonacoKind.Snippet,
    detail: 'lock statement',
    documentation: 'Lock statement.',
    insertText: 'lock (${1:lockObject}) {\n\t${2:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'using statement',
    kind: MonacoKind.Snippet,
    detail: 'using statement',
    documentation: 'Using statement.',
    insertText: 'using (${1:var} = ${2:new}) {\n\t${3:// code}\n}',
    insertTextFormat: 2,
  },
  {
    label: 'using var',
    kind: MonacoKind.Snippet,
    detail: 'using var declaration',
    documentation: 'Using var declaration.',
    insertText: 'using var ${1:varName} = ${2:new};\n${3:// code}',
    insertTextFormat: 2,
  },
];
