import { LspCompletionItem, MonacoKind } from "./types";

export const JAVA_API_COMPLETIONS: LspCompletionItem[] = [
  // java.lang.System
  {
    label: "System",
    kind: MonacoKind.Class,
    detail: "java.lang.System",
    documentation:
      "The System class contains several useful class fields and methods.",
    insertText: "System",
  },
  {
    label: "System.out.println",
    kind: MonacoKind.Method,
    detail: "void println()",
    documentation: "Prints a line to standard output with a newline.",
    insertText: "System.out.println(${1:value});",
    insertTextFormat: 2,
  },
  {
    label: "System.out.print",
    kind: MonacoKind.Method,
    detail: "void print()",
    documentation: "Prints a value to standard output without newline.",
    insertText: "System.out.print(${1:value});",
    insertTextFormat: 2,
  },
  {
    label: "System.out.printf",
    kind: MonacoKind.Method,
    detail: "void printf(String format, Object... args)",
    documentation: "Prints a formatted string to standard output.",
    insertText: 'System.out.printf("${1:format}", ${2:args});',
    insertTextFormat: 2,
  },
  {
    label: "System.in",
    kind: MonacoKind.Variable,
    detail: "java.io.InputStream",
    documentation: "The standard input stream.",
    insertText: "System.in",
  },
  {
    label: "System.exit",
    kind: MonacoKind.Method,
    detail: "void exit(int status)",
    documentation: "Terminates the currently running Java Virtual Machine.",
    insertText: "System.exit(${1:0});",
    insertTextFormat: 2,
  },
  {
    label: "System.currentTimeMillis",
    kind: MonacoKind.Method,
    detail: "long currentTimeMillis()",
    documentation: "Returns the current time in milliseconds.",
    insertText: "System.currentTimeMillis()",
  },

  // java.util.Scanner
  {
    label: "Scanner",
    kind: MonacoKind.Class,
    detail: "java.util.Scanner",
    documentation:
      "A simple text scanner which can parse primitive types and strings.",
    insertText: "Scanner scanner = new Scanner(System.in);\nscanner.close();",
    insertTextFormat: 2,
  },
  {
    label: "scanner.nextInt",
    kind: MonacoKind.Method,
    detail: "int nextInt()",
    documentation: "Scans the next token of the input as an int.",
    insertText: "scanner.nextInt()",
  },
  {
    label: "scanner.next",
    kind: MonacoKind.Method,
    detail: "String next()",
    documentation:
      "Finds and returns the next complete token from this scanner.",
    insertText: "scanner.next()",
  },
  {
    label: "scanner.nextLine",
    kind: MonacoKind.Method,
    detail: "String nextLine()",
    documentation:
      "Advances this scanner past the current line and returns the input that was skipped.",
    insertText: "scanner.nextLine()",
  },
  {
    label: "scanner.nextDouble",
    kind: MonacoKind.Method,
    detail: "double nextDouble()",
    documentation: "Scans the next token of the input as a double.",
    insertText: "scanner.nextDouble()",
  },
  {
    label: "scanner.nextLong",
    kind: MonacoKind.Method,
    detail: "long nextLong()",
    documentation: "Scans the next token of the input as a long.",
    insertText: "scanner.nextLong()",
  },
  {
    label: "scanner.hasNextInt",
    kind: MonacoKind.Method,
    detail: "boolean hasNextInt()",
    documentation:
      "Returns true if the next token in this scanner's input can be interpreted as an int.",
    insertText: "scanner.hasNextInt()",
  },
  {
    label: "scanner.hasNext",
    kind: MonacoKind.Method,
    detail: "boolean hasNext()",
    documentation:
      "Returns true if this scanner has another token in its input.",
    insertText: "scanner.hasNext()",
  },
  {
    label: "scanner.close",
    kind: MonacoKind.Method,
    detail: "void close()",
    documentation: "Closes this scanner.",
    insertText: "scanner.close();",
  },

  // java.lang.String
  {
    label: "String",
    kind: MonacoKind.Class,
    detail: "java.lang.String",
    documentation: "The String class represents character strings.",
    insertText: "String",
  },
  {
    label: "str.length",
    kind: MonacoKind.Method,
    detail: "int length()",
    documentation: "Returns the length of this string.",
    insertText: "str.length()",
  },
  {
    label: "str.substring",
    kind: MonacoKind.Method,
    detail: "String substring(int beginIndex)",
    documentation: "Returns a new string that is a substring of this string.",
    insertText: "str.substring(${1:beginIndex})",
    insertTextFormat: 2,
  },
  {
    label: "str.indexOf",
    kind: MonacoKind.Method,
    detail: "int indexOf(String str)",
    documentation:
      "Returns the index of the first occurrence of the specified substring.",
    insertText: "str.indexOf(${1:str})",
    insertTextFormat: 2,
  },
  {
    label: "str.equals",
    kind: MonacoKind.Method,
    detail: "boolean equals(Object anObject)",
    documentation: "Compares this string to the specified object.",
    insertText: "str.equals(${1:other})",
    insertTextFormat: 2,
  },
  {
    label: "str.toLowerCase",
    kind: MonacoKind.Method,
    detail: "String toLowerCase()",
    documentation: "Converts all characters to lowercase.",
    insertText: "str.toLowerCase()",
  },
  {
    label: "str.toUpperCase",
    kind: MonacoKind.Method,
    detail: "String toUpperCase()",
    documentation: "Converts all characters to uppercase.",
    insertText: "str.toUpperCase()",
  },
  {
    label: "str.trim",
    kind: MonacoKind.Method,
    detail: "String trim()",
    documentation:
      "Returns a string whose value is this string, with leading and trailing whitespace removed.",
    insertText: "str.trim()",
  },
  {
    label: "str.split",
    kind: MonacoKind.Method,
    detail: "String[] split(String regex)",
    documentation:
      "Splits this string around matches of the given regular expression.",
    insertText: 'str.split("${1:regex}")',
    insertTextFormat: 2,
  },
  {
    label: "str.charAt",
    kind: MonacoKind.Method,
    detail: "char charAt(int index)",
    documentation: "Returns the char value at the specified index.",
    insertText: "str.charAt(${1:index})",
    insertTextFormat: 2,
  },
  {
    label: "str.replace",
    kind: MonacoKind.Method,
    detail: "String replace(char oldChar, char newChar)",
    documentation:
      "Returns a string resulting from replacing all occurrences of oldChar with newChar.",
    insertText: "str.replace(${1:oldChar}, ${2:newChar})",
    insertTextFormat: 2,
  },
  {
    label: "str.replaceAll",
    kind: MonacoKind.Method,
    detail: "String replaceAll(String regex, String replacement)",
    documentation: "Replaces each substring matching the regular expression.",
    insertText: 'str.replaceAll("${1:regex}", "${2:replacement}")',
    insertTextFormat: 2,
  },
  {
    label: "str.startsWith",
    kind: MonacoKind.Method,
    detail: "boolean startsWith(String prefix)",
    documentation: "Tests if this string starts with the specified prefix.",
    insertText: 'str.startsWith("${1:prefix}")',
    insertTextFormat: 2,
  },
  {
    label: "str.endsWith",
    kind: MonacoKind.Method,
    detail: "boolean endsWith(String suffix)",
    documentation: "Tests if this string ends with the specified suffix.",
    insertText: 'str.endsWith("${1:suffix}")',
    insertTextFormat: 2,
  },
  {
    label: "str.contains",
    kind: MonacoKind.Method,
    detail: "boolean contains(CharSequence s)",
    documentation:
      "Returns true if this string contains the specified sequence of char values.",
    insertText: "str.contains(${1:s})",
    insertTextFormat: 2,
  },
  {
    label: "str.isEmpty",
    kind: MonacoKind.Method,
    detail: "boolean isEmpty()",
    documentation: "Returns true if length() is 0.",
    insertText: "str.isEmpty()",
  },
  {
    label: "str.concat",
    kind: MonacoKind.Method,
    detail: "String concat(String str)",
    documentation:
      "Concatenates the specified string to the end of this string.",
    insertText: "str.concat(${1:str})",
    insertTextFormat: 2,
  },
  {
    label: "str.valueOf",
    kind: MonacoKind.Method,
    detail: "static String valueOf(...)",
    documentation: "Returns the string representation of various types.",
    insertText: "String.valueOf(${1:obj})",
    insertTextFormat: 2,
  },

  // java.util.Arrays
  {
    label: "Arrays",
    kind: MonacoKind.Class,
    detail: "java.util.Arrays",
    documentation:
      "Contains methods to manipulate arrays (sort, search, compare, fill).",
    insertText: "Arrays",
  },
  {
    label: "Arrays.sort",
    kind: MonacoKind.Method,
    detail: "void sort(Object[] a)",
    documentation: "Sorts the specified array into ascending order.",
    insertText: "Arrays.sort(${1:array});",
    insertTextFormat: 2,
  },
  {
    label: "Arrays.toString",
    kind: MonacoKind.Method,
    detail: "String toString(Object[] a)",
    documentation:
      "Returns a string representation of the contents of the specified array.",
    insertText: "Arrays.toString(${1:array})",
    insertTextFormat: 2,
  },
  {
    label: "Arrays.asList",
    kind: MonacoKind.Method,
    detail: "static List asList(T... a)",
    documentation: "Returns a fixed-size list backed by the specified array.",
    insertText: "Arrays.asList(${1:array})",
    insertTextFormat: 2,
  },
  {
    label: "Arrays.binarySearch",
    kind: MonacoKind.Method,
    detail: "int binarySearch(Object[] a, Object key)",
    documentation:
      "Searches the specified array for the specified value using the binary search algorithm.",
    insertText: "Arrays.binarySearch(${1:array}, ${2:key})",
    insertTextFormat: 2,
  },
  {
    label: "Arrays.fill",
    kind: MonacoKind.Method,
    detail: "void fill(Object[] a, Object val)",
    documentation:
      "Assigns the specified value to each element of the specified array.",
    insertText: "Arrays.fill(${1:array}, ${2:val});",
    insertTextFormat: 2,
  },
  {
    label: "Arrays.copyOf",
    kind: MonacoKind.Method,
    detail: "T[] copyOf(T[] original, int newLength)",
    documentation:
      "Copies the specified array, truncating or padding with zeros.",
    insertText: "Arrays.copyOf(${1:original}, ${2:newLength})",
    insertTextFormat: 2,
  },

  // java.util.List / ArrayList
  {
    label: "ArrayList",
    kind: MonacoKind.Class,
    detail: "java.util.ArrayList",
    documentation: "Resizable-array implementation of the List interface.",
    insertText: "ArrayList<${1:E}> ${2:list} = new ArrayList<>();",
    insertTextFormat: 2,
  },
  {
    label: "list.add",
    kind: MonacoKind.Method,
    detail: "boolean add(E e)",
    documentation: "Appends the specified element to the end of this list.",
    insertText: "list.add(${1:element});",
    insertTextFormat: 2,
  },
  {
    label: "list.get",
    kind: MonacoKind.Method,
    detail: "E get(int index)",
    documentation:
      "Returns the element at the specified position in this list.",
    insertText: "list.get(${1:index})",
    insertTextFormat: 2,
  },
  {
    label: "list.set",
    kind: MonacoKind.Method,
    detail: "E set(int index, E element)",
    documentation:
      "Replaces the element at the specified position in this list.",
    insertText: "list.set(${1:index}, ${2:element})",
    insertTextFormat: 2,
  },
  {
    label: "list.size",
    kind: MonacoKind.Method,
    detail: "int size()",
    documentation: "Returns the number of elements in this list.",
    insertText: "list.size()",
  },
  {
    label: "list.isEmpty",
    kind: MonacoKind.Method,
    detail: "boolean isEmpty()",
    documentation: "Returns true if this list contains no elements.",
    insertText: "list.isEmpty()",
  },
  {
    label: "list.contains",
    kind: MonacoKind.Method,
    detail: "boolean contains(Object o)",
    documentation: "Returns true if this list contains the specified element.",
    insertText: "list.contains(${1:o})",
    insertTextFormat: 2,
  },
  {
    label: "list.remove",
    kind: MonacoKind.Method,
    detail: "E remove(int index)",
    documentation:
      "Removes the element at the specified position in this list.",
    insertText: "list.remove(${1:index})",
    insertTextFormat: 2,
  },
  {
    label: "list.clear",
    kind: MonacoKind.Method,
    detail: "void clear()",
    documentation: "Removes all elements from this list.",
    insertText: "list.clear();",
  },
  {
    label: "list.indexOf",
    kind: MonacoKind.Method,
    detail: "int indexOf(Object o)",
    documentation:
      "Returns the index of the first occurrence of the specified element.",
    insertText: "list.indexOf(${1:o})",
    insertTextFormat: 2,
  },
  {
    label: "list.addAll",
    kind: MonacoKind.Method,
    detail: "boolean addAll(Collection c)",
    documentation:
      "Appends all elements of the specified collection to the end of this list.",
    insertText: "list.addAll(${1:c});",
    insertTextFormat: 2,
  },

  // java.util.Map / HashMap
  {
    label: "HashMap",
    kind: MonacoKind.Class,
    detail: "java.util.HashMap",
    documentation: "Hash table based implementation of the Map interface.",
    insertText: "HashMap<${1:K}, ${2:V}> ${3:map} = new HashMap<>();",
    insertTextFormat: 2,
  },
  {
    label: "map.put",
    kind: MonacoKind.Method,
    detail: "V put(K key, V value)",
    documentation: "Associates the specified value with the specified key.",
    insertText: "map.put(${1:key}, ${2:value});",
    insertTextFormat: 2,
  },
  {
    label: "map.get",
    kind: MonacoKind.Method,
    detail: "V get(Object key)",
    documentation: "Returns the value associated with the specified key.",
    insertText: "map.get(${1:key})",
    insertTextFormat: 2,
  },
  {
    label: "map.containsKey",
    kind: MonacoKind.Method,
    detail: "boolean containsKey(Object key)",
    documentation:
      "Returns true if this map contains a mapping for the specified key.",
    insertText: "map.containsKey(${1:key})",
    insertTextFormat: 2,
  },
  {
    label: "map.containsValue",
    kind: MonacoKind.Method,
    detail: "boolean containsValue(Object value)",
    documentation:
      "Returns true if this map contains a mapping for the specified value.",
    insertText: "map.containsValue(${1:value})",
    insertTextFormat: 2,
  },
  {
    label: "map.keySet",
    kind: MonacoKind.Method,
    detail: "Set<K> keySet()",
    documentation: "Returns a Set view of the keys contained in this map.",
    insertText: "map.keySet()",
  },
  {
    label: "map.values",
    kind: MonacoKind.Method,
    detail: "Collection<V> values()",
    documentation:
      "Returns a Collection view of the values contained in this map.",
    insertText: "map.values()",
  },
  {
    label: "map.size",
    kind: MonacoKind.Method,
    detail: "int size()",
    documentation: "Returns the number of key-value mappings in this map.",
    insertText: "map.size()",
  },
  {
    label: "map.isEmpty",
    kind: MonacoKind.Method,
    detail: "boolean isEmpty()",
    documentation: "Returns true if this map contains no key-value mappings.",
    insertText: "map.isEmpty()",
  },
  {
    label: "map.remove",
    kind: MonacoKind.Method,
    detail: "V remove(Object key)",
    documentation: "Removes the mapping for the specified key from this map.",
    insertText: "map.remove(${1:key});",
    insertTextFormat: 2,
  },
  {
    label: "map.clear",
    kind: MonacoKind.Method,
    detail: "void clear()",
    documentation: "Removes all mappings from this map.",
    insertText: "map.clear();",
  },

  // java.util.Set / HashSet
  {
    label: "HashSet",
    kind: MonacoKind.Class,
    detail: "java.util.HashSet",
    documentation: "Hash table based implementation of the Set interface.",
    insertText: "HashSet<${1:E}> ${2:set} = new HashSet<>();",
    insertTextFormat: 2,
  },
  {
    label: "set.add",
    kind: MonacoKind.Method,
    detail: "boolean add(E e)",
    documentation:
      "Adds the specified element to this set if it is not already present.",
    insertText: "set.add(${1:element});",
    insertTextFormat: 2,
  },
  {
    label: "set.contains",
    kind: MonacoKind.Method,
    detail: "boolean contains(Object o)",
    documentation: "Returns true if this set contains the specified element.",
    insertText: "set.contains(${1:o})",
    insertTextFormat: 2,
  },
  {
    label: "set.remove",
    kind: MonacoKind.Method,
    detail: "boolean remove(Object o)",
    documentation: "Removes the specified element from this set if present.",
    insertText: "set.remove(${1:o});",
    insertTextFormat: 2,
  },
  {
    label: "set.size",
    kind: MonacoKind.Method,
    detail: "int size()",
    documentation: "Returns the number of elements in this set.",
    insertText: "set.size()",
  },
  {
    label: "set.isEmpty",
    kind: MonacoKind.Method,
    detail: "boolean isEmpty()",
    documentation: "Returns true if this set contains no elements.",
    insertText: "set.isEmpty()",
  },
  {
    label: "set.clear",
    kind: MonacoKind.Method,
    detail: "void clear()",
    documentation: "Removes all elements from this set.",
    insertText: "set.clear();",
  },

  // java.io classes
  {
    label: "BufferedReader",
    kind: MonacoKind.Class,
    detail: "java.io.BufferedReader",
    documentation:
      "Reads text from a character-input stream, buffering characters.",
    insertText:
      "BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));",
  },
  {
    label: "BufferedWriter",
    kind: MonacoKind.Class,
    detail: "java.io.BufferedWriter",
    documentation:
      "Writes text to a character-output stream, buffering characters.",
    insertText:
      "BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(System.out));",
  },
  {
    label: "reader.readLine",
    kind: MonacoKind.Method,
    detail: "String readLine()",
    documentation: "Reads a line of text.",
    insertText: "reader.readLine()",
  },
  {
    label: "writer.write",
    kind: MonacoKind.Method,
    detail: "void write(String s, int off, int len)",
    documentation: "Writes a portion of a string.",
    insertText: "writer.write(${1:s});",
    insertTextFormat: 2,
  },
  {
    label: "writer.newLine",
    kind: MonacoKind.Method,
    detail: "void newLine()",
    documentation: "Writes a line separator.",
    insertText: "writer.newLine();",
  },
  {
    label: "writer.flush",
    kind: MonacoKind.Method,
    detail: "void flush()",
    documentation: "Flushes the stream.",
    insertText: "writer.flush();",
  },
  {
    label: "reader.close",
    kind: MonacoKind.Method,
    detail: "void close()",
    documentation: "Closes the stream.",
    insertText: "reader.close();",
  },
  {
    label: "writer.close",
    kind: MonacoKind.Method,
    detail: "void close()",
    documentation: "Closes the stream.",
    insertText: "writer.close();",
  },

  // Math
  {
    label: "Math.abs",
    kind: MonacoKind.Method,
    detail: "static double abs(double a)",
    documentation: "Returns the absolute value of a double value.",
    insertText: "Math.abs(${1:a})",
    insertTextFormat: 2,
  },
  {
    label: "Math.max",
    kind: MonacoKind.Method,
    detail: "static int max(int a, int b)",
    documentation: "Returns the greater of two int values.",
    insertText: "Math.max(${1:a}, ${2:b})",
    insertTextFormat: 2,
  },
  {
    label: "Math.min",
    kind: MonacoKind.Method,
    detail: "static int min(int a, int b)",
    documentation: "Returns the smaller of two int values.",
    insertText: "Math.min(${1:a}, ${2:b})",
    insertTextFormat: 2,
  },
  {
    label: "Math.sqrt",
    kind: MonacoKind.Method,
    detail: "static double sqrt(double a)",
    documentation:
      "Returns the correctly rounded positive square root of a double value.",
    insertText: "Math.sqrt(${1:a})",
    insertTextFormat: 2,
  },
  {
    label: "Math.pow",
    kind: MonacoKind.Method,
    detail: "static double pow(double a, double b)",
    documentation:
      "Returns the value of the first argument raised to the power of the second.",
    insertText: "Math.pow(${1:a}, ${2:b})",
    insertTextFormat: 2,
  },
  {
    label: "Math.floor",
    kind: MonacoKind.Method,
    detail: "static double floor(double a)",
    documentation:
      "Returns the largest double value that is less than or equal to the argument.",
    insertText: "Math.floor(${1:a})",
    insertTextFormat: 2,
  },
  {
    label: "Math.ceil",
    kind: MonacoKind.Method,
    detail: "static double ceil(double a)",
    documentation:
      "Returns the smallest double value that is greater than or equal to the argument.",
    insertText: "Math.ceil(${1:a})",
    insertTextFormat: 2,
  },
  {
    label: "Math.round",
    kind: MonacoKind.Method,
    detail: "static long round(double a)",
    documentation: "Returns the closest long to the argument.",
    insertText: "Math.round(${1:a})",
    insertTextFormat: 2,
  },
  {
    label: "Math.random",
    kind: MonacoKind.Method,
    detail: "static double random()",
    documentation:
      "Returns a double value with a positive sign, greater than or equal to 0.0 and less than 1.0.",
    insertText: "Math.random()",
  },
  {
    label: "Math.PI",
    kind: MonacoKind.Constant,
    detail: "static final double PI",
    documentation: "The double value that is closer than any other to pi.",
    insertText: "Math.PI",
  },
  {
    label: "Math.E",
    kind: MonacoKind.Constant,
    detail: "static final double E",
    documentation: "The double value that is closer than any other to e.",
    insertText: "Math.E",
  },

  // java.util.Collections
  {
    label: "Collections",
    kind: MonacoKind.Class,
    detail: "java.util.Collections",
    documentation:
      "Contains static methods that operate on or return collections.",
    insertText: "Collections",
  },
  {
    label: "Collections.sort",
    kind: MonacoKind.Method,
    detail: "void sort(List<T> list)",
    documentation: "Sorts the specified list into ascending order.",
    insertText: "Collections.sort(${1:list});",
    insertTextFormat: 2,
  },
  {
    label: "Collections.reverse",
    kind: MonacoKind.Method,
    detail: "void reverse(List<?> list)",
    documentation: "Reverses the order of elements in the specified list.",
    insertText: "Collections.reverse(${1:list});",
    insertTextFormat: 2,
  },
  {
    label: "Collections.max",
    kind: MonacoKind.Method,
    detail: "T max(Collection<? extends T> coll)",
    documentation: "Returns the maximum element of the given collection.",
    insertText: "Collections.max(${1:collection})",
    insertTextFormat: 2,
  },
  {
    label: "Collections.min",
    kind: MonacoKind.Method,
    detail: "T min(Collection<? extends T> coll)",
    documentation: "Returns the minimum element of the given collection.",
    insertText: "Collections.min(${1:collection})",
    insertTextFormat: 2,
  },
  {
    label: "Collections.frequency",
    kind: MonacoKind.Method,
    detail: "int frequency(Collection<?> c, Object o)",
    documentation:
      "Returns the number of elements in the collection equal to the specified object.",
    insertText: "Collections.frequency(${1:c}, ${2:o})",
    insertTextFormat: 2,
  },
  {
    label: "Collections.shuffle",
    kind: MonacoKind.Method,
    detail: "void shuffle(List<?> list)",
    documentation: "Randomly permutes the specified list.",
    insertText: "Collections.shuffle(${1:list});",
    insertTextFormat: 2,
  },

  // java.util.Objects
  {
    label: "Objects.requireNonNull",
    kind: MonacoKind.Method,
    detail: "static <T> T requireNonNull(T obj)",
    documentation: "Checks that the specified object reference is not null.",
    insertText: "Objects.requireNonNull(${1:obj})",
    insertTextFormat: 2,
  },
  {
    label: "Objects.equals",
    kind: MonacoKind.Method,
    detail: "static boolean equals(Object a, Object b)",
    documentation: "Returns true if the arguments are equal to each other.",
    insertText: "Objects.equals(${1:a}, ${2:b})",
    insertTextFormat: 2,
  },
  {
    label: "Objects.toString",
    kind: MonacoKind.Method,
    detail: "static String toString(Object o)",
    documentation:
      "Returns the result of calling toString for a non-null argument.",
    insertText: "Objects.toString(${1:o})",
    insertTextFormat: 2,
  },

  // StringBuilder
  {
    label: "StringBuilder",
    kind: MonacoKind.Class,
    detail: "java.lang.StringBuilder",
    documentation: "A mutable sequence of characters.",
    insertText: "StringBuilder sb = new StringBuilder();",
  },
  {
    label: "sb.append",
    kind: MonacoKind.Method,
    detail: "StringBuilder append(...)",
    documentation: "Appends the string representation of various arguments.",
    insertText: "sb.append(${1:value});",
    insertTextFormat: 2,
  },
  {
    label: "sb.insert",
    kind: MonacoKind.Method,
    detail: "StringBuilder insert(int offset, ...)",
    documentation: "Inserts the string representation of various arguments.",
    insertText: "sb.insert(${1:offset}, ${2:value});",
    insertTextFormat: 2,
  },
  {
    label: "sb.delete",
    kind: MonacoKind.Method,
    detail: "StringBuilder delete(int start, int end)",
    documentation: "Removes the characters in a substring of this sequence.",
    insertText: "sb.delete(${1:start}, ${2:end});",
    insertTextFormat: 2,
  },
  {
    label: "sb.toString",
    kind: MonacoKind.Method,
    detail: "String toString()",
    documentation: "Returns a string representing the data in this sequence.",
    insertText: "sb.toString()",
  },
  {
    label: "sb.length",
    kind: MonacoKind.Method,
    detail: "int length()",
    documentation: "Returns the length (character count).",
    insertText: "sb.length()",
  },
  {
    label: "sb.reverse",
    kind: MonacoKind.Method,
    detail: "StringBuilder reverse()",
    documentation:
      "Causes this character sequence to be replaced by the reverse of the sequence.",
    insertText: "sb.reverse();",
  },
  {
    label: "sb.setCharAt",
    kind: MonacoKind.Method,
    detail: "void setCharAt(int index, char ch)",
    documentation: "The character at the specified index is set to ch.",
    insertText: "sb.setCharAt(${1:index}, ${2:'c'});",
    insertTextFormat: 2,
  },

  // java.math.BigInteger
  {
    label: "BigInteger",
    kind: MonacoKind.Class,
    detail: "java.math.BigInteger",
    documentation: "Immutable arbitrary-precision integers.",
    insertText: 'BigInteger ${1:name} = new BigInteger("${2:0}");',
    insertTextFormat: 2,
  },
  {
    label: "bigInt.add",
    kind: MonacoKind.Method,
    detail: "BigInteger add(BigInteger val)",
    documentation: "Returns a BigInteger whose value is (this + val).",
    insertText: "bigInt.add(${1:val})",
    insertTextFormat: 2,
  },
  {
    label: "bigInt.multiply",
    kind: MonacoKind.Method,
    detail: "BigInteger multiply(BigInteger val)",
    documentation: "Returns a BigInteger whose value is (this * val).",
    insertText: "bigInt.multiply(${1:val})",
    insertTextFormat: 2,
  },
  {
    label: "bigInt.divide",
    kind: MonacoKind.Method,
    detail: "BigInteger divide(BigInteger val)",
    documentation: "Returns a BigInteger whose value is (this / val).",
    insertText: "bigInt.divide(${1:val})",
    insertTextFormat: 2,
  },
  {
    label: "bigInt.remainder",
    kind: MonacoKind.Method,
    detail: "BigInteger remainder(BigInteger val)",
    documentation: "Returns a BigInteger whose value is (this % val).",
    insertText: "bigInt.remainder(${1:val})",
    insertTextFormat: 2,
  },
  {
    label: "bigInt.pow",
    kind: MonacoKind.Method,
    detail: "BigInteger pow(int exponent)",
    documentation: "Returns a BigInteger whose value is (this ^ exponent).",
    insertText: "bigInt.pow(${1:exponent})",
    insertTextFormat: 2,
  },
  {
    label: "bigInt.compareTo",
    kind: MonacoKind.Method,
    detail: "int compareTo(BigInteger val)",
    documentation: "Compares this BigInteger with the specified BigInteger.",
    insertText: "bigInt.compareTo(${1:val})",
    insertTextFormat: 2,
  },

  // java.math.BigDecimal
  {
    label: "BigDecimal",
    kind: MonacoKind.Class,
    detail: "java.math.BigDecimal",
    documentation: "Immutable arbitrary-precision signed decimal numbers.",
    insertText: 'BigDecimal ${1:name} = new BigDecimal("${2:0}");',
    insertTextFormat: 2,
  },
  {
    label: "bigDec.add",
    kind: MonacoKind.Method,
    detail: "BigDecimal add(BigDecimal augend)",
    documentation: "Returns a BigDecimal whose value is (this + augend).",
    insertText: "bigDec.add(${1:augend})",
    insertTextFormat: 2,
  },
  {
    label: "bigDec.multiply",
    kind: MonacoKind.Method,
    detail: "BigDecimal multiply(BigDecimal multiplicand)",
    documentation: "Returns a BigDecimal whose value is (this x multiplicand).",
    insertText: "bigDec.multiply(${1:multiplicand})",
    insertTextFormat: 2,
  },
  {
    label: "bigDec.setScale",
    kind: MonacoKind.Method,
    detail: "BigDecimal setScale(int newScale)",
    documentation: "Returns a BigDecimal with the specified scale.",
    insertText: "bigDec.setScale(${1:newScale})",
    insertTextFormat: 2,
  },
  {
    label: "bigDec.stripTrailingZeros",
    kind: MonacoKind.Method,
    detail: "BigDecimal stripTrailingZeros()",
    documentation: "Returns a BigDecimal with trailing zeros removed.",
    insertText: "bigDec.stripTrailingZeros()",
  },
  {
    label: "bigDec.compareTo",
    kind: MonacoKind.Method,
    detail: "int compareTo(BigDecimal val)",
    documentation: "Compares this BigDecimal with the specified BigDecimal.",
    insertText: "bigDec.compareTo(${1:val})",
    insertTextFormat: 2,
  },

  // java.time classes
  {
    label: "LocalDateTime",
    kind: MonacoKind.Class,
    detail: "java.time.LocalDateTime",
    documentation: "A date-time without a time-zone.",
    insertText: "LocalDateTime ${1:name} = LocalDateTime.now();",
    insertTextFormat: 2,
  },
  {
    label: "LocalDate",
    kind: MonacoKind.Class,
    detail: "java.time.LocalDate",
    documentation: "A date without a time-zone.",
    insertText: "LocalDate ${1:name} = LocalDate.now();",
    insertTextFormat: 2,
  },
  {
    label: "LocalTime",
    kind: MonacoKind.Class,
    detail: "java.time.LocalTime",
    documentation: "A time without a time-zone.",
    insertText: "LocalTime ${1:name} = LocalTime.now();",
    insertTextFormat: 2,
  },
  {
    label: "Instant",
    kind: MonacoKind.Class,
    detail: "java.time.Instant",
    documentation: "An instantaneous point on the time-line.",
    insertText: "Instant ${1:name} = Instant.now();",
    insertTextFormat: 2,
  },
  {
    label: "Duration",
    kind: MonacoKind.Class,
    detail: "java.time.Duration",
    documentation: "A time-based amount of time.",
    insertText: "Duration ${1:name} = Duration.ofSeconds(${2:seconds});",
    insertTextFormat: 2,
  },
  {
    label: "Period",
    kind: MonacoKind.Class,
    detail: "java.time.Period",
    documentation: "A date-based amount of time.",
    insertText: "Period ${1:name} = Period.ofDays(${2:days});",
    insertTextFormat: 2,
  },
  {
    label: "DateTimeFormatter",
    kind: MonacoKind.Class,
    detail: "java.time.format.DateTimeFormatter",
    documentation: "Formatter for printing and parsing date-time objects.",
    insertText:
      'DateTimeFormatter formatter = DateTimeFormatter.ofPattern("${1:yyyy-MM-dd HH:mm:ss}");',
    insertTextFormat: 2,
  },
  {
    label: "LocalDateTime.now",
    kind: MonacoKind.Method,
    detail: "static LocalDateTime now()",
    documentation: "Obtains the current date-time from the system clock.",
    insertText: "LocalDateTime.now()",
  },
  {
    label: "LocalDate.now",
    kind: MonacoKind.Method,
    detail: "static LocalDate now()",
    documentation: "Obtains the current date from the system clock.",
    insertText: "LocalDate.now()",
  },
  {
    label: "LocalTime.now",
    kind: MonacoKind.Method,
    detail: "static LocalTime now()",
    documentation: "Obtains the current time from the system clock.",
    insertText: "LocalTime.now()",
  },
  {
    label: "Instant.now",
    kind: MonacoKind.Method,
    detail: "static Instant now()",
    documentation: "Obtains the current instant from the system clock.",
    insertText: "Instant.now()",
  },
  {
    label: "ldt.parse",
    kind: MonacoKind.Method,
    detail: "static LocalDateTime parse(CharSequence text)",
    documentation: "Obtains an instance of LocalDateTime from a text string.",
    insertText: 'LocalDateTime.parse("${1:text}")',
    insertTextFormat: 2,
  },

  // Control flow snippets
  {
    label: "if-else",
    kind: MonacoKind.Snippet,
    detail: "if-else statement",
    documentation: "Inserts an if-else block.",
    insertText:
      "if (${1:condition}) {\n\t${2:// code}\n} else {\n\t${3:// code}\n}",
    insertTextFormat: 2,
  },
  {
    label: "for loop",
    kind: MonacoKind.Snippet,
    detail: "for loop",
    documentation: "Inserts a standard for loop.",
    insertText:
      "for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t${3:// code}\n}",
    insertTextFormat: 2,
  },
  {
    label: "for-each loop",
    kind: MonacoKind.Snippet,
    detail: "enhanced for loop",
    documentation: "Inserts an enhanced for loop (for-each).",
    insertText:
      "for (${1:int} ${2:item} : ${3:collection}) {\n\t${4:// code}\n}",
    insertTextFormat: 2,
  },
  {
    label: "while loop",
    kind: MonacoKind.Snippet,
    detail: "while loop",
    documentation: "Inserts a while loop.",
    insertText: "while (${1:condition}) {\n\t${2:// code}\n}",
    insertTextFormat: 2,
  },
  {
    label: "do-while loop",
    kind: MonacoKind.Snippet,
    detail: "do-while loop",
    documentation: "Inserts a do-while loop.",
    insertText: "do {\n\t${1:// code}\n} while (${2:condition});",
    insertTextFormat: 2,
  },
  {
    label: "try-catch",
    kind: MonacoKind.Snippet,
    detail: "try-catch block",
    documentation: "Inserts a try-catch block.",
    insertText:
      "try {\n\t${1:// code}\n} catch (${2:Exception} ${3:e}) {\n\t${4:// handle exception}\n}",
    insertTextFormat: 2,
  },
  {
    label: "try-catch-finally",
    kind: MonacoKind.Snippet,
    detail: "try-catch-finally block",
    documentation: "Inserts a try-catch-finally block.",
    insertText:
      "try {\n\t${1:// code}\n} catch (${2:Exception} ${3:e}) {\n\t${4:// handle exception}\n} finally {\n\t${5:// cleanup}\n}",
    insertTextFormat: 2,
  },
  {
    label: "switch",
    kind: MonacoKind.Snippet,
    detail: "switch statement",
    documentation: "Inserts a switch statement.",
    insertText:
      "switch (${1:key}) {\n\tcase ${2:value1}:\n\t\t${3:// code}\n\t\tbreak;\n\tcase ${4:value2}:\n\t\t${5:// code}\n\t\tbreak;\n\tdefault:\n\t\t${6:// default code}\n}",
    insertTextFormat: 2,
  },
  {
    label: "switch expression",
    kind: MonacoKind.Snippet,
    detail: "switch expression (Java 14+)",
    documentation: "Inserts a switch expression.",
    insertText:
      'String result = switch (${1:key}) {\n\tcase ${2:value1} -> "${3:result1}";\n\tcase ${4:value2} -> "${5:result2}";\n\tdefault -> "${6:default}";\n};',
    insertTextFormat: 2,
  },
  {
    label: "if (condition)",
    kind: MonacoKind.Snippet,
    detail: "if statement",
    documentation: "Inserts an if statement.",
    insertText: "if (${1:condition}) {\n\t${2:// code}\n}",
    insertTextFormat: 2,
  },

  // Class/interface snippets
  {
    label: "public class",
    kind: MonacoKind.Snippet,
    detail: "public class template",
    documentation: "Inserts a public class template.",
    insertText:
      "public class ${1:ClassName} {\n\tpublic ${1:ClassName}() {\n\t\t${2:// constructor}\n\t}\n}",
    insertTextFormat: 2,
  },
  {
    label: "public static void main",
    kind: MonacoKind.Snippet,
    detail: "main method",
    documentation: "Inserts a main method.",
    insertText: "public static void main(String[] args) {\n\t${1:// code}\n}",
    insertTextFormat: 2,
  },
  {
    label: "public method",
    kind: MonacoKind.Snippet,
    detail: "public method template",
    documentation: "Inserts a public method template.",
    insertText:
      "public ${1:void} ${2:methodName}(${3:params}) {\n\t${4:// code}\n}",
    insertTextFormat: 2,
  },
  {
    label: "private method",
    kind: MonacoKind.Snippet,
    detail: "private method template",
    documentation: "Inserts a private method template.",
    insertText:
      "private ${1:void} ${2:methodName}(${3:params}) {\n\t${4:// code}\n}",
    insertTextFormat: 2,
  },
  {
    label: "getter",
    kind: MonacoKind.Snippet,
    detail: "getter method",
    documentation: "Inserts a getter method.",
    insertText:
      "public ${1:Type} get${2:Property}() {\n\treturn ${2:property};\n}",
    insertTextFormat: 2,
  },
  {
    label: "setter",
    kind: MonacoKind.Snippet,
    detail: "setter method",
    documentation: "Inserts a setter method.",
    insertText:
      "public void set${2:Property}(${1:Type} ${2:property}) {\n\tthis.${2:property} = ${2:property};\n}",
    insertTextFormat: 2,
  },
  {
    label: "toString",
    kind: MonacoKind.Snippet,
    detail: "toString method",
    documentation: "Inserts a toString method.",
    insertText:
      '@Override\npublic String toString() {\n\treturn "${1:ClassName}{" +\n\t\t"${2:field1=" + field1 +\n\t\t${3:", field2=" + field2} +\n\t\t\'}\';\n}',
    insertTextFormat: 2,
  },
  {
    label: "equals and hashCode",
    kind: MonacoKind.Snippet,
    detail: "equals and hashCode methods",
    documentation: "Inserts equals and hashCode methods.",
    insertText:
      "@Override\npublic boolean equals(Object obj) {\n\tif (this == obj) return true;\n\tif (obj == null || getClass() != obj.getClass()) return false;\n\t${1:ClassName} other = (${1:ClassName}) obj;\n\treturn ${2:Objects.equals(field, other.field)};\n}\n\n@Override\npublic int hashCode() {\n\treturn Objects.hash(${3:field});\n}",
    insertTextFormat: 2,
  },
  {
    label: "interface",
    kind: MonacoKind.Snippet,
    detail: "interface template",
    documentation: "Inserts an interface template.",
    insertText:
      "public interface ${1:InterfaceName} {\n\t${2:// abstract methods}\n}",
    insertTextFormat: 2,
  },
  {
    label: "enum",
    kind: MonacoKind.Snippet,
    detail: "enum template",
    documentation: "Inserts an enum template.",
    insertText:
      "public enum ${1:EnumName} {\n\t${2:VALUE1},\n\t${3:VALUE2};\n}",
    insertTextFormat: 2,
  },
  {
    label: "record",
    kind: MonacoKind.Snippet,
    detail: "record (Java 16+)",
    documentation: "Inserts a record template.",
    insertText:
      "public record ${1:RecordName}(${2:int field1}, ${3:String field2}) {\n}",
    insertTextFormat: 2,
  },
  {
    label: "abstract class",
    kind: MonacoKind.Snippet,
    detail: "abstract class template",
    documentation: "Inserts an abstract class template.",
    insertText:
      "public abstract class ${1:ClassName} {\n\t${2:// fields and methods}\n}",
    insertTextFormat: 2,
  },
  {
    label: "lambda",
    kind: MonacoKind.Snippet,
    detail: "lambda expression",
    documentation: "Inserts a lambda expression.",
    insertText: "(${1:params}) -> ${2:// expression}",
    insertTextFormat: 2,
  },
  {
    label: "method reference",
    kind: MonacoKind.Snippet,
    detail: "method reference",
    documentation: "Inserts a method reference.",
    insertText: "${1:object}::${2:method}",
    insertTextFormat: 2,
  },
  {
    label: "Stream.forEach",
    kind: MonacoKind.Snippet,
    detail: "Stream forEach",
    documentation: "Performs an action for each element of the stream.",
    insertText: "${1:stream}.forEach(${2:item} -> {\n\t${3:// code}\n});",
    insertTextFormat: 2,
  },
  {
    label: "Stream.filter",
    kind: MonacoKind.Snippet,
    detail: "Stream filter",
    documentation:
      "Returns a stream consisting of elements matching the given predicate.",
    insertText:
      "${1:stream}.filter(${2:item} -> ${3:condition})\n\t.collect(Collectors.toList())",
    insertTextFormat: 2,
  },
  {
    label: "Stream.map",
    kind: MonacoKind.Snippet,
    detail: "Stream map",
    documentation:
      "Returns a stream consisting of results of applying the given function.",
    insertText:
      "${1:stream}.map(${2:item} -> ${3:result})\n\t.collect(Collectors.toList())",
    insertTextFormat: 2,
  },
  {
    label: "Stream.collect",
    kind: MonacoKind.Snippet,
    detail: "Stream collect",
    documentation: "Collects stream elements into a collection.",
    insertText: ".collect(Collectors.toList())",
    insertTextFormat: 2,
  },
  {
    label: "Collectors.toList",
    kind: MonacoKind.Method,
    detail: "static <T> List<T> toList()",
    documentation: "Returns a Collector that accumulates elements into a List.",
    insertText: "Collectors.toList()",
  },
  {
    label: "Collectors.toSet",
    kind: MonacoKind.Method,
    detail: "static <T> Set<T> toSet()",
    documentation: "Returns a Collector that accumulates elements into a Set.",
    insertText: "Collectors.toSet()",
  },
  {
    label: "Collectors.joining",
    kind: MonacoKind.Method,
    detail:
      "static Collector<CharSequence,?,String> joining(CharSequence delimiter)",
    documentation: "Concatenates input strings with the specified delimiter.",
    insertText: 'Collectors.joining("${1:, ")',
    insertTextFormat: 2,
  },
  {
    label: "Stream.reduce",
    kind: MonacoKind.Method,
    detail: "Optional<T> reduce(BinaryOperator<T> accumulator)",
    documentation: "Performs a reduction on the elements of the stream.",
    insertText:
      "${1:stream}.reduce(${2:(a, b) -> a + b}).orElse(${3:defaultValue})",
    insertTextFormat: 2,
  },
  {
    label: "Stream.count",
    kind: MonacoKind.Method,
    detail: "long count()",
    documentation: "Returns the count of elements in the stream.",
    insertText: "${1:stream}.count()",
    insertTextFormat: 2,
  },
  {
    label: "Stream.distinct",
    kind: MonacoKind.Method,
    detail: "Stream distinct()",
    documentation: "Returns a stream with distinct elements.",
    insertText: "${1:stream}.distinct()",
    insertTextFormat: 2,
  },
  {
    label: "Stream.sorted",
    kind: MonacoKind.Method,
    detail: "Stream sorted()",
    documentation:
      "Returns a stream with elements sorted according to natural order.",
    insertText: "${1:stream}.sorted()",
    insertTextFormat: 2,
  },
  {
    label: "Stream.limit",
    kind: MonacoKind.Method,
    detail: "Stream limit(long maxSize)",
    documentation: "Returns a stream truncated to be no longer than maxSize.",
    insertText: "${1:stream}.limit(${2:maxSize})",
    insertTextFormat: 2,
  },
  {
    label: "Stream.skip",
    kind: MonacoKind.Method,
    detail: "Stream skip(long n)",
    documentation: "Skips the first n elements.",
    insertText: "${1:stream}.skip(${2:n})",
    insertTextFormat: 2,
  },
  {
    label: "Optional.ofNullable",
    kind: MonacoKind.Method,
    detail: "static <T> Optional<T> ofNullable(T value)",
    documentation:
      "Returns an Optional describing the given value, or empty if null.",
    insertText: "Optional.ofNullable(${1:value})",
    insertTextFormat: 2,
  },
  {
    label: "optional.orElse",
    kind: MonacoKind.Method,
    detail: "T orElse(T other)",
    documentation: "Returns the value if present, otherwise returns other.",
    insertText: "optional.orElse(${1:defaultValue})",
    insertTextFormat: 2,
  },
  {
    label: "optional.orElseGet",
    kind: MonacoKind.Method,
    detail: "T orElseGet(Supplier<? extends T> supplier)",
    documentation:
      "Returns the value if present, otherwise invokes the supplier.",
    insertText: "optional.orElseGet(() -> ${1:defaultValue})",
    insertTextFormat: 2,
  },
  {
    label: "optional.ifPresent",
    kind: MonacoKind.Method,
    detail: "void ifPresent(Consumer<? super T> action)",
    documentation: "Executes the action if a value is present.",
    insertText: "optional.ifPresent(${1:value} -> {\n\t${2:// code}\n});",
    insertTextFormat: 2,
  },
  {
    label: "optional.map",
    kind: MonacoKind.Method,
    detail: "<U> Optional<U> map(Function<? super T,? extends U> mapper)",
    documentation: "Applies the mapping function if a value is present.",
    insertText: "optional.map(${1:value} -> ${2:result})",
    insertTextFormat: 2,
  },
  {
    label: "optional.isPresent",
    kind: MonacoKind.Method,
    detail: "boolean isPresent()",
    documentation: "Returns true if a value is present.",
    insertText: "optional.isPresent()",
  },

  // println shortcuts
  {
    label: "println",
    kind: MonacoKind.Snippet,
    detail: "System.out.println()",
    documentation: "Prints a line to console.",
    insertText: "System.out.println(${1:value});",
    insertTextFormat: 2,
  },
  {
    label: "print",
    kind: MonacoKind.Snippet,
    detail: "System.out.print()",
    documentation: "Prints without newline.",
    insertText: "System.out.print(${1:value});",
    insertTextFormat: 2,
  },
  {
    label: "printf",
    kind: MonacoKind.Snippet,
    detail: "System.out.printf()",
    documentation: "Prints a formatted string.",
    insertText: 'System.out.printf("${1:format}", ${2:args});',
    insertTextFormat: 2,
  },

  // import statements
  {
    label: "import java.util.*",
    kind: MonacoKind.Snippet,
    detail: "import java.util.*",
    documentation: "Imports java.util package.",
    insertText: "import java.util.*;",
  },
  {
    label: "import java.io.*",
    kind: MonacoKind.Snippet,
    detail: "import java.io.*",
    documentation: "Imports java.io package.",
    insertText: "import java.io.*;",
  },
  {
    label: "import java.math.*",
    kind: MonacoKind.Snippet,
    detail: "import java.math.*",
    documentation: "Imports java.math package.",
    insertText: "import java.math.*;",
  },
  {
    label: "import java.time.*",
    kind: MonacoKind.Snippet,
    detail: "import java.time.*",
    documentation: "Imports java.time package.",
    insertText: "import java.time.*;",
  },
  {
    label: "import java.util.stream.*",
    kind: MonacoKind.Snippet,
    detail: "import java.util.stream.*",
    documentation: "Imports java.util.stream package.",
    insertText: "import java.util.stream.*;",
  },

  // Arrays
  {
    label: "int[] array",
    kind: MonacoKind.Snippet,
    detail: "int array declaration and initialization",
    documentation: "Creates an int array with specified size.",
    insertText: "int[] ${1:array} = new int[${2:size}];",
    insertTextFormat: 2,
  },
  {
    label: "String[] array",
    kind: MonacoKind.Snippet,
    detail: "String array declaration and initialization",
    documentation: "Creates a String array with specified size.",
    insertText: "String[] ${1:array} = new String[${2:size}];",
    insertTextFormat: 2,
  },
  {
    label: "Arrays.toString(array)",
    kind: MonacoKind.Snippet,
    detail: "Print array as string",
    documentation: "Prints array contents using Arrays.toString().",
    insertText: "System.out.println(Arrays.toString(${1:array}));",
    insertTextFormat: 2,
  },
];
