import { LspCompletionItem, MonacoKind } from './types';

export const JAVASCRIPT_API_COMPLETIONS: LspCompletionItem[] = [
  // Built-in types
  { label: 'string', kind: MonacoKind.Keyword, detail: 'string', documentation: 'String primitive type.', insertText: 'string' },
  { label: 'number', kind: MonacoKind.Keyword, detail: 'number', documentation: 'Number primitive type.', insertText: 'number' },
  { label: 'boolean', kind: MonacoKind.Keyword, detail: 'boolean', documentation: 'Boolean primitive type.', insertText: 'boolean' },
  { label: 'undefined', kind: MonacoKind.Keyword, detail: 'undefined', documentation: 'Undefined type.', insertText: 'undefined' },
  { label: 'null', kind: MonacoKind.Keyword, detail: 'null', documentation: 'Null value.', insertText: 'null' },
  { label: 'symbol', kind: MonacoKind.Keyword, detail: 'symbol', documentation: 'Symbol primitive type.', insertText: 'symbol' },
  { label: 'bigint', kind: MonacoKind.Keyword, detail: 'bigint', documentation: 'Big integer type.', insertText: 'bigint' },
  { label: 'object', kind: MonacoKind.Keyword, detail: 'object', documentation: 'Object type.', insertText: 'object' },

  // Control flow snippets
  { label: 'if statement', kind: MonacoKind.Snippet, detail: 'if statement', documentation: 'Creates an if statement.', insertText: 'if (${1:condition}) {\n    ${2:// code}\n}', insertTextFormat: 2 },
  { label: 'if-else', kind: MonacoKind.Snippet, detail: 'if-else statement', documentation: 'Creates an if-else statement.', insertText: 'if (${1:condition}) {\n    ${2:// code}\n} else {\n    ${3:// code}\n}', insertTextFormat: 2 },
  { label: 'else-if chain', kind: MonacoKind.Snippet, detail: 'else-if chain', documentation: 'Creates else-if chain.', insertText: 'if (${1:condition}) {\n    ${2:// code}\n} else if (${3:condition}) {\n    ${4:// code}\n} else {\n    ${5:// code}\n}', insertTextFormat: 2 },
  { label: 'for loop', kind: MonacoKind.Snippet, detail: 'for loop', documentation: 'Creates a for loop.', insertText: 'for (let ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n    ${3:// code}\n}', insertTextFormat: 2 },
  { label: 'for-of loop', kind: MonacoKind.Snippet, detail: 'for-of loop', documentation: 'Creates a for-of loop.', insertText: 'for (const ${1:item} of ${2:array}) {\n    ${3:// code}\n}', insertTextFormat: 2 },
  { label: 'for-in loop', kind: MonacoKind.Snippet, detail: 'for-in loop', documentation: 'Creates a for-in loop.', insertText: 'for (const ${1:key} in ${2:object}) {\n    ${3:// code}\n}', insertTextFormat: 2 },
  { label: 'while loop', kind: MonacoKind.Snippet, detail: 'while loop', documentation: 'Creates a while loop.', insertText: 'while (${1:condition}) {\n    ${2:// code}\n}', insertTextFormat: 2 },
  { label: 'do-while loop', kind: MonacoKind.Snippet, detail: 'do-while loop', documentation: 'Creates a do-while loop.', insertText: 'do {\n    ${1:// code}\n} while (${2:condition});', insertTextFormat: 2 },
  { label: 'switch', kind: MonacoKind.Snippet, detail: 'switch statement', documentation: 'Creates a switch statement.', insertText: 'switch (${1:expr}) {\n    case ${2:val1}:\n        ${3:// code}\n        break;\n    case ${4:val2}:\n        ${5:// code}\n        break;\n    default:\n        ${6:// code}\n}', insertTextFormat: 2 },
  { label: 'try-catch', kind: MonacoKind.Snippet, detail: 'try-catch block', documentation: 'Creates a try-catch block.', insertText: 'try {\n    ${1:// code}\n} catch (${2:error}) {\n    ${3:// handle error}\n}', insertTextFormat: 2 },
  { label: 'try-catch-finally', kind: MonacoKind.Snippet, detail: 'try-catch-finally', documentation: 'Creates a try-catch-finally block.', insertText: 'try {\n    ${1:// code}\n} catch (${2:error}) {\n    ${3:// handle error}\n} finally {\n    ${4:// cleanup}\n}', insertTextFormat: 2 },
  { label: 'throw', kind: MonacoKind.Snippet, detail: 'throw statement', documentation: 'Throws an error.', insertText: 'throw new Error("${1:message}")', insertTextFormat: 2 },

  // Functions
  { label: 'function declaration', kind: MonacoKind.Snippet, detail: 'function declaration', documentation: 'Creates a function declaration.', insertText: 'function ${1:name}(${2:args}) {\n    ${3:// code}\n}', insertTextFormat: 2 },
  { label: 'arrow function', kind: MonacoKind.Snippet, detail: 'arrow function', documentation: 'Creates an arrow function.', insertText: '(${1:args}) => {\n    ${2:// code}\n}', insertTextFormat: 2 },
  { label: 'arrow function expression', kind: MonacoKind.Snippet, detail: 'arrow function expression', documentation: 'Creates an arrow function with implicit return.', insertText: '(${1:args}) => ${2:expr}', insertTextFormat: 2 },
  { label: 'async function', kind: MonacoKind.Snippet, detail: 'async function', documentation: 'Creates an async function.', insertText: 'async function ${1:name}(${2:args}) {\n    ${3:// code\n    await ${4:promise};\n}', insertTextFormat: 2 },
  { label: 'async arrow function', kind: MonacoKind.Snippet, detail: 'async arrow function', documentation: 'Creates an async arrow function.', insertText: 'async (${1:args}) => {\n    ${2:// code\n    await ${3:promise};\n}', insertTextFormat: 2 },
  { label: 'IIFE', kind: MonacoKind.Snippet, detail: 'Immediately Invoked Function Expression', documentation: 'Creates an IIFE.', insertText: '((${1:args}) => {\n    ${2:// code\n})(${3:args});', insertTextFormat: 2 },
  { label: 'generator function', kind: MonacoKind.Snippet, detail: 'generator function', documentation: 'Creates a generator function.', insertText: 'function* ${1:name}(${2:args}) {\n    ${3:// code\n    yield ${4:value};\n}', insertTextFormat: 2 },
  { label: 'callback pattern', kind: MonacoKind.Snippet, detail: 'callback pattern', documentation: 'Creates a callback pattern.', insertText: '(err, ${1:result}) => {\n    ${2:// code\n}', insertTextFormat: 2 },
  { label: 'Promise-based function', kind: MonacoKind.Snippet, detail: 'Promise-returning function', documentation: 'Creates a function returning Promise.', insertText: 'function ${1:name}(${2:args}) {\n    return new Promise((resolve, reject) => {\n        ${3:// code\n    });\n}', insertTextFormat: 2 },

  // Async/Await
  { label: 'await', kind: MonacoKind.Snippet, detail: 'await expression', documentation: 'Awaits a Promise.', insertText: 'await ${1:promise}', insertTextFormat: 2 },
  { label: 'Promise.all', kind: MonacoKind.Function, detail: 'Promise.all(promises)', documentation: 'Waits for all promises.', insertText: 'Promise.all(${1:promises})', insertTextFormat: 2 },
  { label: 'Promise.race', kind: MonacoKind.Function, detail: 'Promise.race(promises)', documentation: 'Resolves/rejects with first settled.', insertText: 'Promise.race(${1:promises})', insertTextFormat: 2 },
  { label: 'Promise.allSettled', kind: MonacoKind.Function, detail: 'Promise.allSettled(promises)', documentation: 'Waits for all promises to settle.', insertText: 'Promise.allSettled(${1:promises})', insertTextFormat: 2 },
  { label: 'Promise.any', kind: MonacoKind.Function, detail: 'Promise.any(promises)', documentation: 'Resolves with first fulfilled.', insertText: 'Promise.any(${1:promises})', insertTextFormat: 2 },
  { label: 'Promise.resolve', kind: MonacoKind.Function, detail: 'Promise.resolve(value)', documentation: 'Creates resolved Promise.', insertText: 'Promise.resolve(${1:value})', insertTextFormat: 2 },
  { label: 'Promise.reject', kind: MonacoKind.Function, detail: 'Promise.reject(error)', documentation: 'Creates rejected Promise.', insertText: 'Promise.reject(${1:error})', insertTextFormat: 2 },
  { label: 'new Promise', kind: MonacoKind.Snippet, detail: 'new Promise', documentation: 'Creates a new Promise.', insertText: 'new Promise((resolve, reject) => {\n    ${1:// code\n})', insertTextFormat: 2 },
  { label: 'then catch', kind: MonacoKind.Snippet, detail: 'then/catch chain', documentation: 'Chains Promise then/catch.', insertText: '.then((${1:result}) => {\n    ${2:// handle result\n}).catch((${3:error}) => {\n    ${4:// handle error\n});', insertTextFormat: 2 },
  { label: '.then', kind: MonacoKind.Snippet, detail: '.then()', documentation: 'Attaches success handler.', insertText: '.then((${1:result}) => {\n    ${2:// code\n})', insertTextFormat: 2 },
  { label: '.catch', kind: MonacoKind.Snippet, detail: '.catch()', documentation: 'Attaches error handler.', insertText: '.catch((${1:error}) => {\n    ${2:// code\n})', insertTextFormat: 2 },
  { label: '.finally', kind: MonacoKind.Snippet, detail: '.finally()', documentation: 'Attaches cleanup handler.', insertText: '.finally(() => {\n    ${1:// cleanup\n})', insertTextFormat: 2 },

  // Array methods
  { label: 'array.map', kind: MonacoKind.Method, detail: 'map(callback): array', documentation: 'Transforms each element.', insertText: '${1:array}.map((${2:item}) => ${3:item})', insertTextFormat: 2 },
  { label: 'array.filter', kind: MonacoKind.Method, detail: 'filter(callback): array', documentation: 'Filters elements.', insertText: '${1:array}.filter((${2:item}) => ${3:condition})', insertTextFormat: 2 },
  { label: 'array.reduce', kind: MonacoKind.Method, detail: 'reduce(callback, init): value', documentation: 'Reduces array to single value.', insertText: '${1:array}.reduce((${2:acc}, ${3:item}) => ${4:acc + item}, ${5:0})', insertTextFormat: 2 },
  { label: 'array.forEach', kind: MonacoKind.Method, detail: 'forEach(callback): void', documentation: 'Iterates over elements.', insertText: '${1:array}.forEach((${2:item}) => {\n    ${3:// code\n})', insertTextFormat: 2 },
  { label: 'array.find', kind: MonacoKind.Method, detail: 'find(callback): element | undefined', documentation: 'Finds first matching element.', insertText: '${1:array}.find((${2:item}) => ${3:condition})', insertTextFormat: 2 },
  { label: 'array.findIndex', kind: MonacoKind.Method, detail: 'findIndex(callback): number', documentation: 'Finds index of first match.', insertText: '${1:array}.findIndex((${2:item}) => ${3:condition})', insertTextFormat: 2 },
  { label: 'array.some', kind: MonacoKind.Method, detail: 'some(callback): boolean', documentation: 'Checks if any element matches.', insertText: '${1:array}.some((${2:item}) => ${3:condition})', insertTextFormat: 2 },
  { label: 'array.every', kind: MonacoKind.Method, detail: 'every(callback): boolean', documentation: 'Checks if all elements match.', insertText: '${1:array}.every((${2:item}) => ${3:condition})', insertTextFormat: 2 },
  { label: 'array.includes', kind: MonacoKind.Method, detail: 'includes(searchElement): boolean', documentation: 'Checks if array includes element.', insertText: '${1:array}.includes(${2:value})', insertTextFormat: 2 },
  { label: 'array.indexOf', kind: MonacoKind.Method, detail: 'indexOf(searchElement): number', documentation: 'Returns index of element.', insertText: '${1:array}.indexOf(${2:value})', insertTextFormat: 2 },
  { label: 'array.slice', kind: MonacoKind.Method, detail: 'slice(start?, end?): array', documentation: 'Returns a shallow copy.', insertText: '${1:array}.slice(${2:start}, ${3:end})', insertTextFormat: 2 },
  { label: 'array.splice', kind: MonacoKind.Method, detail: 'splice(start, deleteCount?): array', documentation: 'Adds/removes elements.', insertText: '${1:array}.splice(${2:index}, ${3:deleteCount})', insertTextFormat: 2 },
  { label: 'array.concat', kind: MonacoKind.Method, detail: 'concat(...items): array', documentation: 'Concatenates arrays.', insertText: '${1:array}.concat(${2:otherArray})', insertTextFormat: 2 },
  { label: 'array.join', kind: MonacoKind.Method, detail: 'join(separator?): string', documentation: 'Joins elements into string.', insertText: '${1:array}.join("${2:,}")', insertTextFormat: 2 },
  { label: 'array.sort', kind: MonacoKind.Method, detail: 'sort(compareFn?): array', documentation: 'Sorts array in place.', insertText: '${1:array}.sort((${2:a}, ${3:b}) => ${4:a - b})', insertTextFormat: 2 },
  { label: 'array.reverse', kind: MonacoKind.Method, detail: 'reverse(): array', documentation: 'Reverses array in place.', insertText: '${1:array}.reverse()' },
  { label: 'array.flat', kind: MonacoKind.Method, detail: 'flat(depth?): array', documentation: 'Flattens nested arrays.', insertText: '${1:array}.flat(${2:1})', insertTextFormat: 2 },
  { label: 'array.flatMap', kind: MonacoKind.Method, detail: 'flatMap(callback): array', documentation: 'Maps then flattens.', insertText: '${1:array}.flatMap((${2:item}) => ${3:item})', insertTextFormat: 2 },
  { label: 'array.fill', kind: MonacoKind.Method, detail: 'fill(value, start?, end?): array', documentation: 'Fills array with value.', insertText: '${1:array}.fill(${2:value})', insertTextFormat: 2 },
  { label: 'array.copyWithin', kind: MonacoKind.Method, detail: 'copyWithin(target, start?, end?): array', documentation: 'Copies within array.', insertText: '${1:array}.copyWithin(${2:target}, ${3:start})', insertTextFormat: 2 },
  { label: 'array.entries', kind: MonacoKind.Method, detail: 'entries(): iterator', documentation: 'Returns key-value iterator.', insertText: '${1:array}.entries()' },
  { label: 'array.keys', kind: MonacoKind.Method, detail: 'keys(): iterator', documentation: 'Returns key iterator.', insertText: '${1:array}.keys()' },
  { label: 'array.values', kind: MonacoKind.Method, detail: 'values(): iterator', documentation: 'Returns value iterator.', insertText: '${1:array}.values()' },
  { label: 'array.at', kind: MonacoKind.Method, detail: 'at(index): element', documentation: 'Gets element at index (negative indexing).', insertText: '${1:array}.at(${2:index})', insertTextFormat: 2 },
  { label: 'Array.isArray', kind: MonacoKind.Function, detail: 'Array.isArray(value): boolean', documentation: 'Checks if value is array.', insertText: 'Array.isArray(${1:value})', insertTextFormat: 2 },
  { label: 'Array.from', kind: MonacoKind.Function, detail: 'Array.from(arrayLike): array', documentation: 'Creates array from array-like.', insertText: 'Array.from(${1:arrayLike})', insertTextFormat: 2 },
  { label: 'Array.of', kind: MonacoKind.Function, detail: 'Array.of(...elements): array', documentation: 'Creates array from arguments.', insertText: 'Array.of(${1:element})', insertTextFormat: 2 },

  // String methods
  { label: 'str.length', kind: MonacoKind.Property, detail: 'string.length', documentation: 'Returns string length.', insertText: '${1:str}.length' },
  { label: 'str.charAt', kind: MonacoKind.Method, detail: 'charAt(index): string', documentation: 'Returns character at index.', insertText: '${1:str}.charAt(${2:index})', insertTextFormat: 2 },
  { label: 'str.includes', kind: MonacoKind.Method, detail: 'includes(searchString): boolean', documentation: 'Checks if string includes substring.', insertText: '${1:str}.includes("${2:substring}")', insertTextFormat: 2 },
  { label: 'str.indexOf', kind: MonacoKind.Method, detail: 'indexOf(searchString): number', documentation: 'Returns first index of substring.', insertText: '${1:str}.indexOf("${2:substring}")', insertTextFormat: 2 },
  { label: 'str.lastIndexOf', kind: MonacoKind.Method, detail: 'lastIndexOf(searchString): number', documentation: 'Returns last index of substring.', insertText: '${1:str}.lastIndexOf("${2:substring}")', insertTextFormat: 2 },
  { label: 'str.match', kind: MonacoKind.Method, detail: 'match(regexp): array | null', documentation: 'Matches against regex.', insertText: '${1:str}.match(/${2:pattern}/)', insertTextFormat: 2 },
  { label: 'str.replace', kind: MonacoKind.Method, detail: 'replace(pattern, replacement): string', documentation: 'Replaces first/all matches.', insertText: '${1:str}.replace(/${2:pattern}/, "${3:replacement}")', insertTextFormat: 2 },
  { label: 'str.replaceAll', kind: MonacoKind.Method, detail: 'replaceAll(pattern, replacement): string', documentation: 'Replaces all matches.', insertText: '${1:str}.replaceAll(/${2:pattern}/g, "${3:replacement}")', insertTextFormat: 2 },
  { label: 'str.slice', kind: MonacoKind.Method, detail: 'slice(start?, end?): string', documentation: 'Extracts portion.', insertText: '${1:str}.slice(${2:start}, ${3:end})', insertTextFormat: 2 },
  { label: 'str.split', kind: MonacoKind.Method, detail: 'split(separator): array', documentation: 'Splits string.', insertText: '${1:str}.split("${2:separator}")', insertTextFormat: 2 },
  { label: 'str.startsWith', kind: MonacoKind.Method, detail: 'startsWith(searchString): boolean', documentation: 'Checks if starts with.', insertText: '${1:str}.startsWith("${2:prefix}")', insertTextFormat: 2 },
  { label: 'str.endsWith', kind: MonacoKind.Method, detail: 'endsWith(searchString): boolean', documentation: 'Checks if ends with.', insertText: '${1:str}.endsWith("${2:suffix}")', insertTextFormat: 2 },
  { label: 'str.substring', kind: MonacoKind.Method, detail: 'substring(indexStart, indexEnd?): string', documentation: 'Extracts substring.', insertText: '${1:str}.substring(${2:start}, ${3:end})', insertTextFormat: 2 },
  { label: 'str.toLowerCase', kind: MonacoKind.Method, detail: 'toLowerCase(): string', documentation: 'Converts to lowercase.', insertText: '${1:str}.toLowerCase()' },
  { label: 'str.toUpperCase', kind: MonacoKind.Method, detail: 'toUpperCase(): string', documentation: 'Converts to uppercase.', insertText: '${1:str}.toUpperCase()' },
  { label: 'str.trim', kind: MonacoKind.Method, detail: 'trim(): string', documentation: 'Removes whitespace.', insertText: '${1:str}.trim()' },
  { label: 'str.trimStart', kind: MonacoKind.Method, detail: 'trimStart(): string', documentation: 'Removes leading whitespace.', insertText: '${1:str}.trimStart()' },
  { label: 'str.trimEnd', kind: MonacoKind.Method, detail: 'trimEnd(): string', documentation: 'Removes trailing whitespace.', insertText: '${1:str}.trimEnd()' },
  { label: 'str.padEnd', kind: MonacoKind.Method, detail: 'padEnd(length, fillString?): string', documentation: 'Pads end of string.', insertText: '${1:str}.padEnd(${2:length}, "${3:" "}")', insertTextFormat: 2 },
  { label: 'str.padStart', kind: MonacoKind.Method, detail: 'padStart(length, fillString?): string', documentation: 'Pads start of string.', insertText: '${1:str}.padStart(${2:length}, "${3:" "}")', insertTextFormat: 2 },
  { label: 'str.repeat', kind: MonacoKind.Method, detail: 'repeat(count): string', documentation: 'Repeats string.', insertText: '${1:str}.repeat(${2:count})', insertTextFormat: 2 },
  { label: 'str.search', kind: MonacoKind.Method, detail: 'search(regexp): number', documentation: 'Searches for pattern.', insertText: '${1:str}.search(/${2:pattern}/)', insertTextFormat: 2 },
  { label: 'str.matchAll', kind: MonacoKind.Method, detail: 'matchAll(regexp): iterator', documentation: 'Matches all with regex.', insertText: '${1:str}.matchAll(/${2:pattern}/g)', insertTextFormat: 2 },
  { label: 'str.codePointAt', kind: MonacoKind.Method, detail: 'codePointAt(index): number', documentation: 'Returns code point at index.', insertText: '${1:str}.codePointAt(${2:index})', insertTextFormat: 2 },
  { label: 'str.normalize', kind: MonacoKind.Method, detail: 'normalize(form?): string', documentation: 'Returns Unicode normalization.', insertText: '${1:str}.normalize()' },
  { label: 'str.localeCompare', kind: MonacoKind.Method, detail: 'localeCompare(other): number', documentation: 'Compares strings in locale order.', insertText: '${1:str}.localeCompare(${2:other})', insertTextFormat: 2 },
  { label: 'String.fromCharCode', kind: MonacoKind.Function, detail: 'String.fromCharCode(...codes): string', documentation: 'Creates string from codes.', insertText: 'String.fromCharCode(${1:code})', insertTextFormat: 2 },
  { label: 'String.fromCodePoint', kind: MonacoKind.Function, detail: 'String.fromCodePoint(...points): string', documentation: 'Creates string from code points.', insertText: 'String.fromCodePoint(${1:point})', insertTextFormat: 2 },
  { label: 'template literal', kind: MonacoKind.Snippet, detail: 'Template literal', documentation: 'Creates a template literal.', insertText: '`${1:${2:variable}}`', insertTextFormat: 2 },

  // Object methods
  { label: 'Object.keys', kind: MonacoKind.Function, detail: 'Object.keys(value): string[]', documentation: 'Returns keys of object.', insertText: 'Object.keys(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.values', kind: MonacoKind.Function, detail: 'Object.values(value): array', documentation: 'Returns values of object.', insertText: 'Object.values(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.entries', kind: MonacoKind.Function, detail: 'Object.entries(value): [string, any][]', documentation: 'Returns key-value pairs.', insertText: 'Object.entries(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.assign', kind: MonacoKind.Function, detail: 'Object.assign(target, ...sources): target', documentation: 'Assigns properties.', insertText: 'Object.assign(${1:target}, ${2:source})', insertTextFormat: 2 },
  { label: 'Object.create', kind: MonacoKind.Function, detail: 'Object.create(proto): object', documentation: 'Creates object with prototype.', insertText: 'Object.create(${1:proto})', insertTextFormat: 2 },
  { label: 'Object.freeze', kind: MonacoKind.Function, detail: 'Object.freeze(obj): object', documentation: 'Freezes object.', insertText: 'Object.freeze(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.seal', kind: MonacoKind.Function, detail: 'Object.seal(obj): object', documentation: 'Seals object.', insertText: 'Object.seal(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.is', kind: MonacoKind.Function, detail: 'Object.is(value1, value2): boolean', documentation: 'Compares values.', insertText: 'Object.is(${1:a}, ${2:b})', insertTextFormat: 2 },
  { label: 'Object.hasOwn', kind: MonacoKind.Function, detail: 'Object.hasOwn(obj, prop): boolean', documentation: 'Checks own property (ES2022+).', insertText: 'Object.hasOwn(${1:obj}, "${2:prop}")', insertTextFormat: 2 },
  { label: 'Object.defineProperty', kind: MonacoKind.Function, detail: 'Object.defineProperty(obj, prop, descriptor)', documentation: 'Defines property.', insertText: 'Object.defineProperty(${1:obj}, "${2:prop}", { ${3:config} })', insertTextFormat: 2 },
  { label: 'Object.getOwnPropertyNames', kind: MonacoKind.Function, detail: 'Object.getOwnPropertyNames(obj): string[]', documentation: 'Returns all property names.', insertText: 'Object.getOwnPropertyNames(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.getPrototypeOf', kind: MonacoKind.Function, detail: 'Object.getPrototypeOf(obj): object', documentation: 'Returns prototype.', insertText: 'Object.getPrototypeOf(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.setPrototypeOf', kind: MonacoKind.Function, detail: 'Object.setPrototypeOf(obj, proto)', documentation: 'Sets prototype.', insertText: 'Object.setPrototypeOf(${1:obj}, ${2:proto})', insertTextFormat: 2 },
  { label: 'obj.hasOwnProperty', kind: MonacoKind.Method, detail: 'hasOwnProperty(prop): boolean', documentation: 'Checks own property.', insertText: '${1:obj}.hasOwnProperty("${2:prop}")', insertTextFormat: 2 },
  { label: 'obj.toString', kind: MonacoKind.Method, detail: 'toString(): string', documentation: 'Returns string representation.', insertText: '${1:obj}.toString()' },
  { label: 'obj.valueOf', kind: MonacoKind.Method, detail: 'valueOf(): object', documentation: 'Returns primitive value.', insertText: '${1:obj}.valueOf()' },

  // JSON
  { label: 'JSON.parse', kind: MonacoKind.Function, detail: 'JSON.parse(text): any', documentation: 'Parses JSON string.', insertText: 'JSON.parse(${1:text})', insertTextFormat: 2 },
  { label: 'JSON.stringify', kind: MonacoKind.Function, detail: 'JSON.stringify(value): string', documentation: 'Stringifies to JSON.', insertText: 'JSON.stringify(${1:value})', insertTextFormat: 2 },

  // Math
  { label: 'Math.PI', kind: MonacoKind.Constant, detail: 'Math.PI', documentation: 'Value of pi.', insertText: 'Math.PI' },
  { label: 'Math.E', kind: MonacoKind.Constant, detail: 'Math.E', documentation: 'Value of e.', insertText: 'Math.E' },
  { label: 'Math.abs', kind: MonacoKind.Function, detail: 'Math.abs(x): number', documentation: 'Absolute value.', insertText: 'Math.abs(${1:x})', insertTextFormat: 2 },
  { label: 'Math.max', kind: MonacoKind.Function, detail: 'Math.max(...values): number', documentation: 'Maximum value.', insertText: 'Math.max(${1:values})', insertTextFormat: 2 },
  { label: 'Math.min', kind: MonacoKind.Function, detail: 'Math.min(...values): number', documentation: 'Minimum value.', insertText: 'Math.min(${1:values})', insertTextFormat: 2 },
  { label: 'Math.pow', kind: MonacoKind.Function, detail: 'Math.pow(base, exp): number', documentation: 'Power function.', insertText: 'Math.pow(${1:base}, ${2:exp})', insertTextFormat: 2 },
  { label: 'Math.sqrt', kind: MonacoKind.Function, detail: 'Math.sqrt(x): number', documentation: 'Square root.', insertText: 'Math.sqrt(${1:x})', insertTextFormat: 2 },
  { label: 'Math.ceil', kind: MonacoKind.Function, detail: 'Math.ceil(x): number', documentation: 'Ceiling function.', insertText: 'Math.ceil(${1:x})', insertTextFormat: 2 },
  { label: 'Math.floor', kind: MonacoKind.Function, detail: 'Math.floor(x): number', documentation: 'Floor function.', insertText: 'Math.floor(${1:x})', insertTextFormat: 2 },
  { label: 'Math.round', kind: MonacoKind.Function, detail: 'Math.round(x): number', documentation: 'Rounds to nearest.', insertText: 'Math.round(${1:x})', insertTextFormat: 2 },
  { label: 'Math.trunc', kind: MonacoKind.Function, detail: 'Math.trunc(x): number', documentation: 'Truncates decimal.', insertText: 'Math.trunc(${1:x})', insertTextFormat: 2 },
  { label: 'Math.random', kind: MonacoKind.Function, detail: 'Math.random(): number', documentation: 'Random 0-1.', insertText: 'Math.random()' },
  { label: 'Math.sign', kind: MonacoKind.Function, detail: 'Math.sign(x): number', documentation: 'Sign of number.', insertText: 'Math.sign(${1:x})', insertTextFormat: 2 },
  { label: 'Math.sin', kind: MonacoKind.Function, detail: 'Math.sin(x): number', documentation: 'Sine function.', insertText: 'Math.sin(${1:x})', insertTextFormat: 2 },
  { label: 'Math.cos', kind: MonacoKind.Function, detail: 'Math.cos(x): number', documentation: 'Cosine function.', insertText: 'Math.cos(${1:x})', insertTextFormat: 2 },
  { label: 'Math.tan', kind: MonacoKind.Function, detail: 'Math.tan(x): number', documentation: 'Tangent function.', insertText: 'Math.tan(${1:x})', insertTextFormat: 2 },
  { label: 'Math.log', kind: MonacoKind.Function, detail: 'Math.log(x): number', documentation: 'Natural logarithm.', insertText: 'Math.log(${1:x})', insertTextFormat: 2 },
  { label: 'Math.log10', kind: MonacoKind.Function, detail: 'Math.log10(x): number', documentation: 'Base-10 logarithm.', insertText: 'Math.log10(${1:x})', insertTextFormat: 2 },
  { label: 'Math.exp', kind: MonacoKind.Function, detail: 'Math.exp(x): number', documentation: 'Exponential e^x.', insertText: 'Math.exp(${1:x})', insertTextFormat: 2 },
  { label: 'Number.isNaN', kind: MonacoKind.Function, detail: 'Number.isNaN(value): boolean', documentation: 'Checks for NaN.', insertText: 'Number.isNaN(${1:value})', insertTextFormat: 2 },
  { label: 'Number.isFinite', kind: MonacoKind.Function, detail: 'Number.isFinite(value): boolean', documentation: 'Checks if finite.', insertText: 'Number.isFinite(${1:value})', insertTextFormat: 2 },
  { label: 'Number.isInteger', kind: MonacoKind.Function, detail: 'Number.isInteger(value): boolean', documentation: 'Checks if integer.', insertText: 'Number.isInteger(${1:value})', insertTextFormat: 2 },
  { label: 'Number.parseInt', kind: MonacoKind.Function, detail: 'Number.parseInt(s, radix?): number', documentation: 'Parses integer.', insertText: 'Number.parseInt(${1:s})', insertTextFormat: 2 },
  { label: 'Number.parseFloat', kind: MonacoKind.Function, detail: 'Number.parseFloat(s): number', documentation: 'Parses float.', insertText: 'Number.parseFloat(${1:s})', insertTextFormat: 2 },

  // RegExp
  { label: 'RegExp', kind: MonacoKind.Class, detail: '/pattern/flags', documentation: 'Creates a RegExp.', insertText: '/${1:pattern}/${2:flags}', insertTextFormat: 2 },
  { label: 'regExp.test', kind: MonacoKind.Method, detail: 'test(str): boolean', documentation: 'Tests if pattern matches.', insertText: '/${1:pattern}/.test(${2:str})', insertTextFormat: 2 },
  { label: 'regExp.exec', kind: MonacoKind.Method, detail: 'exec(str): array | null', documentation: 'Executes pattern.', insertText: '/${1:pattern}/${2:g}.exec(${3:str})', insertTextFormat: 2 },
  { label: 'regExp.flags', kind: MonacoKind.Property, detail: 'flags property', documentation: 'Returns flags string.', insertText: '/${1:pattern}/${2:flags}.flags' },

  // Date
  { label: 'Date.now', kind: MonacoKind.Function, detail: 'Date.now(): number', documentation: 'Current timestamp.', insertText: 'Date.now()' },
  { label: 'new Date()', kind: MonacoKind.Class, detail: 'new Date()', documentation: 'Creates Date object.', insertText: 'new Date()' },
  { label: 'new Date(value)', kind: MonacoKind.Class, detail: 'new Date(milliseconds)', documentation: 'Creates Date from milliseconds.', insertText: 'new Date(${1:Date.now()})' },
  { label: 'new Date(dateString)', kind: MonacoKind.Class, detail: 'new Date(dateString)', documentation: 'Creates Date from string.', insertText: 'new Date("${1:2024-01-01}")', insertTextFormat: 2 },
  { label: 'date.toISOString', kind: MonacoKind.Method, detail: 'toISOString(): string', documentation: 'ISO format string.', insertText: '${1:date}.toISOString()' },
  { label: 'date.toLocaleDateString', kind: MonacoKind.Method, detail: 'toLocaleDateString(locale?): string', documentation: 'Locale date string.', insertText: '${1:date}.toLocaleDateString()' },
  { label: 'Date.parse', kind: MonacoKind.Function, detail: 'Date.parse(s): number', documentation: 'Parses date string.', insertText: 'Date.parse("${1:date}")', insertTextFormat: 2 },

  // Map / Set / WeakMap / WeakSet
  { label: 'new Map()', kind: MonacoKind.Class, detail: 'new Map()', documentation: 'Creates a Map.', insertText: 'new Map()' },
  { label: 'map.set', kind: MonacoKind.Method, detail: 'set(key, value): Map', documentation: 'Sets key-value pair.', insertText: '${1:map}.set(${2:key}, ${3:value})', insertTextFormat: 2 },
  { label: 'map.get', kind: MonacoKind.Method, detail: 'get(key): value | undefined', documentation: 'Gets value by key.', insertText: '${1:map}.get(${2:key})', insertTextFormat: 2 },
  { label: 'map.has', kind: MonacoKind.Method, detail: 'has(key): boolean', documentation: 'Checks if key exists.', insertText: '${1:map}.has(${2:key})', insertTextFormat: 2 },
  { label: 'map.delete', kind: MonacoKind.Method, detail: 'delete(key): boolean', documentation: 'Deletes entry.', insertText: '${1:map}.delete(${2:key})', insertTextFormat: 2 },
  { label: 'map.clear', kind: MonacoKind.Method, detail: 'clear(): void', documentation: 'Clears all entries.', insertText: '${1:map}.clear()' },
  { label: 'map.size', kind: MonacoKind.Property, detail: 'size property', documentation: 'Returns entry count.', insertText: '${1:map}.size' },
  { label: 'map.keys', kind: MonacoKind.Method, detail: 'keys(): iterator', documentation: 'Returns key iterator.', insertText: '${1:map}.keys()' },
  { label: 'map.values', kind: MonacoKind.Method, detail: 'values(): iterator', documentation: 'Returns value iterator.', insertText: '${1:map}.values()' },
  { label: 'map.entries', kind: MonacoKind.Method, detail: 'entries(): iterator', documentation: 'Returns entry iterator.', insertText: '${1:map}.entries()' },
  { label: 'map.forEach', kind: MonacoKind.Method, detail: 'forEach(callback): void', documentation: 'Iterates entries.', insertText: '${1:map}.forEach((${2:value}, ${3:key}) => {\n    ${4:// code\n})', insertTextFormat: 2 },
  { label: 'new Set()', kind: MonacoKind.Class, detail: 'new Set()', documentation: 'Creates a Set.', insertText: 'new Set()' },
  { label: 'set.add', kind: MonacoKind.Method, detail: 'add(value): Set', documentation: 'Adds value.', insertText: '${1:set}.add(${2:value})', insertTextFormat: 2 },
  { label: 'set.has', kind: MonacoKind.Method, detail: 'has(value): boolean', documentation: 'Checks if value exists.', insertText: '${1:set}.has(${2:value})', insertTextFormat: 2 },
  { label: 'set.delete', kind: MonacoKind.Method, detail: 'delete(value): boolean', documentation: 'Deletes value.', insertText: '${1:set}.delete(${2:value})', insertTextFormat: 2 },
  { label: 'set.clear', kind: MonacoKind.Method, detail: 'clear(): void', documentation: 'Clears all values.', insertText: '${1:set}.clear()' },
  { label: 'set.size', kind: MonacoKind.Property, detail: 'size property', documentation: 'Returns value count.', insertText: '${1:set}.size' },
  { label: 'set.forEach', kind: MonacoKind.Method, detail: 'forEach(callback): void', documentation: 'Iterates values.', insertText: '${1:set}.forEach((${2:value}) => {\n    ${3:// code\n})', insertTextFormat: 2 },
  { label: 'WeakMap', kind: MonacoKind.Class, detail: 'WeakMap', documentation: 'Weak map for object keys.', insertText: 'new WeakMap()' },
  { label: 'WeakSet', kind: MonacoKind.Class, detail: 'WeakSet', documentation: 'Weak set for object values.', insertText: 'new WeakSet()' },

  // Console
  { label: 'console.log', kind: MonacoKind.Function, detail: 'console.log(...data)', documentation: 'Logs to console.', insertText: 'console.log(${1:value})', insertTextFormat: 2 },
  { label: 'console.error', kind: MonacoKind.Function, detail: 'console.error(...data)', documentation: 'Logs error.', insertText: 'console.error(${1:value})', insertTextFormat: 2 },
  { label: 'console.warn', kind: MonacoKind.Function, detail: 'console.warn(...data)', documentation: 'Logs warning.', insertText: 'console.warn(${1:value})', insertTextFormat: 2 },
  { label: 'console.info', kind: MonacoKind.Function, detail: 'console.info(...data)', documentation: 'Logs info.', insertText: 'console.info(${1:value})', insertTextFormat: 2 },
  { label: 'console.debug', kind: MonacoKind.Function, detail: 'console.debug(...data)', documentation: 'Logs debug.', insertText: 'console.debug(${1:value})', insertTextFormat: 2 },
  { label: 'console.table', kind: MonacoKind.Function, detail: 'console.table(data)', documentation: 'Logs as table.', insertText: 'console.table(${1:data})', insertTextFormat: 2 },
  { label: 'console.group', kind: MonacoKind.Function, detail: 'console.group(...label)', documentation: 'Starts group.', insertText: 'console.group("${1:label}")', insertTextFormat: 2 },
  { label: 'console.groupEnd', kind: MonacoKind.Function, detail: 'console.groupEnd()', documentation: 'Ends group.', insertText: 'console.groupEnd()' },
  { label: 'console.time', kind: MonacoKind.Function, detail: 'console.time(label)', documentation: 'Starts timer.', insertText: 'console.time("${1:label}")', insertTextFormat: 2 },
  { label: 'console.timeEnd', kind: MonacoKind.Function, detail: 'console.timeEnd(label)', documentation: 'Ends timer.', insertText: 'console.timeEnd("${1:label}")', insertTextFormat: 2 },
  { label: 'console.assert', kind: MonacoKind.Function, detail: 'console.assert(condition, ...data)', documentation: 'Asserts condition.', insertText: 'console.assert(${1:condition}, ${2:message})', insertTextFormat: 2 },
  { label: 'console.trace', kind: MonacoKind.Function, detail: 'console.trace(...data)', documentation: 'Logs stack trace.', insertText: 'console.trace(${1:message})', insertTextFormat: 2 },
  { label: 'console.clear', kind: MonacoKind.Function, detail: 'console.clear()', documentation: 'Clears console.', insertText: 'console.clear()' },
  { label: 'console.dir', kind: MonacoKind.Function, detail: 'console.dir(obj)', documentation: 'Logs object properties.', insertText: 'console.dir(${1:obj})', insertTextFormat: 2 },

  // Global utils
  { label: 'typeof', kind: MonacoKind.Keyword, detail: 'typeof operator', documentation: 'Returns type as string.', insertText: 'typeof ${1:value}' },
  { label: 'instanceof', kind: MonacoKind.Keyword, detail: 'instanceof operator', documentation: 'Checks prototype chain.', insertText: '${1:value} instanceof ${2:Class}' },
  { label: 'delete', kind: MonacoKind.Keyword, detail: 'delete operator', documentation: 'Deletes property.', insertText: 'delete ${1:obj.${2:prop}}', insertTextFormat: 2 },
  { label: 'in', kind: MonacoKind.Keyword, detail: 'in operator', documentation: 'Checks if property exists.', insertText: '"${1:prop}" in ${2:obj}', insertTextFormat: 2 },
  { label: 'new', kind: MonacoKind.Keyword, detail: 'new operator', documentation: 'Creates instance.', insertText: 'new ${1:Class}(${2:args})', insertTextFormat: 2 },
  { label: 'this', kind: MonacoKind.Keyword, detail: 'this keyword', documentation: 'Current this context.', insertText: 'this' },
  { label: 'super', kind: MonacoKind.Keyword, detail: 'super keyword', documentation: 'Parent class reference.', insertText: 'super.${1:method}()', insertTextFormat: 2 },
  { label: 'debugger', kind: MonacoKind.Keyword, detail: 'debugger statement', documentation: 'Debugger breakpoint.', insertText: 'debugger;' },

  // Nullish operators
  { label: '?? (nullish coalescing)', kind: MonacoKind.Operator, detail: '?? operator', documentation: 'Nullish coalescing.', insertText: '${1:value} ?? ${2:defaultValue}', insertTextFormat: 2 },
  { label: '?. (optional chaining)', kind: MonacoKind.Operator, detail: '?. operator', documentation: 'Optional chaining.', insertText: '${1:obj}?.${2:prop}', insertTextFormat: 2 },
  { label: '?.() (optional call)', kind: MonacoKind.Operator, detail: '?.() optional call', documentation: 'Optional method call.', insertText: '${1:obj}?.${2:method}()', insertTextFormat: 2 },
  { label: '?.[] (optional index)', kind: MonacoKind.Operator, detail: '?.[] optional index', documentation: 'Optional index access.', insertText: '${1:arr}?.[${2:index}]', insertTextFormat: 2 },
  { label: '??= (nullish assignment)', kind: MonacoKind.Operator, detail: '??= assignment', documentation: 'Assigns if nullish.', insertText: '${1:value} ??= ${2:defaultValue}', insertTextFormat: 2 },

  // Destructuring
  { label: 'object destructuring', kind: MonacoKind.Snippet, detail: 'Object destructuring', documentation: 'Creates object destructuring.', insertText: 'const { ${1:prop1}, ${2:prop2} } = ${3:obj};', insertTextFormat: 2 },
  { label: 'array destructuring', kind: MonacoKind.Snippet, detail: 'Array destructuring', documentation: 'Creates array destructuring.', insertText: 'const [${1:elem1}, ${2:elem2}] = ${3:array};', insertTextFormat: 2 },
  { label: 'destructuring with rename', kind: MonacoKind.Snippet, detail: 'destructuring with rename', documentation: 'Destructuring with renamed variables.', insertText: 'const { ${1:prop}: ${2:renamed} } = ${3:obj};', insertTextFormat: 2 },
  { label: 'destructuring with default', kind: MonacoKind.Snippet, detail: 'destructuring with default', documentation: 'Destructuring with default values.', insertText: 'const { ${1:prop} = ${2:defaultValue} } = ${3:obj};', insertTextFormat: 2 },
  { label: 'nested destructuring', kind: MonacoKind.Snippet, detail: 'Nested destructuring', documentation: 'Nested object destructuring.', insertText: 'const { ${1:nested}: { ${2:prop} } } = ${3:obj};', insertTextFormat: 2 },
  { label: 'rest element', kind: MonacoKind.Snippet, detail: 'Rest element in destructuring', documentation: 'Collects remaining elements.', insertText: 'const [${1:first}, ...${2:rest}] = ${3:array};', insertTextFormat: 2 },

  // Spread / Rest
  { label: 'spread in array', kind: MonacoKind.Operator, detail: 'Spread operator in array', documentation: 'Spreads array into new array.', insertText: '[...${1:array1}, ...${2:array2}]', insertTextFormat: 2 },
  { label: 'spread in object', kind: MonacoKind.Operator, detail: 'Spread operator in object', documentation: 'Spreads object into new object.', insertText: '{ ...${1:obj1}, ...${2:obj2} }', insertTextFormat: 2 },
  { label: 'spread in function call', kind: MonacoKind.Operator, detail: 'Spread in function call', documentation: 'Spreads array as arguments.', insertText: '${1:func}(...${2:args})', insertTextFormat: 2 },
  { label: 'rest in function', kind: MonacoKind.Operator, detail: 'Rest parameters', documentation: 'Collects remaining arguments.', insertText: 'function ${1:name}(${2:arg}, ...${3:rest}) {\n    ${4:// code\n}', insertTextFormat: 2 },

  // Modules
  { label: 'import', kind: MonacoKind.Snippet, detail: 'import', documentation: 'Named import.', insertText: 'import { ${1:name} } from "${2:module}";', insertTextFormat: 2 },
  { label: 'import default', kind: MonacoKind.Snippet, detail: 'import default', documentation: 'Default import.', insertText: 'import ${1:name} from "${2:module}";', insertTextFormat: 2 },
  { label: 'import side-effect', kind: MonacoKind.Snippet, detail: 'import side-effect', documentation: 'Side-effect only import.', insertText: 'import "${1:module}";', insertTextFormat: 2 },
  { label: 'import dynamic', kind: MonacoKind.Snippet, detail: 'dynamic import', documentation: 'Dynamic import.', insertText: 'const ${1:module} = await import("${2:module}");', insertTextFormat: 2 },
  { label: 'namespace import', kind: MonacoKind.Snippet, detail: 'namespace import', documentation: 'Namespace import.', insertText: 'import * as ${1:Namespace} from "${2:module}";', insertTextFormat: 2 },
  { label: 'require', kind: MonacoKind.Snippet, detail: 'require (CommonJS)', documentation: 'CommonJS require.', insertText: 'const ${1:name} = require("${2:module}");', insertTextFormat: 2 },
  { label: 'export default', kind: MonacoKind.Snippet, detail: 'export default', documentation: 'Default export.', insertText: 'export default ${1:value};', insertTextFormat: 2 },
  { label: 'export named', kind: MonacoKind.Snippet, detail: 'export named', documentation: 'Named export.', insertText: 'export { ${1:name} };', insertTextFormat: 2 },
  { label: 'export const', kind: MonacoKind.Snippet, detail: 'export const', documentation: 'Exports a const.', insertText: 'export const ${1:name} = ${2:value};', insertTextFormat: 2 },
  { label: 'export function', kind: MonacoKind.Snippet, detail: 'export function', documentation: 'Exports a function.', insertText: 'export function ${1:name}(${2:args}) {\n    ${3:// code\n}', insertTextFormat: 2 },
  { label: 'export class', kind: MonacoKind.Snippet, detail: 'export class', documentation: 'Exports a class.', insertText: 'export class ${1:ClassName} {\n    ${2:// code\n}', insertTextFormat: 2 },
  { label: 'export expression', kind: MonacoKind.Snippet, detail: 'export expression', documentation: 'Export statement.', insertText: 'export ${1:expression};', insertTextFormat: 2 },

  // Class
  { label: 'class', kind: MonacoKind.Snippet, detail: 'class definition', documentation: 'Creates a class.', insertText: 'class ${1:ClassName} {\n    constructor(${2:args}) {\n        ${3:// initialization\n    }\n}', insertTextFormat: 2 },
  { label: 'class extends', kind: MonacoKind.Snippet, detail: 'class with inheritance', documentation: 'Creates a class extending another.', insertText: 'class ${1:ChildClass} extends ${2:ParentClass} {\n    constructor(${3:args}) {\n        super(${3:args});\n    }\n}', insertTextFormat: 2 },
  { label: 'getter', kind: MonacoKind.Snippet, detail: 'getter', documentation: 'Creates a getter.', insertText: 'get ${1:name}() {\n    return this.${2:_${1:name}};\n}', insertTextFormat: 2 },
  { label: 'setter', kind: MonacoKind.Snippet, detail: 'setter', documentation: 'Creates a setter.', insertText: 'set ${1:name}(${2:value}) {\n    this.${3:_${1:name}} = ${2:value};\n}', insertTextFormat: 2 },
  { label: 'static method', kind: MonacoKind.Snippet, detail: 'static method', documentation: 'Creates a static method.', insertText: 'static ${1:methodName}(${2:args}) {\n    ${3:// code\n}', insertTextFormat: 2 },
  { label: 'private field (#)', kind: MonacoKind.Snippet, detail: 'Private class field', documentation: 'Creates a private field.', insertText: '#${1:field};', insertTextFormat: 2 },
  { label: 'private method', kind: MonacoKind.Snippet, detail: 'Private class method', documentation: 'Creates a private method.', insertText: '#${1:methodName}(${2:args}) {\n    ${3:// code\n}', insertTextFormat: 2 },
  { label: 'get class name', kind: MonacoKind.Snippet, detail: 'class name getter', documentation: 'Static readonly class name.', insertText: 'static get name() { return "${1:ClassName}"; }' },

  // ES2020+ features
  { label: 'BigInt', kind: MonacoKind.Class, detail: 'BigInt literal', documentation: 'Creates a BigInt.', insertText: 'BigInt(${1:value})', insertTextFormat: 2 },
  { label: 'BigInt literal', kind: MonacoKind.Constant, detail: 'BigInt literal', documentation: 'BigInt literal notation.', insertText: '${1:number}n', insertTextFormat: 2 },
  { label: '??= (logical nullish assignment)', kind: MonacoKind.Operator, detail: '??= operator', documentation: 'Assigns if nullish.', insertText: '${1:x} ??= ${2:value}', insertTextFormat: 2 },
  { label: '||= (logical OR assignment)', kind: MonacoKind.Operator, detail: '||= operator', documentation: 'Assigns if falsy.', insertText: '${1:x} ||= ${2:value}', insertTextFormat: 2 },
  { label: '&&= (logical AND assignment)', kind: MonacoKind.Operator, detail: '&&= operator', documentation: 'Assigns if truthy.', insertText: '${1:x} &&= ${2:value}', insertTextFormat: 2 },
  { label: '?? (nullish coalescing)', kind: MonacoKind.Operator, detail: '?? operator', documentation: 'Nullish coalescing.', insertText: '${1:x} ?? ${2:y}', insertTextFormat: 2 },
  { label: '?. (optional chaining)', kind: MonacoKind.Operator, detail: '?. operator', documentation: 'Optional chaining.', insertText: '${1:obj}?.${2:prop}', insertTextFormat: 2 },

  // Other globals
  { label: 'setTimeout', kind: MonacoKind.Function, detail: 'setTimeout(callback, delay, ...args): number', documentation: 'Runs callback after delay.', insertText: 'setTimeout(() => {\n    ${1:// code\n}, ${2:delay});', insertTextFormat: 2 },
  { label: 'setInterval', kind: MonacoKind.Function, detail: 'setInterval(callback, delay, ...args): number', documentation: 'Runs callback repeatedly.', insertText: 'setInterval(() => {\n    ${1:// code\n}, ${2:delay});', insertTextFormat: 2 },
  { label: 'clearTimeout', kind: MonacoKind.Function, detail: 'clearTimeout(id)', documentation: 'Clears timeout.', insertText: 'clearTimeout(${1:id})', insertTextFormat: 2 },
  { label: 'clearInterval', kind: MonacoKind.Function, detail: 'clearInterval(id)', documentation: 'Clears interval.', insertText: 'clearInterval(${1:id})', insertTextFormat: 2 },
  { label: 'setImmediate', kind: MonacoKind.Function, detail: 'setImmediate(callback, ...args)', documentation: 'Runs callback immediately.', insertText: 'setImmediate(() => {\n    ${1:// code\n})', insertTextFormat: 2 },
  { label: 'queueMicrotask', kind: MonacoKind.Function, detail: 'queueMicrotask(callback)', documentation: 'Queues microtask.', insertText: 'queueMicrotask(() => {\n    ${1:// code\n})', insertTextFormat: 2 },
  { label: 'structuredClone', kind: MonacoKind.Function, detail: 'structuredClone(value): clone', documentation: 'Clones value (deep) (ES2021+).', insertText: 'structuredClone(${1:value})', insertTextFormat: 2 },
  { label: 'isNaN', kind: MonacoKind.Function, detail: 'isNaN(value): boolean', documentation: 'Checks if NaN.', insertText: 'isNaN(${1:value})', insertTextFormat: 2 },
  { label: 'isFinite', kind: MonacoKind.Function, detail: 'isFinite(value): boolean', documentation: 'Checks if finite.', insertText: 'isFinite(${1:value})', insertTextFormat: 2 },
  { label: 'parseInt', kind: MonacoKind.Function, detail: 'parseInt(s, radix?): number', documentation: 'Parses integer.', insertText: 'parseInt(${1:s})', insertTextFormat: 2 },
  { label: 'parseFloat', kind: MonacoKind.Function, detail: 'parseFloat(s): number', documentation: 'Parses float.', insertText: 'parseFloat(${1:s})', insertTextFormat: 2 },
  { label: 'encodeURI', kind: MonacoKind.Function, detail: 'encodeURI(uri): string', documentation: 'Encodes URI.', insertText: 'encodeURI("${1:uri}")', insertTextFormat: 2 },
  { label: 'decodeURI', kind: MonacoKind.Function, detail: 'decodeURI(uri): string', documentation: 'Decodes URI.', insertText: 'decodeURI("${1:uri}")', insertTextFormat: 2 },
  { label: 'encodeURIComponent', kind: MonacoKind.Function, detail: 'encodeURIComponent(str): string', documentation: 'Encodes URI component.', insertText: 'encodeURIComponent("${1:str}")', insertTextFormat: 2 },
  { label: 'decodeURIComponent', kind: MonacoKind.Function, detail: 'decodeURIComponent(str): string', documentation: 'Decodes URI component.', insertText: 'decodeURIComponent("${1:str}")', insertTextFormat: 2 },
  { label: 'eval', kind: MonacoKind.Function, detail: 'eval(code): any', documentation: 'Evaluates code.', insertText: 'eval(${1:code})', insertTextFormat: 2 },
  { label: 'escape', kind: MonacoKind.Function, detail: 'escape(str): string', documentation: 'Escapes string (deprecated).', insertText: 'escape("${1:str}")', insertTextFormat: 2 },
  { label: 'unescape', kind: MonacoKind.Function, detail: 'unescape(str): string', documentation: 'Unescapes string (deprecated).', insertText: 'unescape("${1:str}")', insertTextFormat: 2 },

  // Proxy / Reflect
  { label: 'new Proxy', kind: MonacoKind.Snippet, detail: 'new Proxy(target, handler)', documentation: 'Creates a Proxy.', insertText: 'new Proxy(${1:target}, {\n    get(${2:target}, ${3:prop}) {\n        ${4:// code\n    }\n})', insertTextFormat: 2 },
  { label: 'Reflect.get', kind: MonacoKind.Function, detail: 'Reflect.get(target, prop): value', documentation: 'Gets property.', insertText: 'Reflect.get(${1:target}, "${2:prop}")', insertTextFormat: 2 },
  { label: 'Reflect.set', kind: MonacoKind.Function, detail: 'Reflect.set(target, prop, value): boolean', documentation: 'Sets property.', insertText: 'Reflect.set(${1:target}, "${2:prop}", ${3:value})', insertTextFormat: 2 },
  { label: 'Reflect.has', kind: MonacoKind.Function, detail: 'Reflect.has(target, prop): boolean', documentation: 'Checks if property exists.', insertText: 'Reflect.has(${1:target}, "${2:prop}")', insertTextFormat: 2 },
  { label: 'Reflect.deleteProperty', kind: MonacoKind.Function, detail: 'Reflect.deleteProperty(target, prop): boolean', documentation: 'Deletes property.', insertText: 'Reflect.deleteProperty(${1:target}, "${2:prop}")', insertTextFormat: 2 },
  { label: 'Reflect.apply', kind: MonacoKind.Function, detail: 'Reflect.apply(fn, thisArg, args): result', documentation: 'Applies function.', insertText: 'Reflect.apply(${1:fn}, ${2:thisArg}, ${3:args})', insertTextFormat: 2 },
  { label: 'Reflect.construct', kind: MonacoKind.Function, detail: 'Reflect.construct(target, args): instance', documentation: 'Constructs instance.', insertText: 'Reflect.construct(${1:Target}, ${2:args})', insertTextFormat: 2 },
  { label: 'Reflect.getPrototypeOf', kind: MonacoKind.Function, detail: 'Reflect.getPrototypeOf(target): object', documentation: 'Gets prototype.', insertText: 'Reflect.getPrototypeOf(${1:target})', insertTextFormat: 2 },
  { label: 'Reflect.setPrototypeOf', kind: MonacoKind.Function, detail: 'Reflect.setPrototypeOf(target, proto): boolean', documentation: 'Sets prototype.', insertText: 'Reflect.setPrototypeOf(${1:target}, ${2:proto})', insertTextFormat: 2 },
  { label: 'Reflect.defineProperty', kind: MonacoKind.Function, detail: 'Reflect.defineProperty(target, prop, descriptor): boolean', documentation: 'Defines property.', insertText: 'Reflect.defineProperty(${1:target}, "${2:prop}", { ${3:descriptor} })', insertTextFormat: 2 },

  // Symbol
  { label: 'Symbol', kind: MonacoKind.Function, detail: 'Symbol(description?)', documentation: 'Creates a Symbol.', insertText: 'Symbol("${1:description}")', insertTextFormat: 2 },
  { label: 'Symbol.for', kind: MonacoKind.Function, detail: 'Symbol.for(key)', documentation: 'Global symbol registry.', insertText: 'Symbol.for("${1:key}")', insertTextFormat: 2 },
  { label: 'Symbol.keyFor', kind: MonacoKind.Function, detail: 'Symbol.keyFor(sym)', documentation: 'Gets key from global symbol.', insertText: 'Symbol.keyFor(${1:sym})', insertTextFormat: 2 },
];
