import { LspCompletionItem, MonacoKind } from './types';

export const PYTHON_API_COMPLETIONS: LspCompletionItem[] = [
  // Built-in Types
  { label: 'int', kind: MonacoKind.Class, detail: 'int', documentation: 'Integer type.', insertText: 'int' },
  { label: 'float', kind: MonacoKind.Class, detail: 'float', documentation: 'Floating point type.', insertText: 'float' },
  { label: 'str', kind: MonacoKind.Class, detail: 'str', documentation: 'String type.', insertText: 'str' },
  { label: 'bool', kind: MonacoKind.Class, detail: 'bool', documentation: 'Boolean type.', insertText: 'bool' },
  { label: 'list', kind: MonacoKind.Class, detail: 'list', documentation: 'List type.', insertText: 'list' },
  { label: 'dict', kind: MonacoKind.Class, detail: 'dict', documentation: 'Dictionary type.', insertText: 'dict' },
  { label: 'set', kind: MonacoKind.Class, detail: 'set', documentation: 'Set type.', insertText: 'set' },
  { label: 'tuple', kind: MonacoKind.Class, detail: 'tuple', documentation: 'Tuple type.', insertText: 'tuple' },
  { label: 'bytes', kind: MonacoKind.Class, detail: 'bytes', documentation: 'Bytes type.', insertText: 'bytes' },
  { label: 'bytearray', kind: MonacoKind.Class, detail: 'bytearray', documentation: 'Bytearray type.', insertText: 'bytearray' },
  { label: 'type', kind: MonacoKind.Class, detail: 'type', documentation: 'Type/class type.', insertText: 'type' },
  { label: 'object', kind: MonacoKind.Class, detail: 'object', documentation: 'Base object class.', insertText: 'object' },
  { label: 'complex', kind: MonacoKind.Class, detail: 'complex', documentation: 'Complex number type.', insertText: 'complex' },
  { label: 'frozenset', kind: MonacoKind.Class, detail: 'frozenset', documentation: 'Immutable set type.', insertText: 'frozenset' },
  { label: 'range', kind: MonacoKind.Class, detail: 'range(stop)', documentation: 'Range type.', insertText: 'range(${1:stop})', insertTextFormat: 2 },
  { label: 'slice', kind: MonacoKind.Class, detail: 'slice(start, stop, step)', documentation: 'Slice type.', insertText: 'slice(${1:start}, ${2:stop}, ${3:step})', insertTextFormat: 2 },
  { label: 'memoryview', kind: MonacoKind.Class, detail: 'memoryview(obj)', documentation: 'Memory view type.', insertText: 'memoryview(${1:obj})', insertTextFormat: 2 },

  // Built-in Functions
  { label: 'print', kind: MonacoKind.Function, detail: 'print(*objects, sep, end, file, flush)', documentation: 'Prints to stdout.', insertText: 'print(${1:value})', insertTextFormat: 2 },
  { label: 'input', kind: MonacoKind.Function, detail: 'input(prompt)', documentation: 'Reads from stdin.', insertText: 'input("${1:prompt}")', insertTextFormat: 2 },
  { label: 'len', kind: MonacoKind.Function, detail: 'len(s)', documentation: 'Returns length.', insertText: 'len(${1:s})', insertTextFormat: 2 },
  { label: 'enumerate', kind: MonacoKind.Function, detail: 'enumerate(iterable, start)', documentation: 'Enumerates iterable.', insertText: 'enumerate(${1:iterable})', insertTextFormat: 2 },
  { label: 'zip', kind: MonacoKind.Function, detail: 'zip(*iterables)', documentation: 'Zips iterables.', insertText: 'zip(${1:a}, ${2:b})', insertTextFormat: 2 },
  { label: 'map', kind: MonacoKind.Function, detail: 'map(func, *iterables)', documentation: 'Maps function over iterable.', insertText: 'map(${1:func}, ${2:iterable})', insertTextFormat: 2 },
  { label: 'filter', kind: MonacoKind.Function, detail: 'filter(function, iterable)', documentation: 'Filters iterable.', insertText: 'filter(${1:func}, ${2:iterable})', insertTextFormat: 2 },
  { label: 'sorted', kind: MonacoKind.Function, detail: 'sorted(iterable, *, key, reverse)', documentation: 'Returns sorted list.', insertText: 'sorted(${1:iterable})', insertTextFormat: 2 },
  { label: 'reversed', kind: MonacoKind.Function, detail: 'reversed(sequence)', documentation: 'Returns reversed iterator.', insertText: 'reversed(${1:seq})', insertTextFormat: 2 },
  { label: 'sum', kind: MonacoKind.Function, detail: 'sum(iterable, start)', documentation: 'Sums iterable.', insertText: 'sum(${1:iterable})', insertTextFormat: 2 },
  { label: 'min', kind: MonacoKind.Function, detail: 'min(iterable, *, key, default)', documentation: 'Returns minimum.', insertText: 'min(${1:iterable})', insertTextFormat: 2 },
  { label: 'max', kind: MonacoKind.Function, detail: 'max(iterable, *, key, default)', documentation: 'Returns maximum.', insertText: 'max(${1:iterable})', insertTextFormat: 2 },
  { label: 'abs', kind: MonacoKind.Function, detail: 'abs(x)', documentation: 'Absolute value.', insertText: 'abs(${1:x})', insertTextFormat: 2 },
  { label: 'round', kind: MonacoKind.Function, detail: 'round(number, ndigits)', documentation: 'Rounds number.', insertText: 'round(${1:x})', insertTextFormat: 2 },
  { label: 'pow', kind: MonacoKind.Function, detail: 'pow(x, y, z)', documentation: 'Power function.', insertText: 'pow(${1:x}, ${2:y})', insertTextFormat: 2 },
  { label: 'divmod', kind: MonacoKind.Function, detail: 'divmod(a, b)', documentation: 'Integer division and remainder.', insertText: 'divmod(${1:a}, ${2:b})', insertTextFormat: 2 },
  { label: 'chr', kind: MonacoKind.Function, detail: 'chr(i)', documentation: 'Int to character.', insertText: 'chr(${1:i})', insertTextFormat: 2 },
  { label: 'ord', kind: MonacoKind.Function, detail: 'ord(c)', documentation: 'Char to int.', insertText: 'ord(${1:c})', insertTextFormat: 2 },
  { label: 'hex', kind: MonacoKind.Function, detail: 'hex(x)', documentation: 'Hex string.', insertText: 'hex(${1:x})', insertTextFormat: 2 },
  { label: 'oct', kind: MonacoKind.Function, detail: 'oct(x)', documentation: 'Octal string.', insertText: 'oct(${1:x})', insertTextFormat: 2 },
  { label: 'bin', kind: MonacoKind.Function, detail: 'bin(x)', documentation: 'Binary string.', insertText: 'bin(${1:x})', insertTextFormat: 2 },
  { label: 'all', kind: MonacoKind.Function, detail: 'all(iterable)', documentation: 'True if all elements are true.', insertText: 'all(${1:iterable})', insertTextFormat: 2 },
  { label: 'any', kind: MonacoKind.Function, detail: 'any(iterable)', documentation: 'True if any element is true.', insertText: 'any(${1:iterable})', insertTextFormat: 2 },
  { label: 'isinstance', kind: MonacoKind.Function, detail: 'isinstance(obj, classinfo)', documentation: 'Checks instance type.', insertText: 'isinstance(${1:obj}, ${2:Class})', insertTextFormat: 2 },
  { label: 'issubclass', kind: MonacoKind.Function, detail: 'issubclass(class, classinfo)', documentation: 'Checks subclass.', insertText: 'issubclass(${1:class}, ${2:Class})', insertTextFormat: 2 },
  { label: 'hasattr', kind: MonacoKind.Function, detail: 'hasattr(object, name)', documentation: 'Checks attribute existence.', insertText: 'hasattr(${1:obj}, "${2:name}")', insertTextFormat: 2 },
  { label: 'getattr', kind: MonacoKind.Function, detail: 'getattr(object, name, default)', documentation: 'Gets attribute.', insertText: 'getattr(${1:obj}, "${2:name}")', insertTextFormat: 2 },
  { label: 'setattr', kind: MonacoKind.Function, detail: 'setattr(object, name, value)', documentation: 'Sets attribute.', insertText: 'setattr(${1:obj}, "${2:name}", ${3:value});', insertTextFormat: 2 },
  { label: 'delattr', kind: MonacoKind.Function, detail: 'delattr(object, name)', documentation: 'Deletes attribute.', insertText: 'delattr(${1:obj}, "${2:name}");', insertTextFormat: 2 },
  { label: 'callable', kind: MonacoKind.Function, detail: 'callable(object)', documentation: 'Checks if callable.', insertText: 'callable(${1:obj})', insertTextFormat: 2 },
  { label: 'dir', kind: MonacoKind.Function, detail: 'dir(object)', documentation: 'Returns attribute list.', insertText: 'dir(${1:obj})', insertTextFormat: 2 },
  { label: 'vars', kind: MonacoKind.Function, detail: 'vars(object)', documentation: 'Returns __dict__.', insertText: 'vars(${1:obj})', insertTextFormat: 2 },
  { label: 'id', kind: MonacoKind.Function, detail: 'id(object)', documentation: 'Returns object identity.', insertText: 'id(${1:obj})', insertTextFormat: 2 },
  { label: 'hash', kind: MonacoKind.Function, detail: 'hash(object)', documentation: 'Returns hash.', insertText: 'hash(${1:obj})', insertTextFormat: 2 },
  { label: 'repr', kind: MonacoKind.Function, detail: 'repr(object)', documentation: 'String representation.', insertText: 'repr(${1:obj})', insertTextFormat: 2 },
  { label: 'open', kind: MonacoKind.Function, detail: 'open(file, mode, encoding)', documentation: 'Opens a file.', insertText: 'open("${1:file.txt}", "${2:r}")', insertTextFormat: 2 },
  { label: 'iter', kind: MonacoKind.Function, detail: 'iter(object, sentinel)', documentation: 'Creates iterator.', insertText: 'iter(${1:obj})', insertTextFormat: 2 },
  { label: 'next', kind: MonacoKind.Function, detail: 'next(iterator, default)', documentation: 'Gets next item.', insertText: 'next(${1:iterator})', insertTextFormat: 2 },
  { label: 'property', kind: MonacoKind.Function, detail: 'property(fget, fset, fdel, doc)', documentation: 'Creates property.', insertText: '@property\ndef ${1:name}(self):\n    return ${2:self._name}', insertTextFormat: 2 },
  { label: 'staticmethod', kind: MonacoKind.Function, detail: 'staticmethod', documentation: 'Static method decorator.', insertText: '@staticmethod\ndef ${1:method}():\n    ${2:pass}', insertTextFormat: 2 },
  { label: 'classmethod', kind: MonacoKind.Function, detail: 'classmethod', documentation: 'Class method decorator.', insertText: '@classmethod\ndef ${1:method}(cls):\n    ${2:pass}', insertTextFormat: 2 },
  { label: 'super', kind: MonacoKind.Function, detail: 'super(type, obj)', documentation: 'Call parent class.', insertText: 'super().${1:method}()', insertTextFormat: 2 },
  { label: 'type', kind: MonacoKind.Function, detail: 'type(object)', documentation: 'Returns type.', insertText: 'type(${1:obj})', insertTextFormat: 2 },

  // Constants
  { label: 'True', kind: MonacoKind.Constant, detail: 'True', documentation: 'Boolean true.', insertText: 'True' },
  { label: 'False', kind: MonacoKind.Constant, detail: 'False', documentation: 'Boolean false.', insertText: 'False' },
  { label: 'None', kind: MonacoKind.Constant, detail: 'None', documentation: 'Null value.', insertText: 'None' },
  { label: 'NotImplemented', kind: MonacoKind.Constant, detail: 'NotImplemented', documentation: 'Not implemented sentinel.', insertText: 'NotImplemented' },
  { label: 'Ellipsis', kind: MonacoKind.Constant, detail: '... (Ellipsis)', documentation: 'Ellipsis literal.', insertText: '...' },
  { label: '__name__', kind: MonacoKind.Constant, detail: '__name__', documentation: 'Module name.', insertText: '__name__' },
  { label: '__main__', kind: MonacoKind.Constant, detail: '__main__', documentation: 'Main module name.', insertText: '__name__ == "__main__"' },

  // collections
  { label: 'defaultdict', kind: MonacoKind.Class, detail: 'collections.defaultdict(default_factory)', documentation: 'Dictionary with default factory.', insertText: 'from collections import defaultdict', insertTextFormat: 2 },
  { label: 'Counter', kind: MonacoKind.Class, detail: 'collections.Counter([iterable])', documentation: 'Counts hashable items.', insertText: 'from collections import Counter', insertTextFormat: 2 },
  { label: 'OrderedDict', kind: MonacoKind.Class, detail: 'collections.OrderedDict', documentation: 'Dictionary that remembers order.', insertText: 'from collections import OrderedDict', insertTextFormat: 2 },
  { label: 'deque', kind: MonacoKind.Class, detail: 'collections.deque([iterable], maxlen)', documentation: 'Double-ended queue.', insertText: 'from collections import deque', insertTextFormat: 2 },
  { label: 'namedtuple', kind: MonacoKind.Function, detail: 'namedtuple(typename, field_names)', documentation: 'Creates tuple with named fields.', insertText: 'from collections import namedtuple', insertTextFormat: 2 },
  { label: 'ChainMap', kind: MonacoKind.Class, detail: 'collections.ChainMap', documentation: 'Chain multiple mappings.', insertText: 'from collections import ChainMap', insertTextFormat: 2 },
  { label: 'UserDict', kind: MonacoKind.Class, detail: 'collections.UserDict', documentation: 'Wrapper for dict.', insertText: 'from collections import UserDict', insertTextFormat: 2 },
  { label: 'deque.append', kind: MonacoKind.Method, detail: 'append(x)', documentation: 'Add to right.', insertText: 'deque.append(${1:x})', insertTextFormat: 2 },
  { label: 'deque.appendleft', kind: MonacoKind.Method, detail: 'appendleft(x)', documentation: 'Add to left.', insertText: 'deque.appendleft(${1:x})', insertTextFormat: 2 },
  { label: 'deque.pop', kind: MonacoKind.Method, detail: 'pop()', documentation: 'Remove from right.', insertText: 'deque.pop()' },
  { label: 'deque.popleft', kind: MonacoKind.Method, detail: 'popleft()', documentation: 'Remove from left.', insertText: 'deque.popleft()' },
  { label: 'deque.extend', kind: MonacoKind.Method, detail: 'extend(iterable)', documentation: 'Extend right.', insertText: 'deque.extend(${1:iterable})', insertTextFormat: 2 },
  { label: 'deque.rotate', kind: MonacoKind.Method, detail: 'rotate(n)', documentation: 'Rotate deque.', insertText: 'deque.rotate(${1:1})', insertTextFormat: 2 },
  { label: 'deque.clear', kind: MonacoKind.Method, detail: 'clear()', documentation: 'Clear deque.', insertText: 'deque.clear()' },
  { label: 'deque.count', kind: MonacoKind.Method, detail: 'count(x)', documentation: 'Count occurrences.', insertText: 'deque.count(${1:x})', insertTextFormat: 2 },

  // itertools
  { label: 'itertools.count', kind: MonacoKind.Function, detail: 'count(start, step)', documentation: 'Infinite counter.', insertText: 'from itertools import count', insertTextFormat: 2 },
  { label: 'itertools.cycle', kind: MonacoKind.Function, detail: 'cycle(iterable)', documentation: 'Cycles through iterable.', insertText: 'from itertools import cycle', insertTextFormat: 2 },
  { label: 'itertools.repeat', kind: MonacoKind.Function, detail: 'repeat(elem, times)', documentation: 'Repeats element.', insertText: 'from itertools import repeat', insertTextFormat: 2 },
  { label: 'itertools.chain', kind: MonacoKind.Function, detail: 'chain(*iterables)', documentation: 'Chains iterables.', insertText: 'from itertools import chain', insertTextFormat: 2 },
  { label: 'itertools.islice', kind: MonacoKind.Function, detail: 'islice(iterable, stop)', documentation: 'Slice iterator.', insertText: 'from itertools import islice', insertTextFormat: 2 },
  { label: 'itertools.takewhile', kind: MonacoKind.Function, detail: 'takewhile(predicate, iterable)', documentation: 'Takes while true.', insertText: 'from itertools import takewhile', insertTextFormat: 2 },
  { label: 'itertools.dropwhile', kind: MonacoKind.Function, detail: 'dropwhile(predicate, iterable)', documentation: 'Drops while true.', insertText: 'from itertools import dropwhile', insertTextFormat: 2 },
  { label: 'itertools.groupby', kind: MonacoKind.Function, detail: 'groupby(iterable, key)', documentation: 'Groups consecutive elements.', insertText: 'from itertools import groupby', insertTextFormat: 2 },
  { label: 'itertools.compress', kind: MonacoKind.Function, detail: 'compress(data, selectors)', documentation: 'Filters by selectors.', insertText: 'from itertools import compress', insertTextFormat: 2 },
  { label: 'itertools.product', kind: MonacoKind.Function, detail: 'product(*iterables, repeat)', documentation: 'Cartesian product.', insertText: 'from itertools import product', insertTextFormat: 2 },
  { label: 'itertools.permutations', kind: MonacoKind.Function, detail: 'permutations(iterable, r)', documentation: 'All permutations.', insertText: 'from itertools import permutations', insertTextFormat: 2 },
  { label: 'itertools.combinations', kind: MonacoKind.Function, detail: 'combinations(iterable, r)', documentation: 'All combinations.', insertText: 'from itertools import combinations', insertTextFormat: 2 },
  { label: 'itertools.zip_longest', kind: MonacoKind.Function, detail: 'zip_longest(*iterables, fillvalue)', documentation: 'Zips with fillvalue.', insertText: 'from itertools import zip_longest', insertTextFormat: 2 },
  { label: 'itertools.accumulate', kind: MonacoKind.Function, detail: 'accumulate(iterable, func)', documentation: 'Accumulates values.', insertText: 'from itertools import accumulate', insertTextFormat: 2 },
  { label: 'itertools.filterfalse', kind: MonacoKind.Function, detail: 'filterfalse(predicate, iterable)', documentation: 'False filter.', insertText: 'from itertools import filterfalse', insertTextFormat: 2 },
  { label: 'itertools.starmap', kind: MonacoKind.Function, detail: 'starmap(func, iterable)', documentation: 'Starmap.', insertText: 'from itertools import starmap', insertTextFormat: 2 },
  { label: 'itertools.tee', kind: MonacoKind.Function, detail: 'tee(iterable, n)', documentation: 'Tees iterable.', insertText: 'from itertools import tee', insertTextFormat: 2 },

  // functools
  { label: '@lru_cache', kind: MonacoKind.Function, detail: 'lru_cache(maxsize, typed)', documentation: 'LRU cache decorator.', insertText: '@lru_cache\ndef ${1:func}(${2:args}):\n    ${3:pass}', insertTextFormat: 2 },
  { label: '@cache', kind: MonacoKind.Function, detail: 'cache decorator (Python 3.9+)', documentation: 'Unbounded cache.', insertText: '@cache\ndef ${1:func}(${2:args}):\n    ${3:pass}', insertTextFormat: 2 },
  { label: '@wraps', kind: MonacoKind.Function, detail: 'wraps(wrapped, assign, update)', documentation: 'Copies function metadata.', insertText: '@wraps(${1:func})\ndef ${2:wrapper}(*args, **kwargs):\n    return ${1:func}(*args, **kwargs)', insertTextFormat: 2 },
  { label: 'functools.reduce', kind: MonacoKind.Function, detail: 'reduce(function, iterable, initializer)', documentation: 'Reduces iterable.', insertText: 'from functools import reduce', insertTextFormat: 2 },
  { label: 'functools.cmp_to_key', kind: MonacoKind.Function, detail: 'cmp_to_key(function)', documentation: 'Converts comparison function to key.', insertText: 'from functools import cmp_to_key', insertTextFormat: 2 },
  { label: 'functools.partial', kind: MonacoKind.Function, detail: 'partial(func, *args, **keywords)', documentation: 'Partial function application.', insertText: 'from functools import partial', insertTextFormat: 2 },
  { label: 'functools.total_ordering', kind: MonacoKind.Function, detail: 'total_ordering', documentation: 'Fills in comparison methods.', insertText: 'from functools import total_ordering', insertTextFormat: 2 },
  { label: 'functools.cached_property', kind: MonacoKind.Function, detail: 'cached_property(func)', documentation: 'Cached property (Python 3.8+).', insertText: 'from functools import cached_property', insertTextFormat: 2 },

  // math
  { label: 'import math', kind: MonacoKind.Snippet, detail: 'import math', documentation: 'Imports math module.', insertText: 'import math' },
  { label: 'math.pi', kind: MonacoKind.Constant, detail: 'math.pi', documentation: 'Value of pi.', insertText: 'math.pi' },
  { label: 'math.e', kind: MonacoKind.Constant, detail: 'math.e', documentation: 'Value of e.', insertText: 'math.e' },
  { label: 'math.inf', kind: MonacoKind.Constant, detail: 'math.inf', documentation: 'Positive infinity.', insertText: 'math.inf' },
  { label: 'math.nan', kind: MonacoKind.Constant, detail: 'math.nan', documentation: 'Not a number.', insertText: 'math.nan' },
  { label: 'math.ceil', kind: MonacoKind.Function, detail: 'ceil(x)', documentation: 'Ceiling function.', insertText: 'math.ceil(${1:x})', insertTextFormat: 2 },
  { label: 'math.floor', kind: MonacoKind.Function, detail: 'floor(x)', documentation: 'Floor function.', insertText: 'math.floor(${1:x})', insertTextFormat: 2 },
  { label: 'math.fabs', kind: MonacoKind.Function, detail: 'fabs(x)', documentation: 'Absolute value.', insertText: 'math.fabs(${1:x})', insertTextFormat: 2 },
  { label: 'math.factorial', kind: MonacoKind.Function, detail: 'factorial(x)', documentation: 'Factorial function.', insertText: 'math.factorial(${1:x})', insertTextFormat: 2 },
  { label: 'math.exp', kind: MonacoKind.Function, detail: 'exp(x)', documentation: 'Exponential e^x.', insertText: 'math.exp(${1:x})', insertTextFormat: 2 },
  { label: 'math.log', kind: MonacoKind.Function, detail: 'log(x, base)', documentation: 'Natural logarithm.', insertText: 'math.log(${1:x})', insertTextFormat: 2 },
  { label: 'math.log10', kind: MonacoKind.Function, detail: 'log10(x)', documentation: 'Base-10 logarithm.', insertText: 'math.log10(${1:x})', insertTextFormat: 2 },
  { label: 'math.log2', kind: MonacoKind.Function, detail: 'log2(x)', documentation: 'Base-2 logarithm.', insertText: 'math.log2(${1:x})', insertTextFormat: 2 },
  { label: 'math.pow', kind: MonacoKind.Function, detail: 'pow(x, y)', documentation: 'Power function.', insertText: 'math.pow(${1:x}, ${2:y})', insertTextFormat: 2 },
  { label: 'math.sqrt', kind: MonacoKind.Function, detail: 'sqrt(x)', documentation: 'Square root.', insertText: 'math.sqrt(${1:x})', insertTextFormat: 2 },
  { label: 'math.isqrt', kind: MonacoKind.Function, detail: 'isqrt(n)', documentation: 'Integer square root.', insertText: 'math.isqrt(${1:n})', insertTextFormat: 2 },
  { label: 'math.sin', kind: MonacoKind.Function, detail: 'sin(x)', documentation: 'Sine function.', insertText: 'math.sin(${1:x})', insertTextFormat: 2 },
  { label: 'math.cos', kind: MonacoKind.Function, detail: 'cos(x)', documentation: 'Cosine function.', insertText: 'math.cos(${1:x})', insertTextFormat: 2 },
  { label: 'math.tan', kind: MonacoKind.Function, detail: 'tan(x)', documentation: 'Tangent function.', insertText: 'math.tan(${1:x})', insertTextFormat: 2 },
  { label: 'math.asin', kind: MonacoKind.Function, detail: 'asin(x)', documentation: 'Arc sine.', insertText: 'math.asin(${1:x})', insertTextFormat: 2 },
  { label: 'math.acos', kind: MonacoKind.Function, detail: 'acos(x)', documentation: 'Arc cosine.', insertText: 'math.acos(${1:x})', insertTextFormat: 2 },
  { label: 'math.atan', kind: MonacoKind.Function, detail: 'atan(x)', documentation: 'Arc tangent.', insertText: 'math.atan(${1:x})', insertTextFormat: 2 },
  { label: 'math.atan2', kind: MonacoKind.Function, detail: 'atan2(y, x)', documentation: 'Two-argument arc tangent.', insertText: 'math.atan2(${1:y}, ${2:x})', insertTextFormat: 2 },
  { label: 'math.sinh', kind: MonacoKind.Function, detail: 'sinh(x)', documentation: 'Hyperbolic sine.', insertText: 'math.sinh(${1:x})', insertTextFormat: 2 },
  { label: 'math.cosh', kind: MonacoKind.Function, detail: 'cosh(x)', documentation: 'Hyperbolic cosine.', insertText: 'math.cosh(${1:x})', insertTextFormat: 2 },
  { label: 'math.tanh', kind: MonacoKind.Function, detail: 'tanh(x)', documentation: 'Hyperbolic tangent.', insertText: 'math.tanh(${1:x})', insertTextFormat: 2 },
  { label: 'math.asinh', kind: MonacoKind.Function, detail: 'asinh(x)', documentation: 'Inverse hyperbolic sine.', insertText: 'math.asinh(${1:x})', insertTextFormat: 2 },
  { label: 'math.acosh', kind: MonacoKind.Function, detail: 'acosh(x)', documentation: 'Inverse hyperbolic cosine.', insertText: 'math.acosh(${1:x})', insertTextFormat: 2 },
  { label: 'math.atanh', kind: MonacoKind.Function, detail: 'atanh(x)', documentation: 'Inverse hyperbolic tangent.', insertText: 'math.atanh(${1:x})', insertTextFormat: 2 },
  { label: 'math.degrees', kind: MonacoKind.Function, detail: 'degrees(x)', documentation: 'Converts radians to degrees.', insertText: 'math.degrees(${1:x})', insertTextFormat: 2 },
  { label: 'math.radians', kind: MonacoKind.Function, detail: 'radians(x)', documentation: 'Converts degrees to radians.', insertText: 'math.radians(${1:x})', insertTextFormat: 2 },
  { label: 'math.gcd', kind: MonacoKind.Function, detail: 'gcd(*integers)', documentation: 'Greatest common divisor.', insertText: 'math.gcd(${1:a}, ${2:b})', insertTextFormat: 2 },
  { label: 'math.lcm', kind: MonacoKind.Function, detail: 'lcm(*integers)', documentation: 'Least common multiple (Python 3.9+).', insertText: 'math.lcm(${1:a}, ${2:b})', insertTextFormat: 2 },
  { label: 'math.isclose', kind: MonacoKind.Function, detail: 'isclose(a, b, rel_tol, abs_tol)', documentation: 'Checks if values are close.', insertText: 'math.isclose(${1:a}, ${2:b})', insertTextFormat: 2 },
  { label: 'math.isfinite', kind: MonacoKind.Function, detail: 'isfinite(x)', documentation: 'Checks if finite.', insertText: 'math.isfinite(${1:x})', insertTextFormat: 2 },
  { label: 'math.isnan', kind: MonacoKind.Function, detail: 'isnan(x)', documentation: 'Checks if NaN.', insertText: 'math.isnan(${1:x})', insertTextFormat: 2 },
  { label: 'math.isinf', kind: MonacoKind.Function, detail: 'isinf(x)', documentation: 'Checks if infinite.', insertText: 'math.isinf(${1:x})', insertTextFormat: 2 },
  { label: 'math.trunc', kind: MonacoKind.Function, detail: 'trunc(x)', documentation: 'Truncates fractional part.', insertText: 'math.trunc(${1:x})', insertTextFormat: 2 },
  { label: 'math.fmod', kind: MonacoKind.Function, detail: 'fmod(x, y)', documentation: 'Remainder of x/y.', insertText: 'math.fmod(${1:x}, ${2:y})', insertTextFormat: 2 },
  { label: 'math.comb', kind: MonacoKind.Function, detail: 'comb(n, k)', documentation: 'Number of combinations (Python 3.8+).', insertText: 'math.comb(${1:n}, ${2:k})', insertTextFormat: 2 },
  { label: 'math.perm', kind: MonacoKind.Function, detail: 'perm(n, k)', documentation: 'Number of permutations (Python 3.8+).', insertText: 'math.perm(${1:n}, ${2:k})', insertTextFormat: 2 },
  { label: 'math.prod', kind: MonacoKind.Function, detail: 'prod(iterable, start)', documentation: 'Product of iterable (Python 3.8+).', insertText: 'math.prod(${1:iterable})', insertTextFormat: 2 },
  { label: 'math.dist', kind: MonacoKind.Function, detail: 'dist(p, q)', documentation: 'Euclidean distance.', insertText: 'math.dist(${1:p}, ${2:q})', insertTextFormat: 2 },

  // random
  { label: 'import random', kind: MonacoKind.Snippet, detail: 'import random', documentation: 'Imports random module.', insertText: 'import random' },
  { label: 'random.random', kind: MonacoKind.Function, detail: 'random()', documentation: 'Random float 0-1.', insertText: 'random.random()' },
  { label: 'random.randint', kind: MonacoKind.Function, detail: 'randint(a, b)', documentation: 'Random integer a to b.', insertText: 'random.randint(${1:a}, ${2:b})', insertTextFormat: 2 },
  { label: 'random.randrange', kind: MonacoKind.Function, detail: 'randrange(start, stop, step)', documentation: 'Random from range.', insertText: 'random.randrange(${1:start}, ${2:stop})', insertTextFormat: 2 },
  { label: 'random.choice', kind: MonacoKind.Function, detail: 'choice(sequence)', documentation: 'Random element from sequence.', insertText: 'random.choice(${1:sequence})', insertTextFormat: 2 },
  { label: 'random.choices', kind: MonacoKind.Function, detail: 'choices(population, weights, k)', documentation: 'Multiple random choices.', insertText: 'random.choices(${1:population}, k=${2:k})', insertTextFormat: 2 },
  { label: 'random.shuffle', kind: MonacoKind.Function, detail: 'shuffle(sequence)', documentation: 'Shuffles sequence in place.', insertText: 'random.shuffle(${1:x})', insertTextFormat: 2 },
  { label: 'random.sample', kind: MonacoKind.Function, detail: 'sample(population, k)', documentation: 'Samples k elements.', insertText: 'random.sample(${1:population}, ${2:k})', insertTextFormat: 2 },
  { label: 'random.uniform', kind: MonacoKind.Function, detail: 'uniform(a, b)', documentation: 'Random float in range.', insertText: 'random.uniform(${1:a}, ${2:b})', insertTextFormat: 2 },
  { label: 'random.seed', kind: MonacoKind.Function, detail: 'seed(a)', documentation: 'Seeds random generator.', insertText: 'random.seed(${1:a})', insertTextFormat: 2 },

  // datetime
  { label: 'from datetime import datetime, date, time, timedelta', kind: MonacoKind.Snippet, detail: 'import datetime classes', documentation: 'Imports datetime classes.', insertText: 'from datetime import datetime, date, time, timedelta' },
  { label: 'datetime.now', kind: MonacoKind.Function, detail: 'datetime.now(tz)', documentation: 'Current local datetime.', insertText: 'datetime.now()' },
  { label: 'datetime.utcnow', kind: MonacoKind.Function, detail: 'datetime.utcnow()', documentation: 'Current UTC datetime.', insertText: 'datetime.utcnow()' },
  { label: 'datetime.strptime', kind: MonacoKind.Function, detail: 'strptime(date_string, format)', documentation: 'Parse string to datetime.', insertText: 'datetime.strptime("${1:2024-01-01}", "${2:%Y-%m-%d}")', insertTextFormat: 2 },
  { label: 'datetime.strftime', kind: MonacoKind.Function, detail: 'strftime(format)', documentation: 'Format datetime to string.', insertText: 'dt.strftime("${1:%Y-%m-%d}")', insertTextFormat: 2 },
  { label: 'datetime.fromisoformat', kind: MonacoKind.Function, detail: 'fromisoformat(date_string)', documentation: 'Parse ISO format string.', insertText: 'datetime.fromisoformat("${1:2024-01-01}")', insertTextFormat: 2 },
  { label: 'date.today', kind: MonacoKind.Function, detail: 'date.today()', documentation: "Today's date.", insertText: 'date.today()' },
  { label: 'timedelta', kind: MonacoKind.Class, detail: 'timedelta(days, seconds, microseconds, ...)', documentation: 'Time difference.', insertText: 'timedelta(days=${1:1})', insertTextFormat: 2 },

  // re (regex)
  { label: 'import re', kind: MonacoKind.Snippet, detail: 'import re', documentation: 'Imports regex module.', insertText: 'import re' },
  { label: 're.match', kind: MonacoKind.Function, detail: 'match(pattern, string, flags)', documentation: 'Match at beginning.', insertText: 're.match(r"${1:pattern}", ${2:string})', insertTextFormat: 2 },
  { label: 're.search', kind: MonacoKind.Function, detail: 'search(pattern, string, flags)', documentation: 'Search anywhere.', insertText: 're.search(r"${1:pattern}", ${2:string})', insertTextFormat: 2 },
  { label: 're.findall', kind: MonacoKind.Function, detail: 'findall(pattern, string, flags)', documentation: 'Find all matches.', insertText: 're.findall(r"${1:pattern}", ${2:string})', insertTextFormat: 2 },
  { label: 're.finditer', kind: MonacoKind.Function, detail: 'finditer(pattern, string, flags)', documentation: 'Find all matches as iterator.', insertText: 're.finditer(r"${1:pattern}", ${2:string})', insertTextFormat: 2 },
  { label: 're.sub', kind: MonacoKind.Function, detail: 'sub(pattern, repl, string, count, flags)', documentation: 'Replace all.', insertText: 're.sub(r"${1:pattern}", "${2:repl}", ${3:string})', insertTextFormat: 2 },
  { label: 're.subn', kind: MonacoKind.Function, detail: 'subn(pattern, repl, string, count, flags)', documentation: 'Replace and return count.', insertText: 're.subn(r"${1:pattern}", "${2:repl}", ${3:string})', insertTextFormat: 2 },
  { label: 're.split', kind: MonacoKind.Function, detail: 'split(pattern, string, maxsplit, flags)', documentation: 'Split by pattern.', insertText: 're.split(r"${1:pattern}", ${2:string})', insertTextFormat: 2 },
  { label: 're.compile', kind: MonacoKind.Function, detail: 'compile(pattern, flags)', documentation: 'Compile pattern.', insertText: 'pattern = re.compile(r"${1:pattern}")', insertTextFormat: 2 },
  { label: 're.IGNORECASE', kind: MonacoKind.Constant, detail: 're.IGNORECASE / re.I', documentation: 'Case-insensitive matching.', insertText: 're.IGNORECASE' },
  { label: 're.MULTILINE', kind: MonacoKind.Constant, detail: 're.MULTILINE / re.M', documentation: '^ and $ match line boundaries.', insertText: 're.MULTILINE' },
  { label: 're.DOTALL', kind: MonacoKind.Constant, detail: 're.DOTALL / re.S', documentation: '. matches newline.', insertText: 're.DOTALL' },
  { label: 're.VERBOSE', kind: MonacoKind.Constant, detail: 're.VERBOSE / re.X', documentation: 'Verbose regex.', insertText: 're.VERBOSE' },

  // os / sys
  { label: 'import os', kind: MonacoKind.Snippet, detail: 'import os', documentation: 'Imports os module.', insertText: 'import os' },
  { label: 'import sys', kind: MonacoKind.Snippet, detail: 'import sys', documentation: 'Imports sys module.', insertText: 'import sys' },
  { label: 'os.getcwd', kind: MonacoKind.Function, detail: 'getcwd()', documentation: 'Gets current working directory.', insertText: 'os.getcwd()' },
  { label: 'os.chdir', kind: MonacoKind.Function, detail: 'chdir(path)', documentation: 'Changes directory.', insertText: 'os.chdir(${1:"path"})', insertTextFormat: 2 },
  { label: 'os.listdir', kind: MonacoKind.Function, detail: 'listdir(path)', documentation: 'Lists directory contents.', insertText: 'os.listdir(${1:"."})', insertTextFormat: 2 },
  { label: 'os.mkdir', kind: MonacoKind.Function, detail: 'mkdir(path, mode)', documentation: 'Creates directory.', insertText: 'os.mkdir(${1:"path"})', insertTextFormat: 2 },
  { label: 'os.makedirs', kind: MonacoKind.Function, detail: 'makedirs(path, mode)', documentation: 'Creates directories recursively.', insertText: 'os.makedirs(${1:"path"})', insertTextFormat: 2 },
  { label: 'os.remove', kind: MonacoKind.Function, detail: 'remove(path)', documentation: 'Removes file.', insertText: 'os.remove(${1:"file"})', insertTextFormat: 2 },
  { label: 'os.unlink', kind: MonacoKind.Function, detail: 'unlink(path)', documentation: 'Removes file.', insertText: 'os.unlink(${1:"file"})', insertTextFormat: 2 },
  { label: 'os.rename', kind: MonacoKind.Function, detail: 'rename(src, dst)', documentation: 'Renames file/directory.', insertText: 'os.rename(${1:"src"}, ${2:"dst"})', insertTextFormat: 2 },
  { label: 'os.path.exists', kind: MonacoKind.Function, detail: 'exists(path)', documentation: 'Checks if path exists.', insertText: 'os.path.exists(${1:"path"})', insertTextFormat: 2 },
  { label: 'os.path.isfile', kind: MonacoKind.Function, detail: 'isfile(path)', documentation: 'Checks if file.', insertText: 'os.path.isfile(${1:"path"})', insertTextFormat: 2 },
  { label: 'os.path.isdir', kind: MonacoKind.Function, detail: 'isdir(path)', documentation: 'Checks if directory.', insertText: 'os.path.isdir(${1:"path"})', insertTextFormat: 2 },
  { label: 'os.path.join', kind: MonacoKind.Function, detail: 'join(*paths)', documentation: 'Joins path components.', insertText: 'os.path.join(${1:"dir"}, ${2:"file"})', insertTextFormat: 2 },
  { label: 'os.path.abspath', kind: MonacoKind.Function, detail: 'abspath(path)', documentation: 'Absolute path.', insertText: 'os.path.abspath(${1:"path"})', insertTextFormat: 2 },
  { label: 'os.path.dirname', kind: MonacoKind.Function, detail: 'dirname(path)', documentation: 'Directory name.', insertText: 'os.path.dirname(${1:"path"})', insertTextFormat: 2 },
  { label: 'os.path.basename', kind: MonacoKind.Function, detail: 'basename(path)', documentation: 'Base name.', insertText: 'os.path.basename(${1:"path"})', insertTextFormat: 2 },
  { label: 'os.path.splitext', kind: MonacoKind.Function, detail: 'splitext(path)', documentation: 'Split extension.', insertText: 'os.path.splitext(${1:"path"})', insertTextFormat: 2 },
  { label: 'os.walk', kind: MonacoKind.Function, detail: 'walk(top, topdown, onerror, followlinks)', documentation: 'Directory tree generator.', insertText: 'os.walk(${1:"."})', insertTextFormat: 2 },
  { label: 'os.getenv', kind: MonacoKind.Function, detail: 'getenv(name, default)', documentation: 'Gets environment variable.', insertText: 'os.getenv("${1:name}")', insertTextFormat: 2 },
  { label: 'os.environ', kind: MonacoKind.Variable, detail: 'os.environ', documentation: 'Environment variables dict.', insertText: 'os.environ' },
  { label: 'os.system', kind: MonacoKind.Function, detail: 'system(command)', documentation: 'Executes system command.', insertText: 'os.system(${1:"command"})', insertTextFormat: 2 },
  { label: 'sys.path', kind: MonacoKind.Variable, detail: 'sys.path', documentation: 'Module search path.', insertText: 'sys.path' },
  { label: 'sys.argv', kind: MonacoKind.Variable, detail: 'sys.argv', documentation: 'Command line arguments.', insertText: 'sys.argv' },
  { label: 'sys.version', kind: MonacoKind.Constant, detail: 'sys.version', documentation: 'Python version string.', insertText: 'sys.version' },
  { label: 'sys.exit', kind: MonacoKind.Function, detail: 'exit(status)', documentation: 'Exits Python.', insertText: 'sys.exit(${1:0})', insertTextFormat: 2 },
  { label: 'sys.getrecursionlimit', kind: MonacoKind.Function, detail: 'getrecursionlimit()', documentation: 'Gets recursion limit.', insertText: 'sys.getrecursionlimit()' },
  { label: 'sys.setrecursionlimit', kind: MonacoKind.Function, detail: 'setrecursionlimit(limit)', documentation: 'Sets recursion limit.', insertText: 'sys.setrecursionlimit(${1:1000})', insertTextFormat: 2 },
  { label: 'sys.getsizeof', kind: MonacoKind.Function, detail: 'getsizeof(object, default)', documentation: 'Object size in bytes.', insertText: 'sys.getsizeof(${1:obj})', insertTextFormat: 2 },

  // json
  { label: 'import json', kind: MonacoKind.Snippet, detail: 'import json', documentation: 'Imports json module.', insertText: 'import json' },
  { label: 'json.dumps', kind: MonacoKind.Function, detail: 'dumps(obj, indent, sort_keys)', documentation: 'Object to JSON string.', insertText: 'json.dumps(${1:obj})', insertTextFormat: 2 },
  { label: 'json.loads', kind: MonacoKind.Function, detail: 'loads(s)', documentation: 'JSON string to object.', insertText: 'json.loads(${1:s})', insertTextFormat: 2 },
  { label: 'json.dump', kind: MonacoKind.Function, detail: 'dump(obj, fp, indent, sort_keys)', documentation: 'Object to JSON file.', insertText: 'json.dump(${1:obj}, ${2:file})', insertTextFormat: 2 },
  { label: 'json.load', kind: MonacoKind.Function, detail: 'load(fp)', documentation: 'JSON file to object.', insertText: 'json.load(${1:file})', insertTextFormat: 2 },

  // pathlib
  { label: 'from pathlib import Path', kind: MonacoKind.Snippet, detail: 'import Path from pathlib', documentation: 'Imports Path class.', insertText: 'from pathlib import Path' },
  { label: 'Path.glob', kind: MonacoKind.Method, detail: 'glob(pattern)', documentation: 'Glob pattern matching.', insertText: 'Path.glob("${1:*.py}")', insertTextFormat: 2 },
  { label: 'Path.rglob', kind: MonacoKind.Method, detail: 'rglob(pattern)', documentation: 'Recursive glob.', insertText: 'Path.rglob("${1:*.py}")', insertTextFormat: 2 },
  { label: 'Path.exists', kind: MonacoKind.Method, detail: 'exists()', documentation: 'Checks if path exists.', insertText: 'Path("${1:path}").exists()' },
  { label: 'Path.is_file', kind: MonacoKind.Method, detail: 'is_file()', documentation: 'Checks if file.', insertText: 'Path("${1:path}").is_file()' },
  { label: 'Path.is_dir', kind: MonacoKind.Method, detail: 'is_dir()', documentation: 'Checks if directory.', insertText: 'Path("${1:path}").is_dir()' },
  { label: 'Path.iterdir', kind: MonacoKind.Method, detail: 'iterdir()', documentation: 'Iterates directory contents.', insertText: 'Path("${1:path}").iterdir()' },
  { label: 'Path.mkdir', kind: MonacoKind.Method, detail: 'mkdir(parents, exist_ok)', documentation: 'Creates directory.', insertText: 'Path("${1:path}").mkdir(parents=True, exist_ok=True)' },
  { label: 'Path.rename', kind: MonacoKind.Method, detail: 'rename(target)', documentation: 'Renames path.', insertText: 'Path("${1:src}").rename("${2:dst}")' },
  { label: 'Path.read_text', kind: MonacoKind.Method, detail: 'read_text(encoding)', documentation: 'Reads text content.', insertText: 'Path("${1:file}").read_text()' },
  { label: 'Path.write_text', kind: MonacoKind.Method, detail: 'write_text(data, encoding)', documentation: 'Writes text content.', insertText: 'Path("${1:file}").write_text(${2:data})', insertTextFormat: 2 },
  { label: 'Path.read_bytes', kind: MonacoKind.Method, detail: 'read_bytes()', documentation: 'Reads binary content.', insertText: 'Path("${1:file}").read_bytes()' },
  { label: 'Path.write_bytes', kind: MonacoKind.Method, detail: 'write_bytes(data)', documentation: 'Writes binary content.', insertText: 'Path("${1:file}").write_bytes(${2:data})', insertTextFormat: 2 },
  { label: 'Path.resolve', kind: MonacoKind.Method, detail: 'resolve()', documentation: 'Absolute path.', insertText: 'Path("${1:path}").resolve()' },
  { label: 'Path.parent', kind: MonacoKind.Property, detail: 'parent', documentation: 'Parent directory.', insertText: 'Path("${1:path}").parent' },
  { label: 'Path.name', kind: MonacoKind.Property, detail: 'name', documentation: 'File/directory name.', insertText: 'Path("${1:path}").name' },
  { label: 'Path.stem', kind: MonacoKind.Property, detail: 'stem', documentation: 'File name without extension.', insertText: 'Path("${1:path}").stem' },
  { label: 'Path.suffix', kind: MonacoKind.Property, detail: 'suffix', documentation: 'File extension.', insertText: 'Path("${1:path}").suffix' },
  { label: 'Path.parts', kind: MonacoKind.Property, detail: 'parts', documentation: 'Path components tuple.', insertText: 'Path("${1:path}").parts' },

  // typing
  { label: 'from typing import List, Dict, Set, Tuple, Optional, Union, Any, Callable, TypeVar, Generic', kind: MonacoKind.Snippet, detail: 'import typing generics', documentation: 'Imports typing generics.', insertText: 'from typing import List, Dict, Set, Tuple, Optional, Union, Any, Callable, TypeVar, Generic' },
  { label: 'List', kind: MonacoKind.Class, detail: 'typing.List', documentation: 'List type hint.', insertText: 'List[${1:int}]', insertTextFormat: 2 },
  { label: 'Dict', kind: MonacoKind.Class, detail: 'typing.Dict', documentation: 'Dict type hint.', insertText: 'Dict[${1:str}, ${2:int}]', insertTextFormat: 2 },
  { label: 'Set', kind: MonacoKind.Class, detail: 'typing.Set', documentation: 'Set type hint.', insertText: 'Set[${1:int}]', insertTextFormat: 2 },
  { label: 'Tuple', kind: MonacoKind.Class, detail: 'typing.Tuple', documentation: 'Tuple type hint.', insertText: 'Tuple[${1:int}, ${2:str}]', insertTextFormat: 2 },
  { label: 'Optional', kind: MonacoKind.Class, detail: 'typing.Optional[X]', documentation: 'Union[X, None].', insertText: 'Optional[${1:int}]', insertTextFormat: 2 },
  { label: 'Union', kind: MonacoKind.Class, detail: 'typing.Union', documentation: 'Union of types.', insertText: 'Union[${1:A}, ${2:B}]', insertTextFormat: 2 },
  { label: 'Any', kind: MonacoKind.Class, detail: 'typing.Any', documentation: 'Any type, no type checking.', insertText: 'Any' },
  { label: 'Callable', kind: MonacoKind.Class, detail: 'typing.Callable[[Args], Return]', documentation: 'Function type.', insertText: 'Callable[[${1:Args}], ${2:Return}]', insertTextFormat: 2 },
  { label: 'TypeVar', kind: MonacoKind.Class, detail: 'typing.TypeVar', documentation: 'Generic type variable.', insertText: "TypeVar('${1:T}')", insertTextFormat: 2 },
  { label: 'Generic', kind: MonacoKind.Class, detail: 'typing.Generic', documentation: 'Generic base class.', insertText: 'class ${1:GenericClass}(Generic[${2:T}]):', insertTextFormat: 2 },
  { label: 'Literal', kind: MonacoKind.Class, detail: 'typing.Literal', documentation: 'Literal type.', insertText: 'Literal[${1:"value"}]', insertTextFormat: 2 },
  { label: 'Final', kind: MonacoKind.Class, detail: 'typing.Final', documentation: 'Final constant type.', insertText: 'Final[${1:int}]', insertTextFormat: 2 },
  { label: '@overload', kind: MonacoKind.Function, detail: '@overload', documentation: 'Define overloaded signatures.', insertText: '@overload\ndef ${1:func}(${2:args}) -> ${3:rtype}:\n    ...', insertTextFormat: 2 },
  { label: 'cast', kind: MonacoKind.Function, detail: 'cast(Type, value)', documentation: 'Cast to type.', insertText: 'cast(${1:Type}, ${2:value})', insertTextFormat: 2 },

  // enum
  { label: 'from enum import Enum, auto, IntEnum, Flag', kind: MonacoKind.Snippet, detail: 'import enum', documentation: 'Imports enum module.', insertText: 'from enum import Enum, auto, IntEnum, Flag' },
  { label: 'class Color(Enum)', kind: MonacoKind.Snippet, detail: 'Enum class', documentation: 'Creates an enum.', insertText: 'class ${1:Color}(Enum):\n    ${2:RED} = auto()\n    ${3:GREEN} = auto()', insertTextFormat: 2 },
  { label: 'auto', kind: MonacoKind.Function, detail: 'auto()', documentation: 'Auto-numbered enum value.', insertText: 'auto()' },
  { label: '@unique', kind: MonacoKind.Function, detail: '@unique', documentation: 'Ensures enum values are unique.', insertText: '@unique\nclass ${1:Color}(Enum):', insertTextFormat: 2 },

  // Control flow snippets
  { label: 'def function', kind: MonacoKind.Snippet, detail: 'function definition', documentation: 'Defines a function.', insertText: 'def ${1:function_name}(${2:args}):\n    ${3:pass}', insertTextFormat: 2 },
  { label: 'lambda', kind: MonacoKind.Snippet, detail: 'lambda function', documentation: 'Lambda expression.', insertText: 'lambda ${1:x}: ${2:x}', insertTextFormat: 2 },
  { label: 'if __name__ == "__main__":', kind: MonacoKind.Snippet, detail: 'main guard', documentation: 'Main entry point guard.', insertText: 'if __name__ == "__main__":\n    ${1:main()}', insertTextFormat: 2 },
  { label: 'for i in range(n):', kind: MonacoKind.Snippet, detail: 'for loop with range', documentation: 'Iterates n times.', insertText: 'for ${1:i} in range(${2:n}):\n    ${3:pass}', insertTextFormat: 2 },
  { label: 'for item in iterable:', kind: MonacoKind.Snippet, detail: 'for loop over iterable', documentation: 'Iterates over iterable.', insertText: 'for ${1:item} in ${2:iterable}:\n    ${3:pass}', insertTextFormat: 2 },
  { label: 'list comprehension', kind: MonacoKind.Snippet, detail: 'list comprehension', documentation: 'List comprehension.', insertText: '[${1:x} for ${2:x} in ${3:iterable}]', insertTextFormat: 2 },
  { label: 'dict comprehension', kind: MonacoKind.Snippet, detail: 'dict comprehension', documentation: 'Dictionary comprehension.', insertText: '{${1:k}: ${2:v} for ${3:k}, ${4:v} in ${5:iterable}}', insertTextFormat: 2 },
  { label: 'set comprehension', kind: MonacoKind.Snippet, detail: 'set comprehension', documentation: 'Set comprehension.', insertText: '{${1:x} for ${2:x} in ${3:iterable}}', insertTextFormat: 2 },
  { label: 'generator expression', kind: MonacoKind.Snippet, detail: 'generator expression', documentation: 'Generator expression.', insertText: '(${1:x} for ${2:x} in ${3:iterable})', insertTextFormat: 2 },
  { label: 'with open() as f:', kind: MonacoKind.Snippet, detail: 'with file open', documentation: 'Opens file safely.', insertText: 'with open("${1:file}", "${2:r}") as ${3:f}:\n    ${4:pass}', insertTextFormat: 2 },
  { label: 'try-except', kind: MonacoKind.Snippet, detail: 'try-except block', documentation: 'Exception handling.', insertText: 'try:\n    ${1:pass}\nexcept ${2:Exception} as ${3:e}:\n    ${4:pass}', insertTextFormat: 2 },
  { label: 'try-except-else-finally', kind: MonacoKind.Snippet, detail: 'try-except-else-finally', documentation: 'Full exception handling.', insertText: 'try:\n    ${1:pass}\nexcept ${2:Exception} as ${3:e}:\n    ${4:pass}\nelse:\n    ${5:pass}\nfinally:\n    ${6:pass}', insertTextFormat: 2 },
  { label: 'raise', kind: MonacoKind.Snippet, detail: 'raise exception', documentation: 'Raises an exception.', insertText: 'raise ${1:Exception}("${2:message}")', insertTextFormat: 2 },
  { label: 'class definition', kind: MonacoKind.Snippet, detail: 'class definition', documentation: 'Creates a class.', insertText: 'class ${1:ClassName}:\n    def __init__(self${2:, args}):\n        ${3:pass}', insertTextFormat: 2 },
  { label: 'class inheritance', kind: MonacoKind.Snippet, detail: 'class with inheritance', documentation: 'Creates class inheriting from base.', insertText: 'class ${1:ClassName}(${2:BaseClass}):\n    def __init__(self${3:, args}):\n        super().__init__(${4:args})\n        ${5:pass}', insertTextFormat: 2 },
  { label: '@dataclass', kind: MonacoKind.Snippet, detail: 'dataclass', documentation: 'Creates a dataclass.', insertText: '@dataclass\nclass ${1:DataClassName}:\n    ${2:field1}: ${3:int}\n    ${4:field2}: ${5:str}', insertTextFormat: 2 },
  { label: '@property', kind: MonacoKind.Snippet, detail: 'property decorator', documentation: 'Defines property.', insertText: '@property\ndef ${1:name}(self):\n    return self._${1:name}\n\n@${1:name}.setter\ndef ${1:name}(self, value):\n    self._${1:name} = value', insertTextFormat: 2 },
  { label: 'pass', kind: MonacoKind.Snippet, detail: 'pass statement', documentation: 'No-op statement.', insertText: 'pass' },
  { label: '... (ellipsis)', kind: MonacoKind.Snippet, detail: 'ellipsis', documentation: 'Ellipsis literal.', insertText: '...' },
  { label: 'walrus :=', kind: MonacoKind.Snippet, detail: 'walrus operator', documentation: 'Assignment expression (:=).', insertText: '(${1:x} := ${2:expr})', insertTextFormat: 2 },
  { label: 'assert', kind: MonacoKind.Snippet, detail: 'assert statement', documentation: 'Asserts condition.', insertText: 'assert ${1:condition}${2:, "message"}', insertTextFormat: 2 },
  { label: 'yield', kind: MonacoKind.Snippet, detail: 'yield statement', documentation: 'Yields value from generator.', insertText: 'yield ${1:value}', insertTextFormat: 2 },
  { label: 'yield from', kind: MonacoKind.Snippet, detail: 'yield from', documentation: 'Yields from subgenerator.', insertText: 'yield from ${1:iterable}', insertTextFormat: 2 },
  { label: 'match...case', kind: MonacoKind.Snippet, detail: 'match-case (Python 3.10+)', documentation: 'Pattern matching.', insertText: 'match ${1:subject}:\n    case ${2:pattern}:\n        ${3:pass}', insertTextFormat: 2 },
];
