import { LspCompletionItem, MonacoKind } from './types';

export const TYPESCRIPT_API_COMPLETIONS: LspCompletionItem[] = [
  // Built-in types
  { label: 'string', kind: MonacoKind.Keyword, detail: 'string', documentation: 'String primitive type.', insertText: 'string' },
  { label: 'number', kind: MonacoKind.Keyword, detail: 'number', documentation: 'Number primitive type (int/float).', insertText: 'number' },
  { label: 'boolean', kind: MonacoKind.Keyword, detail: 'boolean', documentation: 'Boolean primitive type.', insertText: 'boolean' },
  { label: 'null', kind: MonacoKind.Keyword, detail: 'null', documentation: 'Null type.', insertText: 'null' },
  { label: 'undefined', kind: MonacoKind.Keyword, detail: 'undefined', documentation: 'Undefined type.', insertText: 'undefined' },
  { label: 'void', kind: MonacoKind.Keyword, detail: 'void', documentation: 'Void return type.', insertText: 'void' },
  { label: 'never', kind: MonacoKind.Keyword, detail: 'never', documentation: 'Never return type.', insertText: 'never' },
  { label: 'any', kind: MonacoKind.Keyword, detail: 'any', documentation: 'Any type, bypasses type checking.', insertText: 'any' },
  { label: 'unknown', kind: MonacoKind.Keyword, detail: 'unknown', documentation: 'Unknown type, must be narrowed.', insertText: 'unknown' },
  { label: 'object', kind: MonacoKind.Keyword, detail: 'object', documentation: 'Non-primitive type.', insertText: 'object' },
  { label: 'symbol', kind: MonacoKind.Keyword, detail: 'symbol', documentation: 'Symbol primitive type.', insertText: 'symbol' },
  { label: 'bigint', kind: MonacoKind.Keyword, detail: 'bigint', documentation: 'Big integer type.', insertText: 'bigint' },

  // TypeScript type keywords
  { label: 'type alias', kind: MonacoKind.Snippet, detail: 'type alias', documentation: 'Creates a type alias.', insertText: 'type ${1:Name} = ${2:string};', insertTextFormat: 2 },
  { label: 'interface', kind: MonacoKind.Snippet, detail: 'interface definition', documentation: 'Creates an interface.', insertText: 'interface ${1:InterfaceName} {\n    ${2:// properties}\n}', insertTextFormat: 2 },
  { label: 'interface extends', kind: MonacoKind.Snippet, detail: 'interface with extends', documentation: 'Creates an interface extending another.', insertText: 'interface ${1:Child} extends ${2:Parent} {\n    ${3:// properties}\n}', insertTextFormat: 2 },
  { label: 'class', kind: MonacoKind.Snippet, detail: 'class definition', documentation: 'Creates a class.', insertText: 'class ${1:ClassName} {\n    ${2:// constructor\n    // properties\n    // methods\n}', insertTextFormat: 2 },
  { label: 'class with constructor', kind: MonacoKind.Snippet, detail: 'class with constructor', documentation: 'Creates a class with constructor.', insertText: 'class ${1:ClassName} {\n    constructor(${2:args}) {\n        ${3:// initialization}\n    }\n}', insertTextFormat: 2 },
  { label: 'class extends', kind: MonacoKind.Snippet, detail: 'class with inheritance', documentation: 'Creates a class extending another.', insertText: 'class ${1:ChildClass} extends ${2:ParentClass} {\n    constructor(${3:args}) {\n        super(${3:args});\n    }\n}', insertTextFormat: 2 },
  { label: 'abstract class', kind: MonacoKind.Snippet, detail: 'abstract class', documentation: 'Creates an abstract class.', insertText: 'abstract class ${1:ClassName} {\n    abstract ${2:methodName}(${3:args}): ${4:void};\n}', insertTextFormat: 2 },
  { label: 'enum', kind: MonacoKind.Snippet, detail: 'enum definition', documentation: 'Creates an enum.', insertText: 'enum ${1:EnumName} {\n    ${2:Value1},\n    ${3:Value2},\n}', insertTextFormat: 2 },
  { label: 'const enum', kind: MonacoKind.Snippet, detail: 'const enum', documentation: 'Creates a const enum.', insertText: 'const enum ${1:EnumName} {\n    ${2:Value1},\n    ${3:Value2},\n}', insertTextFormat: 2 },
  { label: 'namespace', kind: MonacoKind.Snippet, detail: 'namespace', documentation: 'Creates a namespace.', insertText: 'namespace ${1:Namespace} {\n    ${2:// exports\n}', insertTextFormat: 2 },
  { label: 'declare module', kind: MonacoKind.Snippet, detail: 'declare module', documentation: 'Declares a module.', insertText: 'declare module "${1:module}" {\n    ${2:// exports\n}', insertTextFormat: 2 },
  { label: 'declare global', kind: MonacoKind.Snippet, detail: 'declare global', documentation: 'Declares global augmentations.', insertText: 'declare global {\n    ${1:// global declarations\n}', insertTextFormat: 2 },
  { label: 'declare function', kind: MonacoKind.Snippet, detail: 'declare function', documentation: 'Declares a function.', insertText: 'declare function ${1:funcName}(${2:args}): ${3:void};', insertTextFormat: 2 },
  { label: 'declare const', kind: MonacoKind.Snippet, detail: 'declare const', documentation: 'Declares a const.', insertText: 'declare const ${1:name}: ${2:type};', insertTextFormat: 2 },
  { label: 'declare class', kind: MonacoKind.Snippet, detail: 'declare class', documentation: 'Declares a class.', insertText: 'declare class ${1:ClassName} {\n    ${2:// members\n}', insertTextFormat: 2 },

  // Utility types
  { label: 'Partial<T>', kind: MonacoKind.Class, detail: 'Partial<T>', documentation: 'Makes all properties optional.', insertText: 'Partial<${1:T}>', insertTextFormat: 2 },
  { label: 'Required<T>', kind: MonacoKind.Class, detail: 'Required<T>', documentation: 'Makes all properties required.', insertText: 'Required<${1:T}>', insertTextFormat: 2 },
  { label: 'Readonly<T>', kind: MonacoKind.Class, detail: 'Readonly<T>', documentation: 'Makes all properties readonly.', insertText: 'Readonly<${1:T}>', insertTextFormat: 2 },
  { label: 'Pick<T, K>', kind: MonacoKind.Class, detail: 'Pick<T, K>', documentation: 'Picks properties from type.', insertText: 'Pick<${1:T}, ${2:K}>', insertTextFormat: 2 },
  { label: 'Omit<T, K>', kind: MonacoKind.Class, detail: 'Omit<T, K>', documentation: 'Omits properties from type.', insertText: 'Omit<${1:T}, ${2:K}>', insertTextFormat: 2 },
  { label: 'Record<K, V>', kind: MonacoKind.Class, detail: 'Record<K, V>', documentation: 'Creates object type with keys K and values V.', insertText: 'Record<${1:K}, ${2:V}>', insertTextFormat: 2 },
  { label: 'Exclude<T, U>', kind: MonacoKind.Class, detail: 'Exclude<T, U>', documentation: 'Excludes types from union.', insertText: 'Exclude<${1:T}, ${2:U}>', insertTextFormat: 2 },
  { label: 'Extract<T, U>', kind: MonacoKind.Class, detail: 'Extract<T, U>', documentation: 'Extracts types from union.', insertText: 'Extract<${1:T}, ${2:U}>', insertTextFormat: 2 },
  { label: 'NonNullable<T>', kind: MonacoKind.Class, detail: 'NonNullable<T>', documentation: 'Removes null and undefined.', insertText: 'NonNullable<${1:T}>', insertTextFormat: 2 },
  { label: 'ReturnType<T>', kind: MonacoKind.Class, detail: 'ReturnType<T>', documentation: 'Gets return type of function.', insertText: 'ReturnType<${1:T}>', insertTextFormat: 2 },
  { label: 'Parameters<T>', kind: MonacoKind.Class, detail: 'Parameters<T>', documentation: 'Gets parameter types of function.', insertText: 'Parameters<${1:T}>', insertTextFormat: 2 },
  { label: 'ConstructorParameters<T>', kind: MonacoKind.Class, detail: 'ConstructorParameters<T>', documentation: 'Gets constructor parameter types.', insertText: 'ConstructorParameters<${1:T}>', insertTextFormat: 2 },
  { label: 'InstanceType<T>', kind: MonacoKind.Class, detail: 'InstanceType<T>', documentation: 'Gets instance type of constructor.', insertText: 'InstanceType<${1:T}>', insertTextFormat: 2 },
  { label: 'ThisParameterType<T>', kind: MonacoKind.Class, detail: 'ThisParameterType<T>', documentation: 'Gets this parameter type.', insertText: 'ThisParameterType<${1:T}>', insertTextFormat: 2 },
  { label: 'OmitThisParameter<T>', kind: MonacoKind.Class, detail: 'OmitThisParameter<T>', documentation: 'Removes this parameter.', insertText: 'OmitThisParameter<${1:T}>', insertTextFormat: 2 },
  { label: 'ThisType<T>', kind: MonacoKind.Class, detail: 'ThisType<T>', documentation: 'Specifies this type in an object.', insertText: 'ThisType<${1:T}>', insertTextFormat: 2 },
  { label: 'intrinsic types', kind: MonacoKind.Snippet, detail: 'Intrinsic string manipulation types', documentation: 'String, Uppercase, Lowercase, Capitalize, Uncapitalize.', insertText: 'Uppercase<${1:string}>', insertTextFormat: 2 },
  { label: 'Awaited<T>', kind: MonacoKind.Class, detail: 'Awaited<T>', documentation: 'Unwraps Promise type (TS 4.5+).', insertText: 'Awaited<${1:T}>', insertTextFormat: 2 },

  // Control flow snippets
  { label: 'if statement', kind: MonacoKind.Snippet, detail: 'if statement', documentation: 'Creates an if statement.', insertText: 'if (${1:condition}) {\n    ${2:// code}\n}', insertTextFormat: 2 },
  { label: 'if-else', kind: MonacoKind.Snippet, detail: 'if-else statement', documentation: 'Creates an if-else statement.', insertText: 'if (${1:condition}) {\n    ${2:// code}\n} else {\n    ${3:// code}\n}', insertTextFormat: 2 },
  { label: 'else-if chain', kind: MonacoKind.Snippet, detail: 'else-if chain', documentation: 'Creates else-if chain.', insertText: 'if (${1:condition}) {\n    ${2:// code}\n} else if (${3:condition}) {\n    ${4:// code}\n} else {\n    ${5:// code}\n}', insertTextFormat: 2 },
  { label: 'for loop', kind: MonacoKind.Snippet, detail: 'for loop', documentation: 'Creates a for loop.', insertText: 'for (let ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n    ${3:// code}\n}', insertTextFormat: 2 },
  { label: 'for-of loop', kind: MonacoKind.Snippet, detail: 'for-of loop', documentation: 'Creates a for-of loop.', insertText: 'for (const ${1:item} of ${2:array}) {\n    ${3:// code}\n}', insertTextFormat: 2 },
  { label: 'for-in loop', kind: MonacoKind.Snippet, detail: 'for-in loop', documentation: 'Creates a for-in loop.', insertText: 'for (const ${1:key} in ${2:object}) {\n    ${3:// code}\n}', insertTextFormat: 2 },
  { label: 'while loop', kind: MonacoKind.Snippet, detail: 'while loop', documentation: 'Creates a while loop.', insertText: 'while (${1:condition}) {\n    ${2:// code}\n}', insertTextFormat: 2 },
  { label: 'do-while loop', kind: MonacoKind.Snippet, detail: 'do-while loop', documentation: 'Creates a do-while loop.', insertText: 'do {\n    ${1:// code}\n} while (${2:condition});', insertTextFormat: 2 },
  { label: 'switch', kind: MonacoKind.Snippet, detail: 'switch statement', documentation: 'Creates a switch statement.', insertText: 'switch (${1:expr}) {\n    case ${2:val1}:\n        ${3:// code}\n        break;\n    case ${4:val2}:\n        ${5:// code}\n        break;\n    default:\n        ${6:// code}\n}', insertTextFormat: 2 },
  { label: 'try-catch', kind: MonacoKind.Snippet, detail: 'try-catch block', documentation: 'Creates a try-catch block.', insertText: 'try {\n    ${1:// code}\n} catch (${2:error}) {\n    ${3:// handle error}\n}', insertTextFormat: 2 },
  { label: 'try-catch-finally', kind: MonacoKind.Snippet, detail: 'try-catch-finally', documentation: 'Creates a try-catch-finally block.', insertText: 'try {\n    ${1:// code}\n} catch (${2:error}) {\n    ${3:// handle error}\n} finally {\n    ${4:// cleanup}\n}', insertTextFormat: 2 },
  { label: 'throw', kind: MonacoKind.Snippet, detail: 'throw statement', documentation: 'Throws an error.', insertText: 'throw new ${1:Error}("${2:message}")', insertTextFormat: 2 },

  // Functions
  { label: 'function declaration', kind: MonacoKind.Snippet, detail: 'function declaration', documentation: 'Creates a function declaration.', insertText: 'function ${1:name}(${2:args}): ${3:void} {\n    ${4:// code}\n}', insertTextFormat: 2 },
  { label: 'arrow function', kind: MonacoKind.Snippet, detail: 'arrow function', documentation: 'Creates an arrow function.', insertText: '(${1:args}) => {\n    ${2:// code}\n}', insertTextFormat: 2 },
  { label: 'arrow function expression', kind: MonacoKind.Snippet, detail: 'arrow function expression', documentation: 'Creates an arrow function with implicit return.', insertText: '(${1:args}) => ${2:expr}', insertTextFormat: 2 },
  { label: 'async function', kind: MonacoKind.Snippet, detail: 'async function', documentation: 'Creates an async function.', insertText: 'async function ${1:name}(${2:args}): Promise<${3:void}> {\n    ${4:// code}\n}', insertTextFormat: 2 },
  { label: 'async arrow function', kind: MonacoKind.Snippet, detail: 'async arrow function', documentation: 'Creates an async arrow function.', insertText: 'async (${1:args}) => {\n    ${2:// code}\n}', insertTextFormat: 2 },
  { label: 'generator function', kind: MonacoKind.Snippet, detail: 'generator function', documentation: 'Creates a generator function.', insertText: 'function* ${1:name}(${2:args}): Generator<${3:T}> {\n    ${4:// code\n    yield ${5:value};\n}', insertTextFormat: 2 },
  { label: 'IIFE', kind: MonacoKind.Snippet, detail: 'Immediately Invoked Function Expression', documentation: 'Creates an IIFE.', insertText: '((${1:args}) => {\n    ${2:// code\n})(${3:args});', insertTextFormat: 2 },
  { label: 'callback pattern', kind: MonacoKind.Snippet, detail: 'callback pattern', documentation: 'Creates a callback pattern.', insertText: '(err: ${1:Error} | null, result?: ${2:T}) => {\n    ${3:// code\n}', insertTextFormat: 2 },
  { label: 'Promise-based function', kind: MonacoKind.Snippet, detail: 'Promise-returning function', documentation: 'Creates a function returning Promise.', insertText: 'function ${1:name}(${2:args}): Promise<${3:T}> {\n    return new Promise((${4:resolve}, ${5:reject}) => {\n        ${6:// code\n    });\n}', insertTextFormat: 2 },

  // Async/Await
  { label: 'await', kind: MonacoKind.Snippet, detail: 'await expression', documentation: 'Awaits a Promise.', insertText: 'await ${1:promise}', insertTextFormat: 2 },
  { label: 'Promise.all', kind: MonacoKind.Function, detail: 'Promise.all(promises)', documentation: 'Waits for all promises.', insertText: 'Promise.all(${1:promises})', insertTextFormat: 2 },
  { label: 'Promise.race', kind: MonacoKind.Function, detail: 'Promise.race(promises)', documentation: 'Resolves/rejects with first settled.', insertText: 'Promise.race(${1:promises})', insertTextFormat: 2 },
  { label: 'Promise.allSettled', kind: MonacoKind.Function, detail: 'Promise.allSettled(promises)', documentation: 'Waits for all promises to settle.', insertText: 'Promise.allSettled(${1:promises})', insertTextFormat: 2 },
  { label: 'Promise.any', kind: MonacoKind.Function, detail: 'Promise.any(promises)', documentation: 'Resolves with first fulfilled.', insertText: 'Promise.any(${1:promises})', insertTextFormat: 2 },
  { label: 'Promise.resolve', kind: MonacoKind.Function, detail: 'Promise.resolve(value)', documentation: 'Creates resolved Promise.', insertText: 'Promise.resolve(${1:value})', insertTextFormat: 2 },
  { label: 'Promise.reject', kind: MonacoKind.Function, detail: 'Promise.reject(error)', documentation: 'Creates rejected Promise.', insertText: 'Promise.reject(${1:error})', insertTextFormat: 2 },
  { label: 'new Promise', kind: MonacoKind.Snippet, detail: 'new Promise', documentation: 'Creates a new Promise.', insertText: 'new Promise<${1:T}>((resolve, reject) => {\n    ${2:// code\n})', insertTextFormat: 2 },

  // Array methods
  { label: 'array.map', kind: MonacoKind.Method, detail: 'map<U>(callback: (v: T, i: number) => U): U[]', documentation: 'Transforms each element.', insertText: '${1:array}.map((${2:item}) => ${3:item})', insertTextFormat: 2 },
  { label: 'array.filter', kind: MonacoKind.Method, detail: 'filter(predicate: (v: T) => boolean): T[]', documentation: 'Filters elements.', insertText: '${1:array}.filter((${2:item}) => ${3:condition})', insertTextFormat: 2 },
  { label: 'array.reduce', kind: MonacoKind.Method, detail: 'reduce<U>(callback: (acc: U, v: T) => U, init: U): U', documentation: 'Reduces array to single value.', insertText: '${1:array}.reduce((${2:acc}, ${3:item}) => ${4:acc + item}, ${5:0})', insertTextFormat: 2 },
  { label: 'array.forEach', kind: MonacoKind.Method, detail: 'forEach(callback: (v: T, i: number) => void): void', documentation: 'Iterates over elements.', insertText: '${1:array}.forEach((${2:item}) => {\n    ${3:// code\n})', insertTextFormat: 2 },
  { label: 'array.find', kind: MonacoKind.Method, detail: 'find(predicate: (v: T) => boolean): T | undefined', documentation: 'Finds first matching element.', insertText: '${1:array}.find((${2:item}) => ${3:condition})', insertTextFormat: 2 },
  { label: 'array.findIndex', kind: MonacoKind.Method, detail: 'findIndex(predicate: (v: T) => boolean): number', documentation: 'Finds index of first match.', insertText: '${1:array}.findIndex((${2:item}) => ${3:condition})', insertTextFormat: 2 },
  { label: 'array.some', kind: MonacoKind.Method, detail: 'some(predicate: (v: T) => boolean): boolean', documentation: 'Checks if any element matches.', insertText: '${1:array}.some((${2:item}) => ${3:condition})', insertTextFormat: 2 },
  { label: 'array.every', kind: MonacoKind.Method, detail: 'every(predicate: (v: T) => boolean): boolean', documentation: 'Checks if all elements match.', insertText: '${1:array}.every((${2:item}) => ${3:condition})', insertTextFormat: 2 },
  { label: 'array.includes', kind: MonacoKind.Method, detail: 'includes(searchElement: T): boolean', documentation: 'Checks if array includes element.', insertText: '${1:array}.includes(${2:value})', insertTextFormat: 2 },
  { label: 'array.indexOf', kind: MonacoKind.Method, detail: 'indexOf(searchElement: T): number', documentation: 'Returns index of element.', insertText: '${1:array}.indexOf(${2:value})', insertTextFormat: 2 },
  { label: 'array.slice', kind: MonacoKind.Method, detail: 'slice(start?, end?): T[]', documentation: 'Returns a shallow copy.', insertText: '${1:array}.slice(${2:start}, ${3:end})', insertTextFormat: 2 },
  { label: 'array.splice', kind: MonacoKind.Method, detail: 'splice(start: number, deleteCount?: number): T[]', documentation: 'Adds/removes elements.', insertText: '${1:array}.splice(${2:index}, ${3:deleteCount})', insertTextFormat: 2 },
  { label: 'array.concat', kind: MonacoKind.Method, detail: 'concat(...items: T[][]): T[]', documentation: 'Concatenates arrays.', insertText: '${1:array}.concat(${2:otherArray})', insertTextFormat: 2 },
  { label: 'array.join', kind: MonacoKind.Method, detail: 'join(separator?: string): string', documentation: 'Joins elements into string.', insertText: '${1:array}.join("${2:,}")', insertTextFormat: 2 },
  { label: 'array.sort', kind: MonacoKind.Method, detail: 'sort(compareFn?: (a: T, b: T) => number): T[]', documentation: 'Sorts array in place.', insertText: '${1:array}.sort((${2:a}, ${3:b}) => ${4:a - b})', insertTextFormat: 2 },
  { label: 'array.reverse', kind: MonacoKind.Method, detail: 'reverse(): T[]', documentation: 'Reverses array in place.', insertText: '${1:array}.reverse()' },
  { label: 'array.flat', kind: MonacoKind.Method, detail: 'flat(depth?: number): any[]', documentation: 'Flattens nested arrays.', insertText: '${1:array}.flat(${2:1})', insertTextFormat: 2 },
  { label: 'array.flatMap', kind: MonacoKind.Method, detail: 'flatMap<U>(callback: (v: T) => U[]): U[]', documentation: 'Maps then flattens.', insertText: '${1:array}.flatMap((${2:item}) => ${3:item})', insertTextFormat: 2 },
  { label: 'array.fill', kind: MonacoKind.Method, detail: 'fill(value: T, start?: number, end?: number): T[]', documentation: 'Fills array with value.', insertText: '${1:array}.fill(${2:value})', insertTextFormat: 2 },
  { label: 'array.copyWithin', kind: MonacoKind.Method, detail: 'copyWithin(target: number, start?: number, end?: number): T[]', documentation: 'Copies within array.', insertText: '${1:array}.copyWithin(${2:target}, ${3:start})', insertTextFormat: 2 },
  { label: 'Array.isArray', kind: MonacoKind.Function, detail: 'Array.isArray(value: any): boolean', documentation: 'Checks if value is array.', insertText: 'Array.isArray(${1:value})', insertTextFormat: 2 },
  { label: 'Array.from', kind: MonacoKind.Function, detail: 'Array.from<T>(arrayLike: ArrayLike<T>): T[]', documentation: 'Creates array from array-like.', insertText: 'Array.from(${1:arrayLike})', insertTextFormat: 2 },
  { label: 'Array.of', kind: MonacoKind.Function, detail: 'Array.of<T>(...elements: T[]): T[]', documentation: 'Creates array from arguments.', insertText: 'Array.of(${1:element})', insertTextFormat: 2 },

  // String methods
  { label: 'str.length', kind: MonacoKind.Property, detail: 'string.length', documentation: 'Returns string length.', insertText: '${1:str}.length' },
  { label: 'str.charAt', kind: MonacoKind.Method, detail: 'charAt(index: number): string', documentation: 'Returns character at index.', insertText: '${1:str}.charAt(${2:index})', insertTextFormat: 2 },
  { label: 'str.charCodeAt', kind: MonacoKind.Method, detail: 'charCodeAt(index: number): number', documentation: 'Returns character code.', insertText: '${1:str}.charCodeAt(${2:index})', insertTextFormat: 2 },
  { label: 'str.concat', kind: MonacoKind.Method, detail: 'concat(...strings: string[]): string', documentation: 'Concatenates strings.', insertText: '${1:str}.concat(${2:other})', insertTextFormat: 2 },
  { label: 'str.includes', kind: MonacoKind.Method, detail: 'includes(searchString: string): boolean', documentation: 'Checks if string includes substring.', insertText: '${1:str}.includes("${2:substring}")', insertTextFormat: 2 },
  { label: 'str.indexOf', kind: MonacoKind.Method, detail: 'indexOf(searchString: string): number', documentation: 'Returns first index of substring.', insertText: '${1:str}.indexOf("${2:substring}")', insertTextFormat: 2 },
  { label: 'str.lastIndexOf', kind: MonacoKind.Method, detail: 'lastIndexOf(searchString: string): number', documentation: 'Returns last index of substring.', insertText: '${1:str}.lastIndexOf("${2:substring}")', insertTextFormat: 2 },
  { label: 'str.match', kind: MonacoKind.Method, detail: 'match(regexp: RegExp): RegExpMatchArray | null', documentation: 'Matches against regex.', insertText: '${1:str}.match(/${2:pattern}/)', insertTextFormat: 2 },
  { label: 'str.matchAll', kind: MonacoKind.Method, detail: 'matchAll(regexp: RegExp): IterableIterator<RegExpMatchArray>', documentation: 'Matches all with regex.', insertText: '${1:str}.matchAll(/${2:pattern}/g)', insertTextFormat: 2 },
  { label: 'str.padEnd', kind: MonacoKind.Method, detail: 'padEnd(length: number, fillString?: string): string', documentation: 'Pads end of string.', insertText: "${1:str}.padEnd(${2:length}, \"${3:' '}\")", insertTextFormat: 2 },
  { label: 'str.padStart', kind: MonacoKind.Method, detail: 'padStart(length: number, fillString?: string): string', documentation: 'Pads start of string.', insertText: "${1:str}.padStart(${2:length}, \"${3:' '}\")", insertTextFormat: 2 },
  { label: 'str.repeat', kind: MonacoKind.Method, detail: 'repeat(count: number): string', documentation: 'Repeats string.', insertText: '${1:str}.repeat(${2:count})', insertTextFormat: 2 },
  { label: 'str.replace', kind: MonacoKind.Method, detail: 'replace(pattern: string | RegExp, replacement: string): string', documentation: 'Replaces first/all matches.', insertText: '${1:str}.replace(/${2:pattern}/, "${3:replacement}")', insertTextFormat: 2 },
  { label: 'str.replaceAll', kind: MonacoKind.Method, detail: 'replaceAll(pattern: string | RegExp, replacement: string): string', documentation: 'Replaces all matches.', insertText: '${1:str}.replaceAll(/${2:pattern}/g, "${3:replacement}")', insertTextFormat: 2 },
  { label: 'str.search', kind: MonacoKind.Method, detail: 'search(regexp: RegExp): number', documentation: 'Searches for pattern.', insertText: '${1:str}.search(/${2:pattern}/)', insertTextFormat: 2 },
  { label: 'str.slice', kind: MonacoKind.Method, detail: 'slice(start?: number, end?: number): string', documentation: 'Extracts portion.', insertText: '${1:str}.slice(${2:start}, ${3:end})', insertTextFormat: 2 },
  { label: 'str.split', kind: MonacoKind.Method, detail: 'split(separator: string | RegExp): string[]', documentation: 'Splits string.', insertText: '${1:str}.split("${2:separator}")', insertTextFormat: 2 },
  { label: 'str.startsWith', kind: MonacoKind.Method, detail: 'startsWith(searchString: string): boolean', documentation: 'Checks if starts with.', insertText: '${1:str}.startsWith("${2:prefix}")', insertTextFormat: 2 },
  { label: 'str.endsWith', kind: MonacoKind.Method, detail: 'endsWith(searchString: string): boolean', documentation: 'Checks if ends with.', insertText: '${1:str}.endsWith("${2:suffix}")', insertTextFormat: 2 },
  { label: 'str.substring', kind: MonacoKind.Method, detail: 'substring(indexStart: number, indexEnd?: number): string', documentation: 'Extracts substring.', insertText: '${1:str}.substring(${2:start}, ${3:end})', insertTextFormat: 2 },
  { label: 'str.toLowerCase', kind: MonacoKind.Method, detail: 'toLowerCase(): string', documentation: 'Converts to lowercase.', insertText: '${1:str}.toLowerCase()' },
  { label: 'str.toUpperCase', kind: MonacoKind.Method, detail: 'toUpperCase(): string', documentation: 'Converts to uppercase.', insertText: '${1:str}.toUpperCase()' },
  { label: 'str.trim', kind: MonacoKind.Method, detail: 'trim(): string', documentation: 'Removes whitespace.', insertText: '${1:str}.trim()' },
  { label: 'str.trimStart', kind: MonacoKind.Method, detail: 'trimStart(): string', documentation: 'Removes leading whitespace.', insertText: '${1:str}.trimStart()' },
  { label: 'str.trimEnd', kind: MonacoKind.Method, detail: 'trimEnd(): string', documentation: 'Removes trailing whitespace.', insertText: '${1:str}.trimEnd()' },
  { label: 'str.valueOf', kind: MonacoKind.Method, detail: 'valueOf(): string', documentation: 'Returns string value.', insertText: '${1:str}.valueOf()' },
  { label: 'String.fromCharCode', kind: MonacoKind.Function, detail: 'String.fromCharCode(...codes: number[]): string', documentation: 'Creates string from codes.', insertText: 'String.fromCharCode(${1:code})', insertTextFormat: 2 },
  { label: 'String.fromCodePoint', kind: MonacoKind.Function, detail: 'String.fromCodePoint(...points: number[]): string', documentation: 'Creates string from code points.', insertText: 'String.fromCodePoint(${1:point})', insertTextFormat: 2 },
  { label: 'str template literal', kind: MonacoKind.Snippet, detail: 'Template literal', documentation: 'Creates a template literal.', insertText: '`${1:${2:variable}}`', insertTextFormat: 2 },

  // Object methods
  { label: 'Object.keys', kind: MonacoKind.Function, detail: 'Object.keys(value: object): string[]', documentation: 'Returns keys of object.', insertText: 'Object.keys(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.values', kind: MonacoKind.Function, detail: 'Object.values(value: object): any[]', documentation: 'Returns values of object.', insertText: 'Object.values(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.entries', kind: MonacoKind.Function, detail: 'Object.entries(value: object): [string, any][]', documentation: 'Returns key-value pairs.', insertText: 'Object.entries(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.assign', kind: MonacoKind.Function, detail: 'Object.assign<T>(target: T, ...sources: any[]): T', documentation: 'Assigns properties.', insertText: 'Object.assign(${1:target}, ${2:source})', insertTextFormat: 2 },
  { label: 'Object.create', kind: MonacoKind.Function, detail: 'Object.create(proto: object | null): any', documentation: 'Creates object with prototype.', insertText: 'Object.create(${1:proto})', insertTextFormat: 2 },
  { label: 'Object.freeze', kind: MonacoKind.Function, detail: 'Object.freeze<T>(obj: T): T', documentation: 'Freezes object.', insertText: 'Object.freeze(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.seal', kind: MonacoKind.Function, detail: 'Object.seal<T>(obj: T): T', documentation: 'Seals object.', insertText: 'Object.seal(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.is', kind: MonacoKind.Function, detail: 'Object.is(value1: any, value2: any): boolean', documentation: 'Compares values.', insertText: 'Object.is(${1:a}, ${2:b})', insertTextFormat: 2 },
  { label: 'Object.hasOwn', kind: MonacoKind.Function, detail: 'Object.hasOwn(obj: object, prop: string): boolean', documentation: 'Checks own property (TS 4.9+).', insertText: 'Object.hasOwn(${1:obj}, "${2:prop}")', insertTextFormat: 2 },
  { label: 'Object.defineProperty', kind: MonacoKind.Function, detail: 'Object.defineProperty(obj, prop, descriptor)', documentation: 'Defines property.', insertText: 'Object.defineProperty(${1:obj}, "${2:prop}", { ${3:config} })', insertTextFormat: 2 },
  { label: 'Object.getOwnPropertyNames', kind: MonacoKind.Function, detail: 'Object.getOwnPropertyNames(obj): string[]', documentation: 'Returns all property names.', insertText: 'Object.getOwnPropertyNames(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.getPrototypeOf', kind: MonacoKind.Function, detail: 'Object.getPrototypeOf(obj): object', documentation: 'Returns prototype.', insertText: 'Object.getPrototypeOf(${1:obj})', insertTextFormat: 2 },
  { label: 'Object.setPrototypeOf', kind: MonacoKind.Function, detail: 'Object.setPrototypeOf(obj, proto)', documentation: 'Sets prototype.', insertText: 'Object.setPrototypeOf(${1:obj}, ${2:proto})', insertTextFormat: 2 },

  // JSON
  { label: 'JSON.parse', kind: MonacoKind.Function, detail: 'JSON.parse(text: string): any', documentation: 'Parses JSON string.', insertText: 'JSON.parse(${1:text})', insertTextFormat: 2 },
  { label: 'JSON.stringify', kind: MonacoKind.Function, detail: 'JSON.stringify(value: any): string', documentation: 'Stringifies to JSON.', insertText: 'JSON.stringify(${1:value})', insertTextFormat: 2 },

  // Math
  { label: 'Math.PI', kind: MonacoKind.Constant, detail: 'Math.PI', documentation: 'Value of pi.', insertText: 'Math.PI' },
  { label: 'Math.E', kind: MonacoKind.Constant, detail: 'Math.E', documentation: 'Value of e.', insertText: 'Math.E' },
  { label: 'Math.abs', kind: MonacoKind.Function, detail: 'Math.abs(x: number): number', documentation: 'Absolute value.', insertText: 'Math.abs(${1:x})', insertTextFormat: 2 },
  { label: 'Math.max', kind: MonacoKind.Function, detail: 'Math.max(...values: number[]): number', documentation: 'Maximum value.', insertText: 'Math.max(${1:values})', insertTextFormat: 2 },
  { label: 'Math.min', kind: MonacoKind.Function, detail: 'Math.min(...values: number[]): number', documentation: 'Minimum value.', insertText: 'Math.min(${1:values})', insertTextFormat: 2 },
  { label: 'Math.pow', kind: MonacoKind.Function, detail: 'Math.pow(base: number, exponent: number): number', documentation: 'Power function.', insertText: 'Math.pow(${1:base}, ${2:exp})', insertTextFormat: 2 },
  { label: 'Math.sqrt', kind: MonacoKind.Function, detail: 'Math.sqrt(x: number): number', documentation: 'Square root.', insertText: 'Math.sqrt(${1:x})', insertTextFormat: 2 },
  { label: 'Math.cbrt', kind: MonacoKind.Function, detail: 'Math.cbrt(x: number): number', documentation: 'Cube root.', insertText: 'Math.cbrt(${1:x})', insertTextFormat: 2 },
  { label: 'Math.ceil', kind: MonacoKind.Function, detail: 'Math.ceil(x: number): number', documentation: 'Ceiling function.', insertText: 'Math.ceil(${1:x})', insertTextFormat: 2 },
  { label: 'Math.floor', kind: MonacoKind.Function, detail: 'Math.floor(x: number): number', documentation: 'Floor function.', insertText: 'Math.floor(${1:x})', insertTextFormat: 2 },
  { label: 'Math.round', kind: MonacoKind.Function, detail: 'Math.round(x: number): number', documentation: 'Rounds to nearest.', insertText: 'Math.round(${1:x})', insertTextFormat: 2 },
  { label: 'Math.trunc', kind: MonacoKind.Function, detail: 'Math.trunc(x: number): number', documentation: 'Truncates decimal.', insertText: 'Math.trunc(${1:x})', insertTextFormat: 2 },
  { label: 'Math.sin', kind: MonacoKind.Function, detail: 'Math.sin(x: number): number', documentation: 'Sine function.', insertText: 'Math.sin(${1:x})', insertTextFormat: 2 },
  { label: 'Math.cos', kind: MonacoKind.Function, detail: 'Math.cos(x: number): number', documentation: 'Cosine function.', insertText: 'Math.cos(${1:x})', insertTextFormat: 2 },
  { label: 'Math.tan', kind: MonacoKind.Function, detail: 'Math.tan(x: number): number', documentation: 'Tangent function.', insertText: 'Math.tan(${1:x})', insertTextFormat: 2 },
  { label: 'Math.asin', kind: MonacoKind.Function, detail: 'Math.asin(x: number): number', documentation: 'Arc sine.', insertText: 'Math.asin(${1:x})', insertTextFormat: 2 },
  { label: 'Math.acos', kind: MonacoKind.Function, detail: 'Math.acos(x: number): number', documentation: 'Arc cosine.', insertText: 'Math.acos(${1:x})', insertTextFormat: 2 },
  { label: 'Math.atan', kind: MonacoKind.Function, detail: 'Math.atan(x: number): number', documentation: 'Arc tangent.', insertText: 'Math.atan(${1:x})', insertTextFormat: 2 },
  { label: 'Math.atan2', kind: MonacoKind.Function, detail: 'Math.atan2(y: number, x: number): number', documentation: 'Two-argument arc tangent.', insertText: 'Math.atan2(${1:y}, ${2:x})', insertTextFormat: 2 },
  { label: 'Math.exp', kind: MonacoKind.Function, detail: 'Math.exp(x: number): number', documentation: 'Exponential e^x.', insertText: 'Math.exp(${1:x})', insertTextFormat: 2 },
  { label: 'Math.log', kind: MonacoKind.Function, detail: 'Math.log(x: number): number', documentation: 'Natural logarithm.', insertText: 'Math.log(${1:x})', insertTextFormat: 2 },
  { label: 'Math.log10', kind: MonacoKind.Function, detail: 'Math.log10(x: number): number', documentation: 'Base-10 logarithm.', insertText: 'Math.log10(${1:x})', insertTextFormat: 2 },
  { label: 'Math.log2', kind: MonacoKind.Function, detail: 'Math.log2(x: number): number', documentation: 'Base-2 logarithm.', insertText: 'Math.log2(${1:x})', insertTextFormat: 2 },
  { label: 'Math.random', kind: MonacoKind.Function, detail: 'Math.random(): number', documentation: 'Random 0-1.', insertText: 'Math.random()' },
  { label: 'Math.sign', kind: MonacoKind.Function, detail: 'Math.sign(x: number): number', documentation: 'Sign of number.', insertText: 'Math.sign(${1:x})', insertTextFormat: 2 },
  { label: 'Number.isNaN', kind: MonacoKind.Function, detail: 'Number.isNaN(value: number): boolean', documentation: 'Checks for NaN.', insertText: 'Number.isNaN(${1:value})', insertTextFormat: 2 },
  { label: 'Number.isFinite', kind: MonacoKind.Function, detail: 'Number.isFinite(value: number): boolean', documentation: 'Checks if finite.', insertText: 'Number.isFinite(${1:value})', insertTextFormat: 2 },
  { label: 'Number.isInteger', kind: MonacoKind.Function, detail: 'Number.isInteger(value: number): boolean', documentation: 'Checks if integer.', insertText: 'Number.isInteger(${1:value})', insertTextFormat: 2 },
  { label: 'Number.parseInt', kind: MonacoKind.Function, detail: 'Number.parseInt(s: string, radix?: number): number', documentation: 'Parses integer.', insertText: 'Number.parseInt(${1:s})', insertTextFormat: 2 },
  { label: 'Number.parseFloat', kind: MonacoKind.Function, detail: 'Number.parseFloat(s: string): number', documentation: 'Parses float.', insertText: 'Number.parseFloat(${1:s})', insertTextFormat: 2 },

  // RegExp
  { label: 'RegExp', kind: MonacoKind.Class, detail: 'new RegExp(pattern: string | RegExp, flags?: string)', documentation: 'Creates a RegExp.', insertText: '/${1:pattern}/${2:flags}', insertTextFormat: 2 },
  { label: 'regExp.test', kind: MonacoKind.Method, detail: 'test(str: string): boolean', documentation: 'Tests if pattern matches.', insertText: '/${1:pattern}/.test(${2:str})', insertTextFormat: 2 },
  { label: 'regExp.exec', kind: MonacoKind.Method, detail: 'exec(str: string): RegExpExecArray | null', documentation: 'Executes pattern.', insertText: '/${1:pattern}/${2:g}.exec(${3:str})', insertTextFormat: 2 },

  // Date
  { label: 'Date.now', kind: MonacoKind.Function, detail: 'Date.now(): number', documentation: 'Current timestamp.', insertText: 'Date.now()' },
  { label: 'new Date()', kind: MonacoKind.Class, detail: 'new Date()', documentation: 'Creates Date object.', insertText: 'new Date()' },
  { label: 'date.toISOString', kind: MonacoKind.Method, detail: 'toISOString(): string', documentation: 'ISO format string.', insertText: '${1:date}.toISOString()' },
  { label: 'date.toLocaleDateString', kind: MonacoKind.Method, detail: 'toLocaleDateString(locale?: string): string', documentation: 'Locale date string.', insertText: '${1:date}.toLocaleDateString()' },
  { label: 'date.toLocaleTimeString', kind: MonacoKind.Method, detail: 'toLocaleTimeString(locale?: string): string', documentation: 'Locale time string.', insertText: '${1:date}.toLocaleTimeString()' },
  { label: 'Date.parse', kind: MonacoKind.Function, detail: 'Date.parse(s: string): number', documentation: 'Parses date string.', insertText: 'Date.parse("${1:date}")', insertTextFormat: 2 },

  // Console
  { label: 'console.log', kind: MonacoKind.Function, detail: 'console.log(...data: any[]): void', documentation: 'Logs to console.', insertText: 'console.log(${1:value})', insertTextFormat: 2 },
  { label: 'console.error', kind: MonacoKind.Function, detail: 'console.error(...data: any[]): void', documentation: 'Logs error.', insertText: 'console.error(${1:value})', insertTextFormat: 2 },
  { label: 'console.warn', kind: MonacoKind.Function, detail: 'console.warn(...data: any[]): void', documentation: 'Logs warning.', insertText: 'console.warn(${1:value})', insertTextFormat: 2 },
  { label: 'console.info', kind: MonacoKind.Function, detail: 'console.info(...data: any[]): void', documentation: 'Logs info.', insertText: 'console.info(${1:value})', insertTextFormat: 2 },
  { label: 'console.debug', kind: MonacoKind.Function, detail: 'console.debug(...data: any[]): void', documentation: 'Logs debug.', insertText: 'console.debug(${1:value})', insertTextFormat: 2 },
  { label: 'console.table', kind: MonacoKind.Function, detail: 'console.table(data: any): void', documentation: 'Logs as table.', insertText: 'console.table(${1:data})', insertTextFormat: 2 },
  { label: 'console.group', kind: MonacoKind.Function, detail: 'console.group(...label: any[]): void', documentation: 'Starts group.', insertText: 'console.group("${1:label}")', insertTextFormat: 2 },
  { label: 'console.groupEnd', kind: MonacoKind.Function, detail: 'console.groupEnd(): void', documentation: 'Ends group.', insertText: 'console.groupEnd()' },
  { label: 'console.time', kind: MonacoKind.Function, detail: 'console.time(label: string): void', documentation: 'Starts timer.', insertText: 'console.time("${1:label}")', insertTextFormat: 2 },
  { label: 'console.timeEnd', kind: MonacoKind.Function, detail: 'console.timeEnd(label: string): void', documentation: 'Ends timer.', insertText: 'console.timeEnd("${1:label}")', insertTextFormat: 2 },
  { label: 'console.assert', kind: MonacoKind.Function, detail: 'console.assert(condition: any, ...data: any[]): void', documentation: 'Asserts condition.', insertText: 'console.assert(${1:condition}, ${2:message})', insertTextFormat: 2 },
  { label: 'console.trace', kind: MonacoKind.Function, detail: 'console.trace(...data: any[]): void', documentation: 'Logs stack trace.', insertText: 'console.trace(${1:message})', insertTextFormat: 2 },

  // Console / global utils
  { label: 'typeof', kind: MonacoKind.Keyword, detail: 'typeof operator', documentation: 'Returns type as string.', insertText: 'typeof ${1:value}' },
  { label: 'instanceof', kind: MonacoKind.Keyword, detail: 'instanceof operator', documentation: 'Checks prototype chain.', insertText: '${1:value} instanceof ${2:Class}' },
  { label: 'delete', kind: MonacoKind.Keyword, detail: 'delete operator', documentation: 'Deletes property.', insertText: 'delete ${1:obj.${2:prop}}', insertTextFormat: 2 },
  { label: 'in', kind: MonacoKind.Keyword, detail: 'in operator', documentation: 'Checks if property exists.', insertText: '"${1:prop}" in ${2:obj}', insertTextFormat: 2 },
  { label: 'new', kind: MonacoKind.Keyword, detail: 'new operator', documentation: 'Creates instance.', insertText: 'new ${1:Class}(${2:args})', insertTextFormat: 2 },
  { label: 'this', kind: MonacoKind.Keyword, detail: 'this keyword', documentation: 'Current this context.', insertText: 'this' },
  { label: 'super', kind: MonacoKind.Keyword, detail: 'super keyword', documentation: 'Parent class reference.', insertText: 'super.${1:method}()', insertTextFormat: 2 },
  { label: 'debugger', kind: MonacoKind.Keyword, detail: 'debugger statement', documentation: 'Debugger breakpoint.', insertText: 'debugger;' },

  // Nullish operators
  { label: '?? (nullish coalescing)', kind: MonacoKind.Operator, detail: '?? operator', documentation: 'Nullish coalescing.', insertText: '${1:value} ?? ${2:defaultValue}', insertTextFormat: 2 },
  { label: '?. (optional chaining)', kind: MonacoKind.Operator, detail: '?. operator', documentation: 'Optional chaining.', insertText: '${1:obj}?.${2:prop}', insertTextFormat: 2 },
  { label: '?.() (optional call)', kind: MonacoKind.Operator, detail: '?.() optional call', documentation: 'Optional method call.', insertText: '${1:obj}?.${2:method}()', insertTextFormat: 2 },
  { label: '?.[] (optional index)', kind: MonacoKind.Operator, detail: '?.[] optional index', documentation: 'Optional index access.', insertText: '${1:arr}?.[${2:index}]', insertTextFormat: 2 },
  { label: '??= (nullish assignment)', kind: MonacoKind.Operator, detail: '??= assignment', documentation: 'Assigns if nullish.', insertText: '${1:value} ??= ${2:defaultValue}', insertTextFormat: 2 },

  // Generics
  { label: 'generic function', kind: MonacoKind.Snippet, detail: 'Generic function', documentation: 'Creates a generic function.', insertText: 'function ${1:name}<T>(${2:arg}: T): T {\n    ${3:// code}\n}', insertTextFormat: 2 },
  { label: 'generic arrow function', kind: MonacoKind.Snippet, detail: 'Generic arrow function', documentation: 'Creates a generic arrow function.', insertText: '<T,>(${1:arg}: T): T => {\n    ${2:// code}\n}', insertTextFormat: 2 },
  { label: 'generic class', kind: MonacoKind.Snippet, detail: 'Generic class', documentation: 'Creates a generic class.', insertText: 'class ${1:ClassName}<T> {\n    ${2:property}: T;\n    constructor(${3:arg}: T) {\n        this.${2:property} = ${3:arg};\n    }\n}', insertTextFormat: 2 },
  { label: 'generic interface', kind: MonacoKind.Snippet, detail: 'Generic interface', documentation: 'Creates a generic interface.', insertText: 'interface ${1:Name}<T> {\n    ${2:property}: T;\n}', insertTextFormat: 2 },
  { label: 'generic type constraint', kind: MonacoKind.Snippet, detail: 'Generic with constraint', documentation: 'Creates a generic with extends constraint.', insertText: 'function ${1:name}<T extends ${2:Constraint}>(${3:arg}: T): T {\n    ${4:// code}\n}', insertTextFormat: 2 },
  { label: 'keyof', kind: MonacoKind.Keyword, detail: 'keyof operator', documentation: 'Gets keys of type.', insertText: 'keyof ${1:T}' },
  { label: 'typeof (type query)', kind: MonacoKind.Keyword, detail: 'typeof type query', documentation: 'Gets type of value.', insertText: 'typeof ${1:value}' },
  { label: 'as (type assertion)', kind: MonacoKind.Keyword, detail: 'as type assertion', documentation: 'Asserts type.', insertText: '${1:value} as ${2:Type}' },
  { label: '<Type> (type assertion)', kind: MonacoKind.Keyword, detail: '<Type> assertion', documentation: 'Asserts type (JSX compatible).', insertText: '<${1:Type}>${2:value}', insertTextFormat: 2 },

  // TypeScript specific
  { label: 'satisfies', kind: MonacoKind.Keyword, detail: 'satisfies operator (TS 4.9+)', documentation: 'Validates type without widening.', insertText: '${1:value} satisfies ${2:Type}', insertTextFormat: 2 },
  { label: 'inference with infer', kind: MonacoKind.Keyword, detail: 'infer keyword', documentation: 'Infers type in conditional.', insertText: 'T extends ${1:infer} R ? R : never' },
  { label: 'readonly', kind: MonacoKind.Keyword, detail: 'readonly modifier', documentation: 'Makes property readonly.', insertText: 'readonly ${1:property}: ${2:type}' },
  { label: 'as const', kind: MonacoKind.Keyword, detail: 'as const assertion', documentation: 'Narrows to literal types.', insertText: '${1:value} as const' },
  { label: 'import type', kind: MonacoKind.Snippet, detail: 'import type', documentation: 'Imports only types.', insertText: 'import type { ${1:Type} } from "${2:module}";', insertTextFormat: 2 },
  { label: 'export type', kind: MonacoKind.Snippet, detail: 'export type', documentation: 'Exports a type.', insertText: 'export type ${1:Name} = ${2:type};', insertTextFormat: 2 },
  { label: 'namespace import', kind: MonacoKind.Snippet, detail: 'namespace import', documentation: 'Imports namespace/module.', insertText: 'import * as ${1:Namespace} from "${2:module}";', insertTextFormat: 2 },
  { label: 'require', kind: MonacoKind.Snippet, detail: 'require (CommonJS)', documentation: 'CommonJS require.', insertText: 'const ${1:name} = require("${2:module}");', insertTextFormat: 2 },
  { label: 'export default', kind: MonacoKind.Snippet, detail: 'export default', documentation: 'Default export.', insertText: 'export default ${1:value};', insertTextFormat: 2 },
  { label: 'export named', kind: MonacoKind.Snippet, detail: 'export named', documentation: 'Named export.', insertText: 'export { ${1:name} };', insertTextFormat: 2 },
  { label: 'import', kind: MonacoKind.Snippet, detail: 'import', documentation: 'Named import.', insertText: 'import { ${1:name} } from "${2:module}";', insertTextFormat: 2 },
  { label: 'import default', kind: MonacoKind.Snippet, detail: 'import default', documentation: 'Default import.', insertText: 'import ${1:name} from "${2:module}";', insertTextFormat: 2 },
  { label: 'import side-effect', kind: MonacoKind.Snippet, detail: 'import side-effect', documentation: 'Side-effect only import.', insertText: 'import "${1:module}";', insertTextFormat: 2 },
  { label: 'import dynamic', kind: MonacoKind.Snippet, detail: 'dynamic import', documentation: 'Dynamic import.', insertText: 'const ${1:module} = await import("${2:module}");', insertTextFormat: 2 },

  // Mapped types
  { label: '-readonly', kind: MonacoKind.Keyword, detail: '-readonly modifier', documentation: 'Removes readonly.', insertText: '-readonly' },
  { label: '?', kind: MonacoKind.Keyword, detail: 'optional modifier', documentation: 'Makes property optional.', insertText: '?' },
  { label: '-?', kind: MonacoKind.Keyword, detail: '-? modifier', documentation: 'Removes optional.', insertText: '-?' },
];
