export { Skeleton, SkeletonText } from "./skeleton";
export { ClassroomListSkeleton } from "./ClassroomListSkeleton";
export { StudentDashboardSkeleton } from "./StudentDashboardSkeleton";
export { LecturerDashboardSkeleton } from "./LecturerDashboardSkeleton";
export { ExamsSkeleton } from "./ExamsSkeleton";
export { QuizzesSkeleton } from "./QuizzesSkeleton";
export { MaterialsSkeleton } from "./MaterialsSkeleton";
export { StudentListSkeleton } from "./StudentListSkeleton";
export { ClassroomOverviewSkeleton } from "./ClassroomOverviewSkeleton";
export { NotificationsSkeleton } from "./NotificationsSkeleton";
export { QuizDetailSkeleton } from "./QuizDetailSkeleton";
export { OverviewTabSkeleton } from "./OverviewTabSkeleton";
export { DiscussionTabSkeleton } from "./DiscussionTabSkeleton";
export { SlotsTabSkeleton } from "./SlotsTabSkeleton";
export { PractiseTabSkeleton } from "./PractiseTabSkeleton";
export { ClassroomDetailPageSkeleton } from "./ClassroomDetailPageSkeleton";
export { ManageClassroomPageSkeleton } from "./ManageClassroomPageSkeleton";
export { DashboardTabSkeleton } from "./DashboardTabSkeleton";
export { ExamsTabSkeleton } from "./ExamsTabSkeleton";
export { QuizzesTabSkeleton } from "./QuizzesTabSkeleton";
export { StudentTabSkeleton } from "./StudentTabSkeleton";
export { MaterialsTabSkeleton } from "./MaterialsTabSkeleton";
export { AdminDashboardSkeleton } from "./AdminDashboardSkeleton";
export { UserManagementSkeleton } from "./UserManagementSkeleton";
export { ClassesManagementSkeleton } from "./ClassesManagementSkeleton";
export { SubjectsManagementSkeleton } from "./SubjectsManagementSkeleton";
export { AdminMaterialsSkeleton } from "./AdminMaterialsSkeleton";
export { AdminDiscussionsSkeleton } from "./AdminDiscussionsSkeleton";
export { NotificationsManagementSkeleton } from "./NotificationsManagementSkeleton";
export { ProgrammingLanguagesManagementSkeleton } from "./ProgrammingLanguagesManagementSkeleton";
export { QuestionBanksSkeleton } from "./QuestionBanksSkeleton";
export { ProblemBanksSkeleton } from "./ProblemBanksSkeleton";
export { ExamBanksSkeleton } from "./ExamBanksSkeleton";
export { QuizBanksSkeleton } from "./QuizBanksSkeleton";
export { QuizDetailPageSkeleton } from "./QuizDetailPageSkeleton";
export { QuestionBankModalSkeleton } from "./QuestionBankModalSkeleton";
export { ExamDetailPanelSkeleton } from "./ExamDetailPanelSkeleton";
export { SubmissionsTabSkeleton } from "./SubmissionsTabSkeleton";
export { SubmissionDetailModalSkeleton } from "./SubmissionDetailModalSkeleton";
export { RegradingModalSkeleton } from "./RegradingModalSkeleton";
export { ProblemPanelSkeleton, ProblemPanelSkeletonContent, SubmissionsTabSkeleton as ProblemPanelSubmissionsSkeleton } from "./ProblemPanelSkeleton";
export { DefaultPageSkeleton, NotificationsSectionSkeleton, } from "./DefaultPageSkeleton";
export { ExamSessionTabSkeleton } from "./ExamSessionTabSkeleton";
export { ExamDetailTabSkeleton, SubmissionsTabSkeleton as ExamSubmissionsTabSkeleton, SubmissionDetailTabSkeleton } from "./ExamDetailTabSkeleton";
export { ProblemsTabSkeleton } from "./ProblemsTabSkeleton";
export { SimilarityTabSkeleton, SimilarityDiffModalSkeleton } from "./SimilarityTabSkeleton";
